### ISSUE TITLE
Interfaces do not open on the top

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#101]
**Describe the bug**
Interfaces do not open at the top after user create your account (example: Dashboard).

**To Reproduce**
1. Go to Dashboard for the first time after create your account;

**Expected behavior**

- Interface should open on the top and show all content, as this image:

![Screenshot_2019-12-05-14-34-45-323_com android chrome](https://user-images.githubusercontent.com/39558132/70259436-edb21800-176c-11ea-9bdd-e57e672c22b1.png)

**Screenshots**

**- Error example (content start on actions) as this image:**

![Screenshot_2019-12-05-14-30-20-806_com android chrome](https://user-images.githubusercontent.com/39558132/70259399-da06b180-176c-11ea-918b-42386ecfcb6a.png)

**Cambiatus Env you are using**
- muda.cambiatus.io

**Desktop (please complete the following information):**
 - Not tested

**Smartphone (please complete the following information):**
 - Device: Samsung and iPhone
 - OS: Android ans iOS
 - Browser: Chrome and Safari
 - Version: --

**Additional context**
--

**Comment by lucca65** [comment]
@heltonlr can you be more specific on the "should open on the top". What should open in the top? Are there print screens?

**Comment by heltonlr** [comment]
> @heltonlr can you be more specific on the "should open on the top". What should open in the top? Are there print screens?

Sure @lucca65, print addeded. Basically, the interface already loads in half of content as show this image

![Screenshot_2019-12-05-14-30-20-806_com android chrome](https://user-images.githubusercontent.com/39558132/70259841-cc9df700-176d-11ea-9bf6-f2a28facfc46.png)

**Comment by lucca65** [comment]
@heltonhr are you talking about the scroll position?

**Comment by zacck** [comment]
Ahhh so the focus is on the wrong part of the page when the application first loads

**Comment by heltonlr** [comment]
Also occurring in the PDF interface, Loads exactly that way:
![Screenshot_2020-01-28-08-48-03-155_com android chrome](https://user-images.githubusercontent.com/39558132/73264980-c008ae80-41b2-11ea-8747-dfc72b2c0484.jpg)

**Comment by zacck** [comment]
@heltonlr  noted

**Comment by heltonlr** [comment]
@zacck, is exactly what is happen.

**Comment by lucca65** [comment]
fixed after we recreated the new login screen #224
