### ISSUE TITLE
Change select element to tab element in Shop

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#104]
To make it easy for the user to find your offers. Also removing the filter "Offers from my communities", leaving only "All offers" (from the community I'm accessing) and "My offers".

**DESK**
<img width="1357" alt="Captura de Tela 2019-12-09 às 10 26 10" src="https://user-images.githubusercontent.com/39558132/70439575-20ab2300-1a6f-11ea-9250-3ac283de136f.png">

**MOBILE**
<img width="702" alt="Captura de Tela 2019-12-09 às 10 34 30" src="https://user-images.githubusercontent.com/39558132/70439785-87c8d780-1a6f-11ea-8ae4-cd210431cd44.png">

**interface attributes**
https://www.figma.com/file/GyRvSEQNS91DOLgMIk3u77/shop-desk?node-id=99%3A0

and

https://www.figma.com/file/X0ROabI93lbH0YsHDiwcFf/shop-mobile?node-id=1%3A1109

**Comment by zacck** [comment]
@JerryNyoike let's go for this one

**Comment by zacck** [comment]
@JerryNyoike please do let us know how this is going and if you need any help  ...

**Comment by JerryNyoike** [comment]
I replaced the select element with buttons and I am currently trying to make the buttons produce messages. The code compiles but when the buttons are clicked the filters are not produced. I can't seem to find where I am going wrong

**Comment by lucca65** [comment]
@JerryNyoike Please open a PR, so we can look at the code!
