### ISSUE TITLE
Create new main menu

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#105]
Create the new main menu that should work with the following rules:

- Must not appear in content add form interfaces (example: register offer, create community, etc.).

- When performed scrolldown the menu should exit to the right getting off screen;

- When the user scrolls or stays with the navigation stopped the menu should appear, appearing from right to left;

- The menu must always be above all content;

- Should be applied only in mobile resolutions (possibly from 1023px downwards);

**Visual design and how works**
https://www.figma.com/proto/eFQD2HiZokvTfKzidlSXQT/profile-Mobile?node-id=1%3A2538&viewport=587%2C658%2C0.25&scaling=min-zoom

**Interfaces attributes:**
https://www.figma.com/file/ZFYjG821WJpUFXlxV4dfnO/Navigation?node-id=53%3A1033

**Comment by JerryNyoike** [comment]
Can I take on this one?

**Comment by lucca65** [comment]
sure! @JerryNyoike

**Comment by zacck** [comment]
@JerryNyoike  be sure to let us know if you need a hand

**Comment by JerryNyoike** [comment]
Okay @lucca65 @zacck  I will let you know when I need a hand

**Comment by lucca65** [comment]
@heltonlr is this still relevant? do we have a new design for this?

**Comment by heltonlr** [comment]
Hi @lucca65, yes, some users with very small (320px width) screens need these improvements.

All design is in Figma.

**Comment by heltonlr** [comment]
Oh, Sorry @lucca65 
..no more, because we change the menu

**Comment by lucca65** [comment]
we can close this issue, maybe open another one with the new menu

**Comment by heltonlr** [comment]
Yes, I opened another about the new menu these days.
