### ISSUE TITLE
Can't scroll on buy shop form

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#106]
**Describe the bug**
Some smaller sized devices can't scroll to the "buy" button while trying to buy a new product

**To Reproduce**
1. Have a small mobile device
2. Go to the shop in any community env
3. Try to buy something in the shop
4. Make sure you are using a sale with units
5. Try to scroll down to click on "Buy"
6. See the error

**Expected behavior**
We should be able to buy it just fine, but the scroll keeps reseting

**Smartphone (please complete the following information):**
 - OS: Android Motoplaty G6
 - Browser Chrome

**Comment by RodrigoLeiteF** [comment]
I couldn't reproduce this bug on either Firefox, Chrome or my personal phone (Samsung S20) regardless of screen size. Can we double check that it still happens? Maybe it was fixed by one of our tailwind upgrades.

**Comment by lucca65** [comment]
+1 @RodrigoLeiteF looks like its not happening anymore!
