### ISSUE TITLE
Remove the "Ask" button

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#110]
After the MUDA pilot tests we realised that we should remove the chat feature for now as mentioned in the [IP 19](https://github.com/cambiatus/improvement-proposals/issues/19)

This button is inside a Shop sale, for example: https://app.cambiatus.io/shop/17

Just remove the button, pretty straightforward

**Comment by namoscagnm** [comment]
Hi, I will try to work on this issue on my free time.
Just to be sure I dont mislead you with wrong expectations, I am:
-Elm newbie
- Have a regular work and child
So it might take me some time to be productive.
Otherwise, I would like to be assigned to this. Thanks!

**Comment by zacck** [comment]
@namoscagnm  we appreciate your time and the help 🙏
