### ISSUE TITLE
Confusing number of notifications for a single sale

### ISSUE THREAD

**Issue by zacck** [cambiatus/frontend#114]
**Is your feature request related to a problem? Please describe.**
I am always a little confused when I see two notifications for one sale, One gets a notification for the transfer and a notification for buying items please see the screen grab below, You can see that I have a notification for transferring some money to Lucca and I have another one for buying a conch from Lucca, thing is they are from the same action 

![Screenshot 2019-12-16 at 15 16 05](https://user-images.githubusercontent.com/897731/70909835-fa5d2880-2016-11ea-834b-fb4b0e585a45.png)

**Describe the solution you'd like**
I am wondering if it's reasonable to combine both these notifications to one single one so that its clear they are related and doesn't bring up confusions 

**Describe alternatives you've considered**
N/A

**Additional context**
Some transfers are related to sales it would be beneficial to show the information as one unit of information

**Comment by lucca65** [comment]
Zacck this is true, there is a reason why we don’t group those, it has to do on how saletransfer work. 

I think this is a good issue for you to tackle because it involves smart contract and the event source, which maybe are the parts of the project your are the least familiar with!

What do you think? this may be a good issue to tackle before the recess

**Comment by zacck** [comment]
@lucca65  I can look at it but I am not sure I can finish it before recess,  I would say I have done the least work with them but I would love to think I am super familiar with their workings

**Comment by lucca65** [comment]
I don’t think it is urgent no problem if it takes long

**Comment by zacck** [comment]
Ok grabbing this one

**Comment by lucca65** [comment]
Closing this, we will follow the structure defined here: https://github.com/cambiatus/improvement-proposals/issues/36
