### ISSUE TITLE
Unable to approve a pending action

### ISSUE THREAD

**Issue by flaviagoma** [cambiatus/frontend#120]
**Describe the bug**
I've being unable to approve a pending action under the section "Activities for your analysis". First an error message showed up, saying I should try again later. Then, some days later I tried and after inserting the pin, the Enter button changed collor but nothing happened afterwards. Today, the error message was displayed again. 

**To Reproduce**
1. Go to 'dashboard'
2. Click on 'a pending action under the section "Activities for your analysis"
3. Click on 'approve'
4.Click on 'yes, approve'
4. Insert the pin
5. Click on 'enter'
6. See error

**Expected behavior**
The action should be approved and the coins should be generated 

**Screenshots**
![Screenshot_20191226-005103](https://user-images.githubusercontent.com/58967850/71486973-934e2980-27f7-11ea-8e99-b209b08d48cd.jpg)
![Screenshot_20191222-230221](https://user-images.githubusercontent.com/58967850/71486983-9cd79180-27f7-11ea-9045-f7bf4c668d84.jpg)

**Cambiatus Env you are using**
https://muda.cambiatus.io/community/MUDA/objective/2/action/2/claim/8/verification

**Smartphone (please complete the following information):**

Device: ASUS_X00HD
OS: Android 8.1.0
Browser Chrome
Version: 79.0.3945.79

**Additional context**
The issue showed up 3 days ago

**Comment by flaviagoma** [comment]
@lucca65 this is the bug I was talking about, have you seen this??

**Comment by lucca65** [comment]
this happened due to event-source being out of sync. Already solved!
