### ISSUE TITLE
Like and Dislike button doesn't function

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#128]
**Describe the bug**
When user clicks on Like or Dislike button, nothing happens.

**To Reproduce**
1. Go to 'Shop
2. Click on Like or Dislike button
3. See error

**Expected behavior**
When click, the counter must show the number of users that liked or disliked according click.

**Screenshots**

<img width="509" alt="Captura de Tela 2020-01-23 às 10 32 52" src="https://user-images.githubusercontent.com/39558132/72988816-c7ebdb80-3dcb-11ea-86d5-842ca722961c.png">

**Cambiatus Env you are using**
app.cambiatus.io

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: ???

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: ???
 - Browser: Chrome
 - Version: ???

**Additional context**
Examples: https://www.figma.com/file/GyRvSEQNS91DOLgMIk3u77/shop-desk?node-id=99%3A0

**Comment by lucca65** [comment]
@heltonlr does this is still valid? Looks like the new designs the like button don't exist

**Comment by heltonlr** [comment]
Correct, it is not a priority, We removed at the new design.
