### ISSUE TITLE
Update the Error/Success element

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#129]
**Is your feature request related to a problem? Please describe.**
We already have the new success/error element for interfaces,we must update. The current interfaces are with the old element.

**Describe the solution you'd like**
When this element appears, we see that it is the old (image)

<img width="1995" alt="Captura de Tela 2020-01-22 às 11 43 12" src="https://user-images.githubusercontent.com/39558132/72990121-5c573d80-3dce-11ea-9ac4-4ce78143d19e.png">

**Describe alternatives you've considered**
Update the element(image)

<img width="1345" alt="Captura de Tela 2020-01-23 às 10 50 44" src="https://user-images.githubusercontent.com/39558132/72990062-42b5f600-3dce-11ea-92f1-3e612ce5e22c.png">

**Additional context**

Figma element URL:
https://www.figma.com/file/oZJUIyHRmLyLIKDxYebvLg/Form-elements?node-id=7%3A296

**Comment by lucca65** [comment]
this was done during the #212 PR/issue
