### ISSUE TITLE
Some product images do not open on product list and details

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#130]
**Describe the bug**
Some product images do not open on product list and details.

**To Reproduce**
1. Go to 'Shop
2. Click on product details or on the list
3. See error

**Expected behavior**
The product images should appear

**Screenshots**

details
<img width="2048" alt="Captura de Tela 2020-01-23 às 11 19 26" src="https://user-images.githubusercontent.com/39558132/72992452-8448a000-3dd2-11ea-81e6-47c318945c08.png">

list
<img width="2029" alt="Captura de Tela 2020-01-23 às 11 19 14" src="https://user-images.githubusercontent.com/39558132/72992494-94607f80-3dd2-11ea-881b-80c3dfdf36e8.png">

**Cambiatus Env you are using**
app.cambiatus.io

**Desktop (please complete the following information):**

**Additional context**

Figma url:
https://www.figma.com/file/GyRvSEQNS91DOLgMIk3u77/shop-desk?node-id=99%3A0
https://www.figma.com/file/GyRvSEQNS91DOLgMIk3u77/shop-desk?node-id=99%3A3832

**Comment by zacck** [comment]
Seems like all products don' have images here, this seems to me like the ipfs server died will check

**Comment by RodrigoLeiteF** [comment]
Fixed by https://github.com/cambiatus/backend/pull/51
