### ISSUE TITLE
Some buttons do not grow along with the text size

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#131]
**Describe the bug**
Some buttons do not grow along with the text size

**To Reproduce**
1. Go to Shop
2. Click on My Offers tab
3. Click on Your offer

**Expected behavior**
Buttons size must grow along with the text size. The button must have a padding of at least 16px from the right and left

**Screenshots**
<img width="159" alt="Captura de Tela 2020-01-22 às 10 26 20" src="https://user-images.githubusercontent.com/39558132/72992868-38e2c180-3dd3-11ea-9f22-e45bdc652bc1.png">

**Cambiatus Env you are using**
app.cambiatus.io

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version ???

**Additional context**
Figma url:
https://www.figma.com/file/qyeWaokbgB7xSNSFMaceYZ/Buttons?node-id=0%3A1

**Comment by heltonlr** [comment]
Occurring to on mobile:

![Screenshot_2020-01-28-08-51-03-143_com android chrome](https://user-images.githubusercontent.com/39558132/73265935-aa948400-41b4-11ea-9231-f0fb9f7e72aa.jpg)

**Comment by lucca65** [comment]
@heltonlr can you send us an example of how the text size should be on the mobile and desktop?

**Comment by heltonlr** [comment]
Sure @lucca65, the text size is correct, but the padding is necessary:

![ButtonsBug](https://user-images.githubusercontent.com/39558132/73295898-51921380-41e7-11ea-95c0-75fb0ed4fdc7.png)
