### ISSUE TITLE
Confirmation modal before delete some product

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#132]
**Is your feature request related to a problem? Please describe.**
Users can accidentally delete a product

**Describe the solution you'd like**
Show the confirmation modal before delete

**Additional context**
Figma url(an example):
https://www.figma.com/file/cVmLXESyfs6Vb5EdrcEh8U/Profile?node-id=439%3A2803

**Comment by gui-gui** [comment]
I will try to fix this one

**Comment by heltonlr** [comment]
> I will try to fix this one

Thanks @gui-gui

**Comment by Zequez** [comment]
Well, I'll dive into it then :)

**Comment by Zequez** [comment]
<img width="898" alt="Captura de Tela 2020-03-31 às 01 20 09" src="https://user-images.githubusercontent.com/126037/77988612-2e710680-72f3-11ea-8984-b7310718d5cb.png">

Hi @heltonlr is this design and wording to your liking?

Also, if the use is not logged in, should the authentication modal show up BEFORE or AFTER the delete confirmation modal?

This is what I mean, I have it like this right now:

<img width="867" alt="Captura de Tela 2020-03-31 às 01 26 09" src="https://user-images.githubusercontent.com/126037/77988559-0aadc080-72f3-11ea-8a0a-4ad875636e8e.png">

Finally, what's the protocol with the translations? I did the English and Spanish ones, but I wouldn't risk writing the Portuguese and Catalan ones.

**Comment by heltonlr** [comment]
> <img alt="Captura de Tela 2020-03-31 às 01 20 09" width="898" src="https://user-images.githubusercontent.com/126037/77988612-2e710680-72f3-11ea-8984-b7310718d5cb.png">
> 
> Hi @heltonlr is this design and wording to your liking?
> 
> Also, if the use is not logged in, should the authentication modal show up BEFORE or AFTER the delete confirmation modal?
> 
> This is what I mean, I have it like this right now:
> 
> <img alt="Captura de Tela 2020-03-31 às 01 26 09" width="867" src="https://user-images.githubusercontent.com/126037/77988559-0aadc080-72f3-11ea-8a0a-4ad875636e8e.png">
> 
> Finally, what's the protocol with the translations? I did the English and Spanish ones, but I wouldn't risk writing the Portuguese and Catalan ones.

Hey @Zequez , the design is correct, thanks. The authentication modal must show up AFTER the delete confirmation modal. And about the translation, we should talk to @lucca65  to find out how it was done in this case.

**Comment by lucca65** [comment]
@Zequez hit me up on telegram, translations are pretty straight forward, you can look for examples in the whole project. the language files are json files under `public/` folder
