### ISSUE TITLE
Update input error (form)

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#134]
**Is your feature request related to a problem? Please describe.**
We have the new default for errors on inputs and we need update. The default error feedback is shown below the input, not above.

**Describe the solution you'd like**
Update the element

**Describe alternatives you've considered**
Update the element

**Additional context**

Example on the site (wrong):
<img width="1253" alt="Captura de Tela 2020-01-22 às 10 25 11" src="https://user-images.githubusercontent.com/39558132/73012108-67bd5f80-3df4-11ea-9279-17eaf8caa5dd.png">

New default correct:
<img width="1094" alt="Captura de Tela 2020-01-23 às 15 24 49" src="https://user-images.githubusercontent.com/39558132/73012186-8f142c80-3df4-11ea-9feb-817c5387024d.png">

Figma url (element):
https://www.figma.com/file/oZJUIyHRmLyLIKDxYebvLg/Form-elements?node-id=1%3A908

**Comment by heltonlr** [comment]
It is correct @victorgdev , but I did not find the "approve button"

**Comment by lucca65** [comment]
@victorgdev ping
