### ISSUE TITLE
The layout should not expand to the end on larger screens, the limit is 1280px.

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#135]
**Describe the bug**
The layout should not expand to the end on larger screens, the limit is 1280px. If we let it expand too much, the following cases (image) will occur where the content is far from other content, making it difficult to read and usability.

Shop example:
<img width="1976" alt="Captura de Tela 2020-01-22 às 10 15 13" src="https://user-images.githubusercontent.com/39558132/73014699-65a9cf80-3df9-11ea-89d3-95e401904af3.png">

Shop example (not centralized)
<img width="1435" alt="Captura de Tela 2020-01-22 às 10 10 37" src="https://user-images.githubusercontent.com/39558132/73014730-70646480-3df9-11ea-9296-8775fa0a6e80.png">

Other good example
<img width="1923" alt="Captura de Tela 2020-01-22 às 10 19 41" src="https://user-images.githubusercontent.com/39558132/73014745-7ce8bd00-3df9-11ea-9f7d-6d86a3b114ea.png">

**To Reproduce**
1. Go to Dashboard or Shop
2. See error

**Expected behavior**
The width of the content should end at 1280px, like the example shown below:

<img width="819" alt="Captura de Tela 2020-01-23 às 16 09 43" src="https://user-images.githubusercontent.com/39558132/73015437-cab1f500-3dfa-11ea-9e89-586a1f58b91d.png">

**Cambiatus Env you are using**
app.cambiatus.io

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version XXX

**Comment by zacck** [comment]
Consider setting a max size, for the `only-container` class
