### ISSUE TITLE
Wrong inputs margin (mobile) and wrong inputs width

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#136]
**Describe the bug**
The correct inputs margin is 40px, as show the image below (mobile) ans inputs should be 100%

**To Reproduce**
1. Go to 'Shop~
2. Click on Create an offer'
3. See error

**Expected behavior**
Correct margin: 40px
Correct width: 100% (respecting the margin)

**Screenshots**
![bug_form](https://user-images.githubusercontent.com/39558132/73264828-6b653380-41b2-11ea-8bdf-3583af2d3792.png)

**Cambiatus Env you are using**
app.cambiatus.io

**Smartphone (please complete the following information):**
 - Device: Xiaomi 6 Pro
 - OS: Android
 - Browser: Chrome
 - Version: ???

**Comment by lucca65** [comment]
I love this kind of report @heltonlr! Thanks a lot! this is the type of thing that will help us improve faster!

**Comment by heltonlr** [comment]
> I love this kind of report @heltonlr! Thanks a lot! this is the type of thing that will help us improve faster!

I will try register always with a visual example

**Comment by zacck** [comment]
> > I love this kind of report @heltonlr! Thanks a lot! this is the type of thing that will help us improve faster!
> 
> I will try register always with a visual example

Yes @heltonlr  this makes it so much easier
