### ISSUE TITLE
Input price shouldn't accept letters, only numbers

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#137]
**Describe the bug**
Input price is accepting letters

**To Reproduce**
1. Go to Shop
2. Click on 'Create an offer
3. Go to Price input
4. Type letters
5. See the error

**Expected behavior**
Only accept numbers

**Screenshots**
![inputNumber](https://user-images.githubusercontent.com/39558132/73265747-4e316480-41b4-11ea-86b3-f9ab83f16ce2.png)

**Cambiatus Env you are using**
app.cambiatus.io

**Comment by lucca65** [comment]
uuuhhh this will be troublesome, we tried to do that on the PIN form and kept having all sorts of troubles on Android (since there is so much difference in what numbers are in each device)

I recommend we show an error before submitting the form instead of just ignoring non number inputs

**Comment by heltonlr** [comment]
This solution already improves

![Screen Shot 2020-01-28 at 4 23 25 PM](https://user-images.githubusercontent.com/39558132/73297586-95d2e300-41ea-11ea-9ca6-9d53d7adb1b0.png)

Can we show the error before the click on the button? Immediately when the user types a letter or symbol?

**Comment by zacck** [comment]
@heltonlr  the issue here is some numbers have letters in them such as 

`1.8446744e+19` is actually  the value of `2 to the power of 64`  but perhaps we can find a way of validating this with every character
