### ISSUE TITLE
Change text in Communities - MEMBERS

### ISSUE THREAD

**Issue by natillasol** [cambiatus/frontend#140]
**Describe the bug**

When there is only 1 member in a community, it should read "1 member" (or "1 miembro" in ESP, and "1 membro" in POR)  instead of reading "1 members" (in plural). 

**To Reproduce**
1. Go to ' https://app.cambiatus.io/community

**Screenshots**
<img width="317" alt="Screen Shot 2020-01-28 at 09 15 56" src="https://user-images.githubusercontent.com/57719975/73276969-24297380-41af-11ea-9c3d-83ac706e6afb.png">

**Comment by lucca65** [comment]
@natillasol will close this one without a fix because we already have a new design on this screen that don't actually show member info, and the solution would take too much effort! Thanks for the report!
