### ISSUE TITLE
When click "Create" in Communities Page, there is no response

### ISSUE THREAD

**Issue by natillasol** [cambiatus/frontend#143]
**Describe the bug**
When creating a community, and click "Create" in Communities Page (all info has been provided), there is no response or message explaining the error. 

**To Reproduce**
1. Go to 'app.cambiatus.io/dashboard'
2. Click on 'communities'
3. Click on 'create communities'
4. Fill information
5. Click on 'create'
6. see error 

**Expected behavior**
No response

**Cambiatus Env you are using**
app.cambiatus.io/dashboard

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.1
 - Browser : Firefox
 - Version 70.0.1

**Comment by natillasol** [comment]
same happens for Safari 13.0.3 in the same OS

**Comment by lucca65** [comment]
Fixed! Thanks a lot for this @natillasol the solution was on the server, some variable got misconfigured by accident
