### ISSUE TITLE
Referrals 

### ISSUE THREAD

**Issue by natillasol** [cambiatus/frontend#144]
**Is your feature request related to a problem? Please describe.**

With one of the pilot projects (Coopeorganicos), one of the actions is getting people to join the platform and go to buy organic produce in the weekly farmers market. I remember in the past we had an invite option, which is no longer in the app.

**Describe the solution you'd like**

Have an option for inviting people to join Cambiatus either through a link or email. Make this be traceable in order to reward the inviter and the invitee.

**Comment by lucca65** [comment]
it does exists but the form to invite only appears for the account that created the community

**Comment by natillasol** [comment]
So in that case, the feature request will be to allow all members of the community to send invitations.

**Comment by lucca65** [comment]
we have to see how this goes because if there is a reward for invited users someone can just keep inviting people to get those rewards.

I think we have to think this through carefully, we didn’t made it admin only for no reason

**Comment by natillasol** [comment]
of course the system should not allow people to take advantage. Could it be possible for the admin to establish the maximum invites that any member can send?

**Comment by lucca65** [comment]
not in the current structure. There is rework of the invite feature that we have do to that will change how it works, instead of emails it will become just a shareable link

**Comment by lucca65** [comment]
So if you want to use the existing referral it does exists but it admin only! if you then want to allow anyone to invite it already have another issue.


https://github.com/cambiatus/backend/issues/26

I’ll close this issue as duplicate! please feel free to comment on that issue to get notifications on this feature advancement
