### ISSUE TITLE
Give a correct feedback when user tries to analyze a claim and other user already had analyzed.

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#147]
**Is your feature request related to a problem? Please describe.**
Currently the feedback is not clear

**Describe the solution you'd like**
Show a modal with the correct feedback, After user closes the modal, the Action card must be hide on the dashboard and your status must be change on the list.

**Describe alternatives you've considered**
Show in modal or in the interface (feedback default)

**Additional context**

When user clicks in "approve" or "approve", show the modal (image):
![Screen Shot 2020-02-06 at 11 43 03 AM](https://user-images.githubusercontent.com/39558132/73947211-dfe85280-48d5-11ea-949c-2850178497de.png)

"Approve"/"Repprove" interface (Dashboard):
https://www.figma.com/file/nEPG6Dkns8hDVCudVUTEzc/Dashboard?node-id=125%3A4706

Actions list:
https://www.figma.com/file/nEPG6Dkns8hDVCudVUTEzc/Dashboard?node-id=11%3A689

**Comment by lucca65** [comment]
after the new screens we wont display cases like this anymore. Closing
