### ISSUE TITLE
Not possible to delete a product on Shop

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#149]
**Describe the bug**
Not possible to delete a product on Shop after click on DELETE button.

**To Reproduce**
1. Go to Shop
2. Click on My Offers
3. Click on EDIT
4. Click on DELETE
5. See the bug

**Expected behavior**
Show the confirmation modal

**Screenshots**
![Screen Shot 2020-02-11 at 09 28 59](https://user-images.githubusercontent.com/39558132/74236879-0250e600-4cb1-11ea-8b0f-cbe7e8ecb0d0.png)

**Cambiatus Env you are using**
app.cambiatus.io

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version ???

**Additional context**
--

**Comment by felipeasf** [comment]
Hey @heltonlr , I think that this issue should be closed. The deletion of a product is working fine and the confirmation modal was fixed in this PR: https://github.com/cambiatus/frontend/pull/213.

**Comment by lucca65** [comment]
The confirmation modal exists but we are still laking contract and backend adjustments

**Comment by lucca65** [comment]
this was fixed! 👌
