### ISSUE TITLE
New sign In/create account interface and usability improvement

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#151]
With the new **sign In/create account** interface and **usability improvement** we will probably correct some difficulties that our pilots had when creating their accounts.

**All flows and interface rules on Figma**

_Create account:_
https://www.figma.com/file/vqHVOvugUksHKlhJvNfaFq/LoginCreateAccount-desk?node-id=1%3A259

_Sign In:_
https://www.figma.com/file/vqHVOvugUksHKlhJvNfaFq/LoginCreateAccount-desk?node-id=1%3A13100

_Default erros elements:_
https://www.figma.com/file/vqHVOvugUksHKlhJvNfaFq/LoginCreateAccount-desk?node-id=1%3A4539

_Responsive rules_
https://www.figma.com/file/vqHVOvugUksHKlhJvNfaFq/LoginCreateAccount-desk?node-id=82%3A79

**Comment by lucca65** [comment]
We have a new version for those pages here: https://www.figma.com/file/47BEsGEMSWfhTm3zC0ugyA/Main-flow?node-id=0%3A1

**Comment by amiskov** [comment]
As a part of this task the [new layout for PDF](https://www.figma.com/file/AUiVfZ8HbDQ4Qw22uP5OzU/pdf?node-id=81%3A0) with passphrase was also implemented.
