### ISSUE TITLE
New Shop interface and usability improvement

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#152]
With these improvements we want to:

- Give clear feedbacks about each important action of users;
- Apply new interfaces for creating and editing offers, improving usability
- Apply the full payment flow, improving usability
- Apply the complete evaluation flow of an offer
- Apply the new product details interface with the possibility of publishing more photos and video, improving usability
- Create pagination

**Main screen**
https://www.figma.com/file/GyRvSEQNS91DOLgMIk3u77/shop-desk?node-id=99%3A0

**Create new offer flow**
https://www.figma.com/file/GyRvSEQNS91DOLgMIk3u77/shop-desk?node-id=109%3A7539

**User evaluation flow**
https://www.figma.com/file/GyRvSEQNS91DOLgMIk3u77/shop-desk?node-id=333%3A350

**Edit and delete flow**
https://www.figma.com/file/GyRvSEQNS91DOLgMIk3u77/shop-desk?node-id=323%3A19936

**Offer details**
https://www.figma.com/file/GyRvSEQNS91DOLgMIk3u77/shop-desk?node-id=99%3A3832

**Purchase flow**
https://www.figma.com/file/GyRvSEQNS91DOLgMIk3u77/shop-desk?node-id=325%3A0

**Mobile main interfaces**
https://www.figma.com/file/GyRvSEQNS91DOLgMIk3u77/shop-desk?node-id=850%3A21893

**Comment by lucca65** [comment]
No longer valid
