### ISSUE TITLE
Cant update bio if it is too long

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#156]
**Describe the bug**
We get a 500 error when adding a bio with more than 255 characters

**To Reproduce**
1. Go to 'Profile'
2. Click on 'Edit'
3. Fill a bio with more than 255 characters

**Expected behavior**
Show an error related to the length, right now it is only "Something went wrong" 

**Cambiatus Env you are using**
Happens on all envs

**Comment by lucca65** [comment]
also it resets the form. this is not desirable

**Comment by lucca65** [comment]
The ideal solution would be have a counter on the textarea input and limit the number of characters when they reach the max length. 

We have an example of input with that counter in this design: https://www.figma.com/file/vqHVOvugUksHKlhJvNfaFq/LoginCreateAccount-desk?node-id=1%3A17378

**Comment by altjohndev** [comment]
Hi folks, I am available to solve this issue.

What is the procedure to contribute for this project?

Some questions:
- What is the definition of done?
- The development docker environment is "ready" as is? Do I need to perform more steps to prepare my local environment? (Such as: Build/start the backend, integrate with another services or projects)
- Finally, what about testing and code quality/coverage?

Best regards.

**Comment by lucca65** [comment]
thanks for your interest @altjohndev.

Here are the answers:

> What is the definition of done?

In this issue in particular is an approved pull request. That solves the problem described above.

> The development docker environment is "ready" as is? 

It is. We currently consist of several systems, the frontend is only one of them. You are able to run them all in `docker-compose` but the docker files for all the systems are in another repo. For this issue in particular you can only run the frontend, it will connect to our AWS dev env automatically after you run `yarn install` and `yarn start`. You can create an account normally through the system.

> Finally, what about testing and code quality/coverage?

We only have coverage and tests on the backend. Since Elm is a strict and strongly typed language, its type system gives us great confidence that stuff won't break. Not to say that it isn't necessary but we currently don't have them on the frontend.

**Comment by altjohndev** [comment]
Thank you for the reply!

I will start to solve the issue this Thursday (03/05, MM/DD), expecting to open a PR on Friday (04/05) with the solution.

**Comment by altjohndev** [comment]
PR created with additional info: #184
