### ISSUE TITLE
Wrong elements on the header

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#157]
**Describe the bug**
Wrong elements on the header:
- Background element
- Search input location
- Text font-size

**To Reproduce**
1. Go to 'Dashboard
2. See error

**Expected behavior**
The correct gray is #F8F8F8 and correct font-size is 10px

**Screenshots**

Wrong:
![Screen Shot 2020-02-12 at 20 19 44](https://user-images.githubusercontent.com/39558132/74386566-0ece5f00-4dd5-11ea-85a0-dc6812c03e0f.png)

Guidelines (correct):
![Screen Shot 2020-02-12 at 20 28 25](https://user-images.githubusercontent.com/39558132/74387046-52759880-4dd6-11ea-8c18-e8144b999c89.png)

**Cambiatus Env you are using**
app.cambiatus.io

**Comment by heltonlr** [comment]
After analysis, I suggest that the right margin of the bell is **44px** for the profile element (example):

![Screen Shot 2020-02-26 at 09 31 23](https://user-images.githubusercontent.com/39558132/75345265-239dfe80-587b-11ea-986a-b8eec6c03518.png)

**Comment by heltonlr** [comment]
And about the font-size: 10px on the "Profile name", It was not as readable as I imagined, let's use 11px, capital letters then.

**Comment by lucca65** [comment]
soon we will have to work on the search feature, and its a good opportunity to fix that
