### ISSUE TITLE
Invite feature

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#158]
With this feature we going to help on pilot's business model and going to bring more people to the communities.

**Main project**
https://www.figma.com/file/uDj0g2TculdYI8nfAI7avz/Invite?node-id=0%3A1

**Invite flow**
https://www.figma.com/file/uDj0g2TculdYI8nfAI7avz/Invite?node-id=1%3A703

**User with an account**
https://www.figma.com/file/uDj0g2TculdYI8nfAI7avz/Invite?node-id=1%3A1256

**User without an account**
https://www.figma.com/file/uDj0g2TculdYI8nfAI7avz/Invite?node-id=1%3A5098

**Invalid URL (user already be part)**
https://www.figma.com/file/uDj0g2TculdYI8nfAI7avz/Invite?node-id=1%3A16213

**Mobile main interface**
https://www.figma.com/file/uDj0g2TculdYI8nfAI7avz/Invite?node-id=1%3A17254

**Comment by heltonlr** [comment]
Hey @lucca65 , the Welcome screen simplified as we talked yesterday;

![Screen Shot 2020-02-26 at 09 51 59](https://user-images.githubusercontent.com/39558132/75347069-bf7d3980-587e-11ea-9aaf-c0d9792131a4.png)
 
And

The Invite button on the dashabord (the font-size on the buttons are wrong, take a look please);

![Screen Shot 2020-02-26 at 09 52 23](https://user-images.githubusercontent.com/39558132/75347093-cf951900-587e-11ea-8b72-3e4c702e9950.png)
 
More details on Figma:
https://www.figma.com/file/uDj0g2TculdYI8nfAI7avz/Invite?node-id=28%3A61

**Comment by lucca65** [comment]
This issue actually relates to the following tasks:

- [ ] Create new "create invite" modal on the dashboard
- [ ] create new screen "public community page" that will be public and allow for both netlink and sign up redirection
- [ ] change behaviour and params for the current register to accept the new invitation method
- [ ] change redirect behaviour of the current sign in page, to accept redirect to the new "public community page"

and if possible migrate some parts of the new register screen
