### ISSUE TITLE
Wrong "mark as complete" button

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#164]
**Describe the bug**
Wrong "mark as complete" button. The text inside button shouldn't break a line

**To Reproduce**
1. Click on 'Explore'
2. Click on 'Edit Action'
3. See error

**Expected behavior**
The text inside button shouldn't break a line

**Screenshots**

Wrong:
![Screen Shot 2020-02-17 at 10 47 29](https://user-images.githubusercontent.com/39558132/74659649-7b4db300-5173-11ea-9afa-3b29c0974153.png)

Correct:
![Screen Shot 2020-02-17 at 10 52 11](https://user-images.githubusercontent.com/39558132/74659693-90c2dd00-5173-11ea-92bd-506363a33ee4.png)

**Cambiatus Env you are using**
app.cambiatus.io

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome

**Smartphone (please complete the following information):**
 - Device: Xiaomi
 - Browser: Chrome

**Comment by felipeasf** [comment]
I'll dive into this one

**Comment by dev-danilosilva** [comment]
Hi everyone,

Is this issue over? Has @felipeasf dived into this one ?

**Comment by lucca65** [comment]
Sure go on @dev-danilosilva!

**Comment by dev-danilosilva** [comment]
According to my tests, the line only breaks when the viewport width is less than 186 px. All the viewport width greater than that, the button behaves as expected.

Do you think that its necessary to modify something in this button, once its very hard to find a narrower device viewport?

**Comment by lucca65** [comment]
you are right @dev-danilosilva we fixed it a while ago and the issue wasn't updated properly. Thanks for the investigation!
