### ISSUE TITLE
Wrong autocomplete design

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#165]
**Describe the bug**
Wrong autocomplete design, must be must be the same on figma

**To Reproduce**
1. Click on 'Explore'
2. Click on 'Create new action'
3. Use auto-complete (choose the verifiers input)

**Expected behavior**

Correct on Figma:
- Background;
- Same width of input;
- Full name first;
- Username (I liked this idea, you can add username below of full name);

![Screen Shot 2020-02-17 at 15 33 45](https://user-images.githubusercontent.com/39558132/74678840-f4143580-519a-11ea-9955-6524a7300629.png)

https://www.figma.com/file/nEPG6Dkns8hDVCudVUTEzc/Dashboard?node-id=122%3A1217

Wrong on HTML:

![Screen Shot 2020-02-17 at 15 31 07](https://user-images.githubusercontent.com/39558132/74678877-0e4e1380-519b-11ea-8b68-2e623e1c82e8.png)

**Cambiatus Env you are using**
app.cambiatus.io

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome

**Comment by lucca65** [comment]
@heltonlr what should we do with the account information? We have a lot of users without photo (since its not required) and with the same name. Why remove the account if it is the only unique identifier?

**Comment by heltonlr** [comment]
> @heltonlr what should we do with the account information? We have a lot of users without photo (since its not required) and with the same name. Why remove the account if it is the only unique identifier?

Hey @lucca65 . We will not remove it, just start with the Full name and below the username, this part is correct on HTML

**Comment by lucca65** [comment]
then can you provide an example that shows that information? the one you added to the issue have the account omitted

**Comment by lucca65** [comment]
you can edit the issue directly

**Comment by heltonlr** [comment]
Sure, adjusted on Figma:
https://www.figma.com/file/nEPG6Dkns8hDVCudVUTEzc/Dashboard?node-id=122%3A1217

![Screen Shot 2020-02-17 at 16 12 35](https://user-images.githubusercontent.com/39558132/74680757-5c194a80-51a0-11ea-84f3-accf78cd169f.png)

**Comment by marcjal** [comment]
@lucca65 I need to know some special symbol here I mean in Dashboard page or I have to get some privileges to see this part

- Click on 'Explore'
- Click on 'Create new action'
- Use auto-complete (choose the verifiers input)
- See error

Adjunct an image
![Captura de Tela 2021-02-02 às 00 03 54](https://user-images.githubusercontent.com/9432058/106546529-2a50df00-64ea-11eb-93d1-0fb95b2ef0f3.png)

**Comment by lucca65** [comment]
you can just click on transfer, it will have the same selector

**Comment by marcjal** [comment]
@lucca65  I need some sugestion because I can't find the correct way to do this part. I have this

![Captura de Tela 2021-02-02 às 18 34 20](https://user-images.githubusercontent.com/9432058/106665936-b19f6080-6585-11eb-8c3e-615fffa9d471.png)
![Captura de Tela 2021-02-02 às 18 34 34](https://user-images.githubusercontent.com/9432058/106665942-b3692400-6585-11eb-8d49-84b352c97009.png)
![Captura de Tela 2021-02-02 às 18 35 32](https://user-images.githubusercontent.com/9432058/106665944-b401ba80-6585-11eb-9067-43b37700a943.png)
![Captura de Tela 2021-02-02 às 18 36 05](https://user-images.githubusercontent.com/9432058/106665947-b49a5100-6585-11eb-9893-8b17b6ab7300.png)

**Comment by marcjal** [comment]
You can see the border-dotted class in function viewAutoCompleteItem, I'm trying to find the correct place where Profile.selectConfig is called because I have  to see how can I treat my member list to verify for the last and try to not add that class for the last item

**Comment by marcjal** [comment]
Hehe I was trying to avoid some nested css but I made one that  I think is OK. I'm going to send my PR for review
