### ISSUE TITLE
Wrong delete element

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#167]
**Describe the bug**
Wrong delete element,

Wrong:
![Screen Shot 2020-02-17 at 15 46 47](https://user-images.githubusercontent.com/39558132/74679551-efe91780-519c-11ea-81de-ff2098c4dbbf.png)

Correct:
- Background on name;
- Trash icon;

![Screen Shot 2020-02-17 at 15 47 01](https://user-images.githubusercontent.com/39558132/74679559-f6778f00-519c-11ea-80d9-051fc65224b6.png)

**To Reproduce**
1. Click on explore
2. Click on create action
3. Add a verifier

**Cambiatus Env you are using**
app.cambiatus.io

**Comment by RodrigoLeiteF** [comment]
@heltonlr Do we have the new element on Figma? I achieved an approximation, but I'd like to know the exact values for font size, padding and border. Also, the trash can icon doesn't seem to be in the project so I'd need it's SVG values as well if possible.

![image](https://user-images.githubusercontent.com/16887983/76635474-4b9d8b00-6526-11ea-94dc-02d0b11a0648.png)
