### ISSUE TITLE
The buttons on actions and objectives must be disable when marked as complete

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#168]
## Description
Add archive objective button. 

Archived objectives must not allow actions to be edited, making the edit button disabled.

This form is only visible on an admin page:

1. Create a new community on the path `/community/new`, after its done, reload the app
2. After its created, click the cog on the top right part of the page (make sure you've selected the new community on the selector, top left of the screen)
3. Go to Objectives and actions, place where you can create objectives and their actions
4. Create test objectives and actions
5. Implement the archive button

## How to implement

We have a GraphQL mutation to implement this, please use staging GraphQL interface: https://staging.cambiatus.io/api/graphiql

```graphql
mutation {
  completeObjective(input: {objectiveId: 1}) {
    isCompleted
    community {name}
  }
}
```

After the archiving is done, we need to properly disable the buttons, and follow the updated designs, that can be seem below

## Designs
The buttons on actions and objectives must be disable when marked as complete, so that users can not edit (image below)

![Screen Shot 2020-02-17 at 15 54 56](https://user-images.githubusercontent.com/39558132/74679924-edd38880-519d-11ea-9b2a-b83788eeca7c.png)

ON HTML (Even complete the button is enabled):
![Screen Shot 2020-02-17 at 15 57 30](https://user-images.githubusercontent.com/39558132/74680041-4b67d500-519e-11ea-83bb-cf1bd2c7684d.png)

**Cambiatus Env you are using**
app.cambiatus.io

**Comment by Trunkol** [comment]
I got it, let me try!

**Comment by lucca65** [comment]
@marcjal this one is way more challenging, please take a look to see if it makes sense to you, If the description is not good enough let me know

**Comment by lucca65** [comment]
you can always get examples from other pages with mutations, maybe `Features.elm` can provide a good example on how to do it

**Comment by marcjal** [comment]
Sounds good! Let me familiarize myself with that Features.elm to get a more overview of the task and whatever doubt I let you know

**Comment by marcjal** [comment]
@lucca65 I have this
![Captura de Tela 2021-02-04 às 22 41 33](https://user-images.githubusercontent.com/9432058/106978038-3337ef80-673a-11eb-995c-c757f1d1307a.png)


I already created an objective but I don’t know how to create an action, the url is expecting something like this 'http://localhost:3000/community/0,ELMO/objectives/{id_number}/action/new'

I'm trying to replicate this part to later implement the disable button

**Comment by lucca65** [comment]
@marcjal please go to the cog (on the dashboard) > Objetives and Action > and from there explore that page

**Comment by lucca65** [comment]
btw i loved the name of the community

**Comment by marcjal** [comment]
@lucca65 I got it so I have a doubt this task is to disable the edit button when the action is completed, so what about this archive button this is not part of this task, right?

**Comment by lucca65** [comment]
they are the same, i figure since both are simple enough, it's possible to do a combo here

**Comment by marcjal** [comment]
Sounds good! Let me recap to get the task in the correct way so for the archive button I have to implement this mutation to update my actual data and show the archived status in the button, the archive button is to be close to edit button?, later if the task is completed don’t let the user edit that action and finally put the status and disable button in this part near to the down arrow (see image below) @lucca65 

```
mutation {
  completeObjective(input: {objectiveId: 1}) {
    isCompleted
    community {name}
  }
}
```
![Captura de Tela 2021-02-05 às 00 32 11](https://user-images.githubusercontent.com/9432058/106986224-b14fc280-6749-11eb-96ff-9022f7f348da.png)

**Comment by lucca65** [comment]
yeah, in the edit objective page (`/community/{id}/objectives/{objective_id}/edit`) you'll have to add a button called "archive objective" calling that mutation. After that's done, you'll have to implement the designs on the print, checking if the objective is completed and displaying the tag and disabling the buttons

**Comment by lucca65** [comment]
Here are the designs to add the archive (or marked as complete) button:

![74680409-4d7e6380-519f-11ea-8f05-8ad8da3cda5b](https://user-images.githubusercontent.com/1082127/107151346-e3774500-6940-11eb-83a4-5ab7a4c577c0.png)

**Comment by marcjal** [comment]
Thnks! It's going to be a good feature

**Comment by marcjal** [comment]
Still working on the task I hope to finish it by friday

**Comment by lucca65** [comment]
thanks for the ping @marcjal

**Comment by marcjal** [comment]
Hi @lucca65 I need some information to try to understand my mutation I have this for the configuration

![Captura de Tela 2021-02-10 às 20 32 33](https://user-images.githubusercontent.com/9432058/107586768-5b629b00-6bdf-11eb-8d64-507ea613f568.png)
![Captura de Tela 2021-02-10 às 20 32 55](https://user-images.githubusercontent.com/9432058/107586774-5d2c5e80-6bdf-11eb-97a4-cde3bb686743.png)
![Captura de Tela 2021-02-10 às 20 33 25](https://user-images.githubusercontent.com/9432058/107586779-5dc4f500-6bdf-11eb-92a5-a283b0588ee6.png)

**Comment by marcjal** [comment]
And this error
![Captura de Tela 2021-02-10 às 20 35 51](https://user-images.githubusercontent.com/9432058/107586912-9c5aaf80-6bdf-11eb-860f-02aa2da6a7d9.png)

**Comment by marcjal** [comment]
I don't know why the arguments are Mybe () so this () is a Unit

**Comment by lucca65** [comment]
I figure this error appeared suddenly for you right? This may be due to your branch not being updated with `master`. We deployed a new version on the backend and the frontend must follow it (PR #480). Update your branch with master and it should be good! 👍

**Comment by lucca65** [comment]
if that's not the case, please open a draft PR so its easier for us to grasp your context. Looks like you are having trouble with GraphQL auto generated types... its common, takes a while until you are used to how they work, open the PR and we can give you more specific directions!

**Comment by marcjal** [comment]
> I figure this error appeared suddenly for you right? This may be due to your branch not being updated with `master`. We deployed a new version on the backend and the frontend must follow it (PR #480). Update your branch with master and it should be good! 👍

:( I think that it's my types in the construction of my mutation function maybe I missed something I'm going to send my PR to get that help hehe

**Comment by marcjal** [comment]
@lucca65 I opened the PR
