### ISSUE TITLE
Should be the "marked as complete" button also on objective edit

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#169]
**Describe the bug**
Must be possible to the user mark a objective as complete, but we do not have this button on edit screen of Objective

**To Reproduce**
1. Go to 'Edit Objective' screen
2. See error

**Expected behavior**

"Mark as complete" button on edit objective screen (When an objective is marked as complete, all of its actions must change to "Complete" status, no longer allowing "Claims" or "Edit"):
![Screen Shot 2020-02-17 at 16 05 14](https://user-images.githubusercontent.com/39558132/74680409-4d7e6380-519f-11ea-8f05-8ad8da3cda5b.png)

**Cambiatus Env you are using**
app.cambiatus.io

**Comment by lucca65** [comment]
it will be addressed on #168
