### ISSUE TITLE
Form content without max-width

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#170]
**Describe the bug**
Form content without max-width, must be centralised.
![erro2](https://user-images.githubusercontent.com/39558132/74681100-48baaf00-51a1-11ea-8fb4-84bef0a6e339.png)

**To Reproduce**
1. Go to explore
2. Click on Create Objective
3. See error

**Expected behavior**
Centralized content

**Cambiatus Env you are using**
app.cambiatus.io

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome

**Comment by lucca65** [comment]
how should the blue bar behave? just add two white bars on each side or just centralize the content? (back button and title)

**Comment by heltonlr** [comment]
> how should the blue bar behave? just add two white bars on each side or just centralize the content? (back button and title)

The purple bar remains 100% (background) but the content must be limited to the width of the container:

![Screen Shot 2020-02-18 at 11 03 00](https://user-images.githubusercontent.com/39558132/74742922-44909f00-523e-11ea-89c0-689c66dc1f4e.png)
