### ISSUE TITLE
Slide (horizontal slide) was not created (mobile only)

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#172]
**Describe the bug**
Slide (horizontal slide) was not created (mobile only)

Correct on Figma:
![Screen Shot 2020-02-18 at 11 26 39](https://user-images.githubusercontent.com/39558132/74744863-b74f4980-5241-11ea-98b8-a98fb6c5df14.png)

**To Reproduce**
1. Click on Explore
2. Click on Edit
3. Click on Arrow down
4. See error (mobile only)

**Expected behavior**
The actions must be in swipe (horizontal navigation), not in vertical navigation

**Cambiatus Env you are using**
app.cambiatus.io

**Smartphone (please complete the following information):**
 - Device: Xiaomi Red 6
 - OS: Android
 - Browser: Chrome

**Additional context**
Figma:
https://www.figma.com/file/nEPG6Dkns8hDVCudVUTEzc/Dashboard?node-id=153%3A2503

**Comment by lucca65** [comment]
This page changed a lot, and we will fix this on #670
