### ISSUE TITLE
Move Edit Objective button to the top

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#174]
**Is your feature request related to a problem? Please describe.**
Move **Edit Objective** button to the top next to **Create action** button when the accordion is opened. Nowadays it is far below after opening of the accordion, getting long from the name of the Objective.

Improvement on figma:
![Screen Shot 2020-02-18 at 11 46 42](https://user-images.githubusercontent.com/39558132/74746590-70168800-5244-11ea-89df-306fa84300ea.png)

**Describe the solution you'd like**
Move **Edit Objective** button to the top next to **Create action** button when the accordion is opened

**Additional context**
Figma details:
https://www.figma.com/file/nEPG6Dkns8hDVCudVUTEzc/Dashboard?node-id=153%3A2503

**Comment by jxxcarlson** [comment]
It took me a while to realize that the "v" to the right of "Edit" is how how you create a new action. I think it would be better to simply have a "New Action" button there.  The more that is exposed so that the user has a complete picture of the context, the better.

<img width="1097" alt="Screen Shot 2020-02-25 at 13 12 06" src="https://user-images.githubusercontent.com/679991/75246708-a1590000-57d0-11ea-915f-b44eff3ab8f2.png">

**Comment by heltonlr** [comment]
Thanks for your feedback @jxxcarlson . The "v" (arrow) opens the element, and the "create action" button is inside the element. We can add this improvement and bring it to a button in the next version of the interface when we start creating the dashboard.

**Comment by lucca65** [comment]
@heltonlr the Figma link is no longer available, can you send a new one, please?

**Comment by heltonlr** [comment]
> @heltonlr the Figma link is no longer available, can you send a new one, please?

Hum, there isn't this interface on Figma anymore. When I 've updated the new layout, I deleted this interface. But we need to move this button to the top. Can someone send me the print screen? Then I indicate the right place

**Comment by heltonlr** [comment]
i found it @lucca65;

This edit button:

![bug](https://user-images.githubusercontent.com/39558132/85880433-67196280-b7b2-11ea-875a-bc928677b572.jpg)

When the card opens, the edit button must be under the "Create new action":

![bug2](https://user-images.githubusercontent.com/39558132/85880653-bfe8fb00-b7b2-11ea-909e-5507e6f2792b.jpg)
