### ISSUE TITLE
Mobile interface without side margins and incorrect buttons

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#203]
Mobile interface without side margins and incorrect buttons, image below:

![inviteError02](https://user-images.githubusercontent.com/39558132/77323541-30840580-6cf4-11ea-8807-c6c8c0fef6d0.png)

**To Reproduce**
1. Open an invite url on mobile

**Expected behavior**
Image below:

![errorInvitecorrect02](https://user-images.githubusercontent.com/39558132/77324905-3549b900-6cf6-11ea-9e8a-e9e2a4b7dbf9.png)

**Cambiatus Env you are using**
app.cambiatus.io

**Smartphone (please complete the following information):**
 - Device: Xiaomi Note 6 pro
 - OS: Android
 - Browser: Chrome

**Comment by lucca65** [comment]
this was completed on #186
