### ISSUE TITLE
Some date time information is shown incorrectly

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#204]
**Describe the bug**
Date time is shown incorrectly in actions/claims/verifications. On our versions we only show date (not time), so it was difficult to notice. 

When trying to reproduce this error please take into consideration that our server is in UTC, it will depend on the time of the day you are, the time when the claim was opened, your timezone, etc.

**To Reproduce**

*Note*: I'm assuming the following scenario:
Server timezone: UTC
My computer timezone: GMT-3 (no daylight saving time)
Claim opened 22:00 GMT-3

1. Create similar or equivalent scenario as the one mentioned above
2. Open a claim for an action with at least one account you access as validator
3. Open the validator screen (the one you, as a validator, vote)
4. See error, the date will be displayed as the claim opened in the next day

**Expected behavior**
Show the real date the claim was opened

**Screenshots**
I wasn't able to get any screen 

**Cambiatus Env you are using**
Muda (muda.cambiatus.io)

**Comment by zacck** [comment]
@lucca65  could you please describe this in detail? and give an example of where this is broken plus how to fix?

**Comment by lucca65** [comment]
Thanks for the comment Zacck, I wrote this down during a meeting with MUDA and completely forgot to provide a proper description!

**Comment by zacck** [comment]
No worries Lucca, always easier to fix when you see what is broken

**Comment by NeoVier** [comment]
Update: This was caused because we were hardcoding `Time.utc` when showing date strings. #587 fixes this by storing a `Time.Zone` on the `Shared` model. `Time.utc` is the only way to create a `Time.Zone` (apart from a `customZone`) without using `Time.here`. We can prevent silly us to use it again in the future with NeoVier/elm-review-no-function-outside-of-modules (apparently that's a pretty good rule to have :sweat_smile: )

**Comment by lucca65** [comment]
damnnn, this issue was so old it was already with grandkids on college... amazing that the app is now even more protected 🛡️
