### ISSUE TITLE
CI is broken when merging into master

### ISSUE THREAD

**Issue by zacck** [cambiatus/frontend#205]
**Describe the bug**
Some actions in the continuous integration set up do not succeed when a PR is merged into master. Why this is due to some missing data in the application. I expect some docker logins so the applications
can actually build and move past that stage

**To Reproduce**

Merge an approved PR into Master

**Expected behavior**
It should build and publish a docker image of the build 

**Screenshots**
N/A

**Cambiatus Env you are using**
N/A 

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Automation

**Comment by lucca65** [comment]
@zacck I think I can help with this, please create a new docker hub user for our CI (maybe Cambiatus-ci) and share access details with me. We still don't have a way to safely share team passwords so I'll be handling those for now. 

After that I can add the CI user as one of the collaborators of our docker hub account

**Comment by zacck** [comment]
@lucca65  first thing tomorrow I'm on this
