### ISSUE TITLE
Create community configuration

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#235]
We need to create a new screen on the community that allows community administrators to change some params. The Figma design is here: https://www.figma.com/file/nEPG6Dkns8hDVCudVUTEzc/Dashboard?node-id=1046%3A22

Its important to make this screen accessible only by community admins. You can check the community creator, that is the admin account. Make sure to hide the link from the community page as well as to block users that directly use the URL

The url should be `/community/BES/settings`. This page should follow this design: https://www.figma.com/file/nEPG6Dkns8hDVCudVUTEzc/Dashboard?node-id=586%3A1129

You'll also have to remove the "Objectives and Actions" panel, away from the community page: 
<img width="1347" alt="Screen Shot 2020-05-03 at 13 08 06" src="https://user-images.githubusercontent.com/1082127/80919200-26b3e000-8d3f-11ea-8d26-cfd87c34c8c9.png">

The final part would be to create a `/community/BES/settings/features` page with only the toggles.

**Comment by lucca65** [comment]
Please refrain from doing mutations for now, only load the database stuff and allow for toggles, but don't do the submit process just yet

**Comment by RodrigoLeiteF** [comment]
> Please refrain from doing mutations for now, only load the database stuff and allow for toggles, but don't do the submit process just yet

Gotcha :)
