### ISSUE TITLE
Add user quotes to the login/registration screen

### ISSUE THREAD

**Issue by amiskov** [cambiatus/frontend#238]
**Is your feature request related to a problem? Please describe.**
[Desktop layouts](https://www.figma.com/file/47BEsGEMSWfhTm3zC0ugyA/Main-flow?node-id=0%3A1) for login/registration pages have users quote on it. We already have styles and markup implemented in #151 but still have to collect the actual quotes.

**Describe the solution you'd like**
In `Session/Guest.elm` use already implemented `viewQuete` function inside `viewLeftCol` to show user quotes with actual data.

**Comment by lucca65** [comment]
After talking to @heltonlr I'm closing this as we are not doing it anymore
