### ISSUE TITLE
Create account and Sign in improvements

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#245]
After the usability test, we must change some changes on the Registration and Sign in flow to improve the user experience:

1. The pdf file must download in the background without showing to the user. In iOS the pdf file must be open in another tab but do not be shown.

**This item was removed from the task:**
> 2. In the dashboard, we must show the tip on the header. When the user clicks, he must be redirected to another page that shows complete information (figma). After that, this tip should never appear again.
> 
> Figma screen (a tip on the header):
> https://www.figma.com/file/47BEsGEMSWfhTm3zC0ugyA/Main-flow?node-id=556%3A13
> 
> Figma screen (tip details):
> https://www.figma.com/file/47BEsGEMSWfhTm3zC0ugyA/Main-flow?node-id=556%3A381

3. Change the text on Basic informations step:

- Button text: "Continue"

Figma screen:
https://www.figma.com/file/47BEsGEMSWfhTm3zC0ugyA/Main-flow?node-id=3%3A2206

4. Change the text on 12 words step:

- "Copy and paste the 12 words below in a secure place. You have only this chance to do it; if you lost these words, you can't login into your account never more."

- Button text: "Create my account"

Figma screen:
https://www.figma.com/file/47BEsGEMSWfhTm3zC0ugyA/Main-flow?node-id=3%3A2224

5. Change the text on Login (12 words form):

- "Enter your 12 words, that you've copied and pasted on registration."

- Add a placeholder on 12 words input: "Type your 12 words here"

Figma screen:
https://www.figma.com/file/47BEsGEMSWfhTm3zC0ugyA/Main-flow?node-id=3%3A2590

**Comment by heltonlr** [comment]
Hey @amiskov , There is time to make some changes to this task?

**Comment by amiskov** [comment]
> Hey @amiskov, Is there time to make some changes to this task?

Hi, @heltonlr! Now I'm working on the Profile redesign issue (#258) and to be honest we didn't plan to work on Sign In improvements very soon... 😬

I think I'll finish with the Profile redesign by the end of this week and then I could work on it these improvements. As for me, I think it would be reasonable to do so. @lucca65 how do you think? We had Reg/Sign-in improvements back in [Biweekly 18/may~29/may](https://github.com/orgs/cambiatus/projects/16#card-38888602) but then, as far as I remember, I switched to the Payment History page and this task was put on hold...

**Comment by heltonlr** [comment]
Don't worry @amiskov, you can continue with your prioritization. I asked only to know if there is time for some adjust 👊

**Comment by lucca65** [comment]
there is time to adjust stuff @heltonlr! Go ahead! 💪

**Comment by amiskov** [comment]
> Is there time to make some changes to this task?

Now I see that I've understood the meaning of this question incorrectly 🤦‍♂️ @heltonlr @lucca65, sorry about that 😊

**Comment by amiskov** [comment]
It also would be handy to add autofocus to the Passphrase textarea and PIN input on the Register and Login screens. Something like this:

```elm
-- ...
|> UR.addCmd
  (Dom.focus "pinInput"
       |> Task.attempt (\_ -> Ignored)
   )
```

**Comment by lucca65** [comment]
+1 @amiskov

**Comment by heltonlr** [comment]
I decided to remove item 2 from the task. We can use the Welcome email instead to inform about the 12 words and the possibilities to download again.

**Comment by amiskov** [comment]
> The pdf file must download in the background without showing to the user. In iOS the pdf file must be open in another tab but do not be shown.

@heltonlr Helton, I'm afraid we can't open PDF in the new tab without showing it to the user... We can't control that for this PDF. I made it to be opened in a new tab on mobile devices but it opens like usual new tab, not in the background.

You can check it [here](https://deploy-preview-317--eager-jepsen-ee4ac5.netlify.app/) (use your phone, desktop browsers work as they were). Please, let me know if we can use it this way.

**Comment by heltonlr** [comment]
Hey @amiskov 

On **Android** was correct (MUDA's example), the pdf is downloaded and the user is directed to the login screen. I would like the same to happen on the iPhone. Showing the pdf's tab is bad for our users who don't know how to return to the login's tab.

If it is not possible on iPhone, let's keep it as is.

**Comment by amiskov** [comment]
> If it is not possible on iPhone, let's keep it as is.

After some research, I realized that it's not possible to download PDF in the background in iOS :( We can only open a new tab with PDF. So I leave it as it is for now.

**Comment by heltonlr** [comment]
Ok @amiskov , at least on Android, we can redirect the users to log in screen. Thanks for research
