### ISSUE TITLE
Show real-time informations

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#249]
In many moments the users need to refresh the browser to see important information about your journey.

**Example:** 

- [ ] Users don't see the "community change element" on the header. Only after the browser's refresh.
- [ ] Users don't see your new balance after that made an action.
- [ ] The SHOP item (in the menu) should disappear as soon as it is disabled.
- [ ] The actions for analysis and the actions highlighted in the dashboard should disappear as soon as disabled.

These and other information are important and must show in real-time to the users.

**Comment by lucca65** [comment]
@heltonlr there are all the scenarios? In tasks like this we should list all the possible cases where we need auto reload, as this is the only way of knowing that we implemented all cases. 

If there is more to them, can you please list it?

**Comment by heltonlr** [comment]
Sure @lucca65 , I will check it

**Comment by heltonlr** [comment]
Hey @lucca65, I analysed the interfaces and these two are the most important to fix now, for now. We must prioritize if possible.

**Comment by heltonlr** [comment]
I added two more items to this task that did not exist when it was created.

**Comment by lucca65** [comment]
ok @heltonlr. This is pretty hard to do because it requires several updates on the backend as well. We will tackle this one eventually!

**Comment by lucca65** [comment]
closing this for now. A lot has progressed. We still don't have socket updates for a true live app, but all the points on the issue were solved
