### ISSUE TITLE
Webpack fails to invalidate cache

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#252]
**Describe the bug**
Sometimes during our builds, web pack fails to invalidate the cache and we get a blank screen when trying to access the app. You should see a similar error as the print attached

**To Reproduce**

It depends on the cache state of your browser, so its difficult to simulate, as it will depend on the browser's behaviour.
1. Go to the app
2. If it appears as blank, you should see the error
3. If not, just try building new versions until your browser shows the error

**Expected behavior**
The app should just load. Instead we have to force a reload somehow. Used ways are to do a full reload (`ctrl`+`f5` on windows, `cmd`+`r` on Mac), or force a URL change (by adding something after the root url, such as `/dashboard`)

**Screenshots**
<img width="2760" alt="Screen Shot 2020-05-18 at 17 08 21" src="https://user-images.githubusercontent.com/1082127/82255465-126d0700-992b-11ea-9621-41f52dbb8a47.png">

**Cambiatus Env you are using**
It happens on all envs, but you must have accessed it from your browser before, so you have some kind of cache

**Comment by lucca65** [comment]
duplicate of #45

**Comment by amiskov** [comment]
There is some progress on this bug.

How to achieve this behavior on your `localhost`:

1. Run `yarn build`.
1. Run some local server from the `./build` directory (I used [this one](https://github.com/lwsjs/local-web-server#single-page-application) with `--spa` option). Make sure you are serving it via `localhost` or `127.0.0.1` to have Service Worker enabled (it works only with HTTPS or on `localhost`).
1. Open the browser, make sure it works.
1. Then, remove `./build` directory.
1. Make some changes in the code or better change `[chunkhash]` manually in `config/webpack.config.prod.js:46,47`.
1. Run `yarn build` again and try to access the `/` page in the browser. There should be a blank page and an error in the console.

![Screenshot 2020-06-23 at 14 10 50](https://user-images.githubusercontent.com/140053/85407284-b28dff80-b56b-11ea-83dc-a1e18e329093.png)

The cause of this error is a cached version of the `/` page with old paths to JS files. This cache is made in `public/service-worker.js:3`.

**Comment by lucca65** [comment]
wow! Thanks for the report @amiskov! Now we have a way to simulate it and work with it
