### ISSUE TITLE
Add page titles for better navigation

### ISSUE THREAD

**Issue by amiskov** [cambiatus/frontend#254]
**Is your feature request related to a problem? Please describe.**
All pages have the same title:
![cambiatus_page_titles](https://user-images.githubusercontent.com/140053/82482046-e98d7300-9ade-11ea-92ba-1a1c82eee34f.png)

It's better to have a meaningful title for each page to be able to navigate via browser history.

**Describe the solution you'd like**
Change page titles along with URI during the routing.

**Describe alternatives you've considered**

**Additional context**

**Comment by lucca65** [comment]
+1 It would help a lot!

**Comment by lucca65** [comment]
Lets just make sure its localised
