### ISSUE TITLE
The copy feature doesn't work during a user invite

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#264]
The copy feature doesn't work during a user's invites. Neither the button, neither when the user selects and copy manually.

1. Go to 'Dashboard'
2. Click on 'Invite link'
3. Try to copy the URL by button and manually

**Cambiatus Env you are using**
app.cambiatus.io

**Smartphone (please complete the following information):**
Android 9, Xiaomi Mi A1, Firefox

**Comment by amiskov** [comment]
This will be fixed in #305 PR by the b7129ec commit. @lucca65 the cause of this was just `disabled` property for the `input` which doesn't allow to copy the content. Solved by creating separate `input` of type `text` without `disabled` property, just like it has been done in the Registration.

**Comment by lucca65** [comment]
awesome @amiskov! in apple devices it seems to work fine, interesting how different vendors behave differently
