### ISSUE TITLE
Node.js version is too specific

### ISSUE THREAD

**Issue by RodrigoLeiteF** [cambiatus/frontend#285]
On package.json we specify our Node.js version to be `12.0.0`. This isn't a problem necessarily, but specifying the minor version if likely unnecessary for our use case and it means other minor Node.js versions won't work. I've been running the project with Node.js `12.0.17` with no problems, so I think it's safe to specify our version to just `12`.

**Comment by lucca65** [comment]
we had problems before by letting the version too generic. Actually this is good advice when having to handle production builds. It’s best to not run the latest version and have peace of mind than having a surprise when deploying.

no problem to upgrade the version, but on production projects try to keep your package and stack version fixed

after all what do we gain by generalizing? Using the latest version don’t necessarily means more security nor best performance. In some cases node upgrades even introduce bugs (sadly they don’t have the best history when it comes to consistency with security and performance)

No problem to upgrade the version or using a different one on your local machine, both are valid and fine. But generalizing ok production is a bad idea

God I feel old

**Comment by lucca65** [comment]
and actually this issue makes a lot of sense coming from an arch user, always on the bleeding edge of package versions 🤣

**Comment by RodrigoLeiteF** [comment]
I agree with keeping production version specific, but aren't we already doing that on our Dockerfile? Specifying it on the package.json doesn't really do anything in practice, as all it does is prevent yarn from running the project. NPM doesn't seem to care at all.

**Comment by RodrigoLeiteF** [comment]
Another thing to note is that Node.js uses semantic versioning. Minor releases only add new functionality on a backwards compatible manner, so fundamentally the difference between 12.0 and 12.17 for example is negligible, as anything that could break  compatibility would be a new major release (13 in this case).

**Comment by lucca65** [comment]
If you use `n` for handling node versions, it automatically switches the version based on the package.json if that’s why we are doing this change 

The last time we had problems was a minor update, not major. It caused compatibility problems with some ssl related binaries.

Again no problem in doing the upgrade on our projects, but keep the development version compatible with production.

in your machine as you said it doesn’t cause problems

**Comment by RodrigoLeiteF** [comment]
Wow, that's weird. Fair enough though, we can leave it as is :)
