### ISSUE TITLE
Some PDF viewers don't copy the passphrase properly

### ISSUE THREAD

**Issue by amiskov** [cambiatus/frontend#289]
**Describe the bug**
Sometimes the generated passphrase contains words with ligatures, like `fi`, `ff`, `ffi` etc. Some PDF viewers (mostly browsers) won't copy these ligatures and instead of `muffin` we will get `mufn` (`fi` disappears).

**To Reproduce**
1. Register a user.
2. Open provided PDF with the passphrase in the browser.
2. If there are words with ligatures, then they'll be gone when copy/pasting.

**Expected behavior**
All words should be copied correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/140053/86479608-25aa2980-bd55-11ea-88c1-a8a32560eab6.png)

**Additional context**
We can disable ligatures in OTF fonts we are using for PDF generation. I didn't found the solution fast, it will take some time to investigate.

**Comment by lucca65** [comment]
@amiskov do you think that maybe #264 is related to it?

**Comment by amiskov** [comment]
> @amiskov do you think that maybe #264 is related to it?

No, I think that #264 has something with the browser API and this one is about rendering fonts in the PDF.

**Comment by lucca65** [comment]
it makes sense! that’s an awesome catch @amiskov, i wonder how difficult it would be to debug this based on user feedback
