### ISSUE TITLE
Improve modal dialogs

### ISSUE THREAD

**Issue by amiskov** [cambiatus/frontend#292]
**Is your feature request related to a problem? Please describe.**
Modal dialogs have some design related issues. Modals have fixed heights and they become cropped when a server-side error occurs:
![image](https://user-images.githubusercontent.com/140053/87294272-29377080-c50c-11ea-8c7a-1a9cdfa91737.png)

The same for the desktops:
![image](https://user-images.githubusercontent.com/140053/87294295-32c0d880-c50c-11ea-8bbb-861298b6830e.png)

Also, we have duplicated code for almost every modal dialog. This could be improved for easier support and design consistency.

**Describe the solution you'd like**
Make modal dialogs flexible and stretch them by the height if needed.

The code could be improved by moving the view function for the modals to the separate module and use it across the codebase. This approach was introduced by #270 for changing the PIN on the Profile page, see the [`Modal.elm`](https://github.com/cambiatus/frontend/pull/270/commits/c68c8f978556b50aee2da7a7a46516200749a941#diff-7e2e4cd79c8146fb6b3af26d48cc0906) file.

**Comment by lucca65** [comment]
+1

**Comment by lucca65** [comment]
@amiskov I'm assigning this to you for the next! Please feel free to add other Modal improvements you see fit!
