### ISSUE TITLE
Ticolone's create account flow

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#295]
All changes are finished and are in those 6 screens:

https://www.figma.com/file/47BEsGEMSWfhTm3zC0ugyA/Main-flow?node-id=3%3A2206

@lucca65 , Let us know if it's possible to verify with an official Costa Rican Database when the user types their document number (is not a priority).

**Comment by lucca65** [comment]
@xavier506 kindly sent us this some instructions on how to approach this:

```javascript 
// Regex for form validation
if ( /^[1-9]-?\d{4}-?\d{4}$/.test('1-2345-6789') ) {
    // cédula válida
}
```

**Comment by lucca65** [comment]
I'm closing this because this screen actually relates to a lot of other stuff that is necessary. We will reopen this issue as several other, more detailed, issues

**Comment by heltonlr** [comment]
> I'm closing this because this screen actually relates to a lot of other stuff that is necessary. We will reopen this issue as several other, more detailed, issues

Ok @lucca65
