### ISSUE TITLE
Remove the search bar on the header

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#296]
Today, the search bar is only a link to the community page. 

**More details, here**
https://www.figma.com/file/RSoh4DDEj0N1TVkQT0SxIn/Header-and-Footer?node-id=288%3A1172

**Comment by lucca65** [comment]
is there a way to update the component on Figma on cases like this? All the pages except the one from the link has the searcher

**Comment by heltonlr** [comment]
Sorry @lucca65 , but in Figma, I can't control the size of components to auto adapt when a component is deleted. Will have a hole in all interfaces if I "apply" for all. But, when prioritized, this search going to back.

**Comment by heltonlr** [comment]
> don't worry @heltonlr I thought more about it and deleted the comment, it would be a lot of work with little benefit. Hopefully one day Figma will add this feature

There is this feature at Figma, but had been created after I developed this interfaces 😅

**Comment by lucca65** [comment]
lol, I see 😂
