### ISSUE TITLE
Changes on Profile and Public profile

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#298]
**Defined changes:**

- Show location and map on company profile;
- Remove the "download the 12 words" for both profiles
- Show the new information that was added during registration (https://www.figma.com/file/47BEsGEMSWfhTm3zC0ugyA/Main-flow?node-id=3%3A2206)

**More details, here:**
https://www.figma.com/file/47BEsGEMSWfhTm3zC0ugyA/Main-flow?node-id=948%3A468

**Comment by lucca65** [comment]
This will require us to finish reworking the registration if the community has enabled KYC.

Also we will not remove the download PDF anymore

**Comment by heltonlr** [comment]
> This will require us to finish reworking the registration if the community has enabled KYC.
> 
> Also we will not remove the download PDF anymore

Ok

**Comment by heltonlr** [comment]
Ok

**Comment by lucca65** [comment]
duplicate of #361
