### ISSUE TITLE
Add Action Claim Button on Objectives Page

### ISSUE THREAD

**Issue by victorgdev** [cambiatus/frontend#301]
**Describe the bug**
Add claim button for the objectives' actions

**To Reproduce**
1. Go to the objectives page
2. Click on the objective's arrow to open its detailed modal
3. Scroll down to action edit button

**Expected behavior**
By the action edit button there should be a claim button

**Screenshots**
![image](https://user-images.githubusercontent.com/53874965/87744360-52305d80-c7b9-11ea-999b-49b49ad28776.png)

**Cambiatus Env you are using**
app.cambiatus.io

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version ???

**Smartphone (please complete the following information):**
 - Device: Android, Iphone
 - OS: ???
 - Browser: Chrome
 - Version ???

**Comment by lucca65** [comment]
@heltonlr why have a claim button here? This is screen is only visible to admins

**Comment by heltonlr** [comment]
@lucca65 and @victorgdev 

Pessoal, desculpem por escrever em português (está corrido hoje)

Então,

Antigamente esta era a única tela onde admins e membros da comunidade acessavam para editar e fazer claim nas ações. Por isso o botão claim estava ai. Com o novo layout, os membros podem fazer claim no dashboard, se isso já foi desenvolvido (não tenho essa informação), o botão claim não é mais necessário nessa tela..Era essa a dúvida?

**Comment by lucca65** [comment]
Translating (roughly)...

> As it was before, it was the only screen where admins and members had access to edit and claim actions. That's why the button was there. With the new layout members can open a claim on dashboard. If that was already developed (I don't have this information), the button is no longer necessary in this screen. 

If that's the case, then we don't need the button there. Because we still have the old screen do to that, where admins and users can access. Adding this button only to admins is somewhat troublesome if it will be removed soon. 

If everyone is ok with it, I think its best to just close this issue and instead focus our efforts into finishing the dashboard's claim section

**Comment by heltonlr** [comment]
I agree,

**Dashboard with actions:**
https://www.figma.com/file/nEPG6Dkns8hDVCudVUTEzc/Dashboard?node-id=564%3A3

**New actions admin interfaces:**
https://www.figma.com/file/nEPG6Dkns8hDVCudVUTEzc/Dashboard?node-id=586%3A2577

Will a meeting be necessary? I am here
