### ISSUE TITLE
Allow users to delete their KYC information from the profile 10

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#315]
Should be finished after cambiatus/backend/issues/58 is finished.

**Comment by amiskov** [comment]
The flow for deleting KYC info:
- The user clicks the "Disallow" button from the [Profile page](https://www.figma.com/file/47BEsGEMSWfhTm3zC0ugyA/Ticolones-version?node-id=948%3A468).
![image](https://user-images.githubusercontent.com/140053/92352293-6d975500-f0e6-11ea-86a4-580a67f8de89.png)
- A modal confirmation dialog appears with a warning (already implemented in `kyc` branch);
- If the user confirms the deletion, then we send the GraphQL query and initiate [the deletion on the backend](https://github.com/cambiatus/backend/issues/58);
- When the deletion is completed, we show a notification to the user with the related message.
![image](https://user-images.githubusercontent.com/140053/92352549-05953e80-f0e7-11ea-9411-c967d8596295.png)
