### ISSUE TITLE
Install Fathom in Cambiatus app

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#319]
Install Fathom in Cambiatus' app and allow access to:

heltonlr27@gmail.com

ju.cristine20@gmail.com

rafa.chadud.dg@gmail.com

Is it possible see the numbers by Community? Muda, Pulps, etc

**Comment by lucca65** [comment]
@heltonlr Whats the access keys for it?

**Comment by heltonlr** [comment]
I thought you would do all these steps, from generating the keys.  I will provide that then 🤘

**Comment by lucca65** [comment]
thanks for helping us out, you folks will be the users, so it's best you have it! 💪

**Comment by lucca65** [comment]
closing this in favor of #407
