### ISSUE TITLE
Changing the Muda Logo

### ISSUE THREAD

**Issue by juramos-2020** [cambiatus/frontend#323]
**Is your feature request related to a problem? Please describe.**
The logo is too small which makes visibility of the app difficult for users.

**Describe the solution you'd like**
Switch to the attached logo and make it the size of the other icons (profile and notifications)
Place preferably in size 30x30px

**Describe alternatives you've considered**
If it cannot be the same size, it can be the closest possible size

**Additional context**
Later I send the logo in SVG through the slack.

![Logo Muda PNG](https://user-images.githubusercontent.com/67649886/89132909-f3bfea80-d4ed-11ea-9eb6-cf5e12d13ebc.png)

**Comment by lucca65** [comment]
Done!

**Comment by juramos-2020** [comment]
@lucca65 Thanks
