### ISSUE TITLE
Shop is not shown on first load

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#329]
**Describe the bug**
The shop link don't appear after a login. 

**To Reproduce**
1. Login with a user that belongs to a community that has the `has_shop` feature as `false`
2. See error

**Expected behavior**
Communities that have shop enabled should always have the link available at the menu

**Screenshots**
N/A

**Cambiatus Env you are using**
It happens on all Envs

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
 All

**Additional context**
We introduced the fix in a wrong way. Since we don't have the whole community data after the login (we only have the symbol) we added a default value as `False` to the loggedIn.init function. This causes this behaviour. We should improve login by returning the correct call.

**Comment by lucca65** [comment]
@RodrigoLeiteF you are currently working on the new login. I was thinking on adding community info to the new GraphQL login query. Any thoughts?

**Comment by RodrigoLeiteF** [comment]
> @RodrigoLeiteF you are currently working on the new login. I was thinking on adding community info to the new GraphQL login query. Any thoughts?

If we need the context, that's the best place to get it imo. :+1: from me

**Comment by RodrigoLeiteF** [comment]
Should we close this due to #330, or keep it open for a better implementation in the future?
