### ISSUE TITLE
PIN requested before user input validation in offer creation form

### ISSUE THREAD

**Issue by victorgdev** [cambiatus/frontend#333]
**Describe the bug**
Asking for user PIN before validating user inputs. 

**To Reproduce**
1. Go to 'Offer page'
2. Click on 'Create offer'
3. Press the create button without filling form out

**Expected behavior**
Form input fields should be validated before PIN request

**Screenshots**
![image](https://user-images.githubusercontent.com/53874965/89557575-033a7e80-d7e1-11ea-8f73-9c4ea835e7a2.png)

**Cambiatus Env you are using**
app.cambiatus.io/shop/new/sell

**Desktop (please complete the following information):**
 - Browser [Chrome]

**Smartphone (please complete the following information):**
 - Device: [iPhone 5/SE]
 - Browser [Safari]

**Comment by lucca65** [comment]
+1

**Comment by NeoVier** [comment]
This doesn't happen anymore:
![2021-06-16-192654_447x584_scrot](https://user-images.githubusercontent.com/39280468/122302685-d4993400-ced8-11eb-9933-dc71e5560285.png)
