### ISSUE TITLE
Comply to Netlify's Open Source requirements

### ISSUE THREAD

**Issue by SkyLeite** [cambiatus/frontend#344]
**Is your feature request related to a problem? Please describe.**
To become part of Netlify's Open Source plan, we need to make some changes to be approved by their team.

**Describe the solution you'd like**
1. Include a LICENSE file, containing any of the licences listed in https://opensource.org/licenses or https://creativecommons.org/
2. Feature a link to Netlify on the main page of the platform, either using one of their [pre-made badges](https://www.netlify.com/press/#badges) or a custom link that reads "This site is powered by Netlify"

**Describe alternatives you've considered**
1. Pay for the premium plan
2. Explore different hosting options

**Comment by lucca65** [comment]
After using Netlify for a while without any problems I think its safe to close
