### ISSUE TITLE
withFeature route fails

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#348]
**Describe the bug**
In MUDA, some users are unable to open certain pages, that they were able to before

**To Reproduce**
1. Go to https://muda.cambiatus.io (or open localhost pointing to MUDA)
2. Access this path: `/community/MUDA/objectives/6/action/13/claim/1786`
3. See error

**Expected behavior**
This link should work as it is a valid claim link. 

**Screenshots**
Screenshot sent on the bug report, we can see clearly that it was accessible at some point

![WhatsApp Image 2020-08-28 at 18 32 49](https://user-images.githubusercontent.com/1082127/91619518-a0fa1700-e963-11ea-81db-b6afecefe89d.jpeg)

**Cambiatus Env you are using**
https://muda.cambiatus.io/community/MUDA/objectives/6/action/13/claim/1786

**Desktop (please complete the following information):**
Happens on all desktop devices

**Smartphone (please complete the following information):**
Happens on all smartphone devices

**Additional context**
I did a little digging on this, and found out that the reason it don't work is because of [this function](https://github.com/cambiatus/frontend/blob/cd9d8e0e29c295ce92ae49fe1841fde90bf70337/src/elm/Main.elm#L625-L633). It works fine if I open the link using the `ClickedLink` Msg, but it won't work if we put the URL directly.

Removing this function makes the direct link work again, but then the `withFeature` filter don't work anymore.

**Comment by amiskov** [comment]
@lucca65 @RodrigoLeiteF This happens in the main repo as well. Try to go to any claim with clicking links, then copy the URL and try to access it by pasting to the address bar. You'll see 404.

**Comment by amiskov** [comment]
We are checking if `hasObjectives` is `True` in `src/elm/Main.elm:625` before `CompletedLoadSettings` from `src/elm/Session/LoggedIn.elm:717` updates it.

**Comment by amiskov** [comment]
@RodrigoLeiteF @lucca65 here's what I found so far.

Now, if we have disabled objectives in the community, the backend doesn't check this if we query the Claim and we can get it e.g. from the Graphiql interface. Maybe we should check if the community has Objectives enabled before returning the response with the Claim? I guess it could help us simplify the frontend and get rid of the async issue with `.hasObjectives`. I guess it's the [`get_claim`](https://github.com/cambiatus/backend/blob/master/lib/cambiatus/commune/commune.ex#L140) function.

You can check it [on the Graphiql](https://api.cambiatus.io/api/graphiql) with the query like this:

```graphql
# This query asks the `OLOL` community, which has objectives disabled.
{
  claim(input: {id: 197}) {
    id
    action {
      description
    }
    createdAt
    claimer {
      name
    }
  }
}

```

**Comment by RodrigoLeiteF** [comment]
I can't think of any drawbacks of going with that approach. Would make the API a bit more expressive as well, since it doesn't make sense for it to expose claims for a community with no objectives. What do you think @lucca65?
