### ISSUE TITLE
Case when restrictions are not working

### ISSUE THREAD

**Issue by amiskov** [cambiatus/frontend#359]
**Describe the bug**
There's a case when the user without KYC filled has full access to the community with enabled KYC.

**To Reproduce**

- The community hasn’t KYC enabled, user can do anything.
- Then, the community enables KYC, and the users without KYC who didn't refresh the page still have full access.

**Expected behavior**
Users without KYC filled should have no access to the community with KYC enabled even without refreshing the page in the case when the community decides to enable KYC.

**Additional context**
Related to #313

**Comment by amiskov** [comment]
Possible solution — use a subscription or something like that and notify the frontend about enabling KYC in communities.

**Comment by lucca65** [comment]
yeah, this is an exiting edge case, but I say we close this and on #316 we add the need to the session to end after a while due to inactivity. This way we can make sure the app is always up to date, even manually invalidate all tokens when a setting is changed

**Comment by lucca65** [comment]
Closing as we do have this possibility, but KYC is not being actively used in a way that requires this
