### ISSUE TITLE
Add a map to the company profile page

### ISSUE THREAD

**Issue by amiskov** [cambiatus/frontend#361]
**Is your feature request related to a problem? Please describe.**
On the design for the company profile, [there is a map](https://www.figma.com/file/47BEsGEMSWfhTm3zC0ugyA/Ticolones-version?node-id=948%3A1007):
![image](https://user-images.githubusercontent.com/140053/93582743-930c4480-f9ab-11ea-8d72-5f7c04e2f045.png)

Now we have a string with an address:
![image](https://user-images.githubusercontent.com/140053/93582991-eaaab000-f9ab-11ea-8298-a2d2c31b3268.png)

I think that it could be useful to have a string AND a map. It may be handy to copy-paste the address to send it to a friend or save the address to the address book. Also, there may be cases when Google map won't show the proper location. @heltonlr what do you think about having both a map and the address string on this page?

**Describe the solution you'd like**
Add a map, as the design suggests. This could be a Google map or other alternative.

**Describe alternatives you've considered**
Leave the address as a string.

**Comment by heltonlr** [comment]
Hey @amiskov , I liked the idea that there are the map and de address (string). We can put the map below the "Location."
