### ISSUE TITLE
Invalid text on account validate input

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#373]
**Describe the bug**
The text is wrong on the natural form, when I don't fill all the required characters

<img width="601" alt="Screen Shot 2020-09-28 at 11 57 26" src="https://user-images.githubusercontent.com/1082127/94449243-43373580-0182-11eb-8c81-534c9e130827.png">

**Comment by amiskov** [comment]
@RodrigoLeiteF there's another case with the same pattern:
![image](https://user-images.githubusercontent.com/140053/94474643-9a66f580-01d6-11eb-83ac-da93078be8e8.png)

**Comment by RodrigoLeiteF** [comment]
Thanks, I'm on it
