### ISSUE TITLE
Handle Buy click msg

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#381]
**Is your feature request related to a problem? Please describe.**
After buying the product from the Shop got this error. It didn't affect the purchase, just seems like we need to do something with it:
![image](https://user-images.githubusercontent.com/140053/95017386-b567b880-0661-11eb-99c9-b9732654fd6a.png)

**Describe the solution you'd like**
Handle that event properly

**Describe alternatives you've considered**
None

**Additional context**
Found during testing on PR #379

**Comment by dev-danilosilva** [comment]
This error is not happening anymore

**Comment by NeoVier** [comment]
This doesn't seem to be happening anymore. Probably because now there is a handler for that:
![2021-06-16-192342_569x263_scrot](https://user-images.githubusercontent.com/39280468/122302385-69e7f880-ced8-11eb-92b2-603046a8baaf.png)
