### ISSUE TITLE
Improve function `Eos.assetToString` to auto fill precision

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#383]
**Is your feature request related to a problem? Please describe.**
Today we have a function on the module `Eos` called `assetToString` that function is used to convert an asset (combining a `Float` and a `Symbol`) to a string. Right now it does uses `Symbol`s field `precision` to automatically add the necessary `.0`s to the final asset that is sent to the blockchain. We could improve it.

**Describe the solution you'd like**
Imagine a community with the ID `3,XXX`. If the user fills in a field to `10.5` this function should be able to add the necessary zeros:

```elm
> Eos.assetToString (Asset 10.5 (Symbol "XXX" 3))
"10.500 XXX"  : String
```

This might be a good opportunity to improve the `Eos` module, maybe even add a specific submodule and proper documentation. We need to discuss this together

**Describe alternatives you've considered**
Maybe we already have a module that does that on Elm, but I think we are the first app to have such Eos abstraction on Elm.

**Additional context**
This appear when we started supporting precision on our App. Now a bunch of places need better inputs to handle this type of thing

**Comment by NeoVier** [comment]
We can use the `Eos.formatSymbolAmount` function introduced in #494 to do this! The difference is that function doesn't add the symbol code (that's useful to use as a placeholder with `View.Form.Input.withCurrency`):

```elm
> Eos.formatSymbolAmount (Symbol "XXX" 3) 10.5
"10.500" : String
```

**Comment by lucca65** [comment]
nice! just a small composition to fix this!

**Comment by lucca65** [comment]
@victorgdev 👀
