### ISSUE TITLE
Shop shows success buy even if there is no balance to buy it

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#402]
**Describe the bug**
Shop shows the buy as successful even if it errors on the blockchain

**To Reproduce**
1. Go to Shop
2. Try to buy something from the shop that costs more than what you have of balance (use a sale with an exuberant value for safety as some communities allow for negative balance)
3. See error

**Expected behavior**
Show an error message, or at least a Toast/feedback with a generic error message

**Screenshots**
N/A

**Cambiatus Env you are using**
Demo, staging

**Comment by lucca65** [comment]
@victorgdev maybe you can tackle this one, its pretty straight forward

**Comment by NeoVier** [comment]
Is this still an issue? When I try to reproduce the behavior as listed, I get an error message:
![2021-05-01-175541_1335x501_scrot](https://user-images.githubusercontent.com/39280468/116794828-8950d080-aaa6-11eb-9e88-ef3d6eefd97c.png)

**Comment by lucca65** [comment]
🤔 looks like its fixed then! nice, one less! I love that you are taking the ownership over the frontend @NeoVier, hopefully the code can become a good portfolio for you in the future!

**Comment by NeoVier** [comment]
The most important is that I'm enjoying the ride and getting a lot of experience out of it! :rocket:

**Comment by lucca65** [comment]
damn, something got into my eye
