### ISSUE TITLE
View transfer screen

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#41]
Screen that shows a transfer, it receives an ID by the URL. The view should change depending on the user. If the user is involved on the transfer it should show "received" or "sent"

Also we should link this page with the transfer notifications

**Comment by Pancakem** [comment]
Hey @lucca65! I would like to have a go at this.

**Comment by lucca65** [comment]
this is a big one @pancakem!

let me know if you need any help! I’ll also link the design here


https://www.figma.com/file/X0ROabI93lbH0YsHDiwcFf/shop-mobile?node-id=0%3A1


https://www.figma.com/file/GyRvSEQNS91DOLgMIk3u77/shop-desk?node-id=0%3A1

**Comment by Pancakem** [comment]
@lucca65 thanks! I think I can crack it and get a better feel of the code base in the process. Is this the screen? How should the URL look like? I am guessing `/community/<>/transfer/<>` .

![tr](https://user-images.githubusercontent.com/36479602/69497903-ea0fcd00-0ef2-11ea-8f34-0ad30b334541.JPG)

**Comment by lucca65** [comment]
looks good!

**Comment by zacck** [comment]
@Pancakem how's this going for you, remeber to shout if you have any issues

**Comment by Pancakem** [comment]
@zacck I am going to start working on it tomorrow. If I get stuck, I'll make sure to shout.

**Comment by Pancakem** [comment]
@zacck are there any queries for a transfer?

**Comment by zacck** [comment]
@Pancakem  there aren't any you might have to add one or wait for me to add one for you tomorrow

**Comment by zacck** [comment]
@Pancakem I have a PR open https://github.com/cambiatus/backend/pull/20 to extend the schema to expose a single transfer, however this feature is already available in our staging environment at 
https://api.bespiral.io/api/graphiql

This means that you can run 
`yarn generate-graphql` 
and it will generate the necessary codecs for you to pull a single transfer 
please let me know if I can assist you further here

once again thank you so much for your contribution we really appreciate the help

**Comment by heltonlr** [comment]
Hey Team;

**Success transfer:**
https://www.figma.com/file/cVmLXESyfs6Vb5EdrcEh8U/profile-Desk?node-id=128%3A1594

**Success repeipt:**
https://www.figma.com/file/cVmLXESyfs6Vb5EdrcEh8U/profile-Desk?node-id=128%3A4925

**Comment by Pancakem** [comment]
@zacck I am almost done with this issue. I need a valid `transfer_id` so that I can get the correct page (not a loading or error page) when styling.

**Comment by zacck** [comment]
Hey @Pancakem  I see, awesome work so far you can get a valid transfer id by  running the following query in the `graphiql` endpoint at https://api.bespiral.io/api/graphiql

```
query{
  community(symbol:"BES"){
    transfers(first: 10){
      edges{
        node{
          id
        }
      }
    }
  }
}
```

**Comment by Pancakem** [comment]
Hey @zacck.  I added translations for the transfer screen but I can't get them to work.

**Comment by zacck** [comment]
@Pancakem  how come what results are you getting?

**Comment by zacck** [comment]
@Pancakem  plase open a PR and push so we can see what's not working for you

**Comment by lucca65** [comment]
hey @Pancakem when reporting problems like this, can you be more specific? 

examples:

- "I'm having trouble making the translations work. The text appears as "x""
- "I'm using this code snippet to load translations but they don't load properly" (and add a code snippet about it)

Since all the work we do is async having good communication and knowing how to ask for help is key!

**Comment by zacck** [comment]
@lucca65  this is such good advice, reminds me we should compile a contributions guideline it will make it much easier to onboard ...

**Comment by Pancakem** [comment]
The trouble am having with translations, for example, I use this `I18Next.t shared.translations "transfer.title" to load the translations ` but `transfer.title` appears.

**Comment by zacck** [comment]
@Pancakem  looking at your PR I dont think the `transferscreen` object is a root object seems to be a child of `menu`

**Comment by lucca65** [comment]
Oh I see! Looking your pull request I see that you added these lines:

```json
"tranferscreen": {
     "title": "Tranferred",
     "tranfer_success": "Hey, this transfer was successfully made",
     "receive_success": " Hey, this receipt was successful made",
     "date": "Date",
     "message": "Message",
     "community": "Community",
     "received": "Received",
     "tranferred": "Transferred",
     "error": {
       "invalid_id": " is not a valid Transfer Id"
     }
```

This means that in order to access the title you need to use:

```
I18Next.t shared.translations "transferscreen.title"
```

**Comment by Pancakem** [comment]
> Oh I see! Looking your pull request I see that you added these lines:
> 
> ```json
> "tranferscreen": {
>      "title": "Tranferred",
>      "tranfer_success": "Hey, this transfer was successfully made",
>      "receive_success": " Hey, this receipt was successful made",
>      "date": "Date",
>      "message": "Message",
>      "community": "Community",
>      "received": "Received",
>      "tranferred": "Transferred",
>      "error": {
>        "invalid_id": " is not a valid Transfer Id"
>      }
> ```
> 
> This means that in order to access the title you need to use:
> 
> ```
> I18Next.t shared.translations "transferscreen.title"
> ```

Yeah. I have changed the `transferscreen` object to `transfer`. It doesn't work.

**Comment by zacck** [comment]
@Pancakem  we  can session this out on vscode later today or early tomorrow I am positive it's some small misstep

**Comment by Pancakem** [comment]
@zacck yes we can.

**Comment by zacck** [comment]
@Pancakem  tomorrow morning, say 9am your time?

**Comment by Pancakem** [comment]
@zacck yeah 9am is fine.

**Comment by Pancakem** [comment]
@zacck Hey the translation errors were from a typo that I ended up pasting through the translations. @lucca65 spotted one and I have been able to make them work.

**Comment by zacck** [comment]
@Pancakem  awesome to hear let's keep going

**Comment by zacck** [comment]
@Pancakem so please let us know how this is going and if you need any help

**Comment by Pancakem** [comment]
I think what remains is making this responsive 
![image](https://user-images.githubusercontent.com/36479602/70808547-f0e27f00-1dd0-11ea-8f1f-99db576861dd.png)

**Comment by Pancakem** [comment]
@zacck I may need help doing this

> I think what remains is making this responsive
> ![image](https://user-images.githubusercontent.com/36479602/70808547-f0e27f00-1dd0-11ea-8f1f-99db576861dd.png)

**Comment by zacck** [comment]
@Pancakem  how can we help you with this?
