### ISSUE TITLE
Improve errors handling on frontend

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#419]
Following the excellent example of PR #425, we should localize our error messages to be shown. It might cause a strange impression to some users but it will come a long way into helping us figure out what's going on on our contract calls

Here are all the pages where we should handle errors:

- [x] [Shop buy](https://github.com/cambiatus/contracts/blob/1ae0906ba20451794713f6b41af1f750a3b747cd/community/community.cpp#L925) → #451 
- [ ] [Community creation](https://github.com/cambiatus/contracts/blob/1ae0906ba20451794713f6b41af1f750a3b747cd/community/community.cpp#L23) and [Token creation](https://github.com/cambiatus/contracts/blob/1ae0906ba20451794713f6b41af1f750a3b747cd/token/token.cpp#L16)
- [x] [Transfers](https://github.com/cambiatus/contracts/blob/1ae0906ba20451794713f6b41af1f750a3b747cd/token/token.cpp#L149) → #432.
- [ ] [Sale creation](https://github.com/cambiatus/contracts/blob/1ae0906ba20451794713f6b41af1f750a3b747cd/community/community.cpp#L764)
- [ ] [Action creation](https://github.com/cambiatus/contracts/blob/1ae0906ba20451794713f6b41af1f750a3b747cd/community/community.cpp#L256)
- [x] [Open Claims](https://github.com/cambiatus/contracts/blob/1ae0906ba20451794713f6b41af1f750a3b747cd/community/community.cpp#L502) → #416
- [ ] Add missing Amharic translation for all these kinds of errors.

**Comment by amiskov** [comment]
@lucca65 Thanks for collecting all those links! I'll take this issue as my next then?

**Comment by lucca65** [comment]
@amiskov I do think its important to work on this one next.

Actually I just had an experience that I think we could improve a lot. I think we could work on the error handling to send more info to Sentry. [Sentry has a way set which user is logged when the error happens](https://docs.sentry.io/platforms/javascript/enriching-events/identify-user/). It would be awesome to know which of the events we got are the one of the user we are supporting right now.

Another thing we could add is to change the "EOS error" error to actually use the blockchain error, because right now all blockchain errors are grouped. Maybe we can have a tag with EOS but not all errors under the same item on sentry. Sentry also supports [breadcrumbs](https://docs.sentry.io/product/error-monitoring/breadcrumbs/) that we can add so we know the context of the action that failed

Maybe we can have sentry on both [Elm](https://package.elm-lang.org/packages/romariolopezc/elm-sentry/latest/) and Javascript.

I do think those comments are more important to have than the error feedbacks on the description. What are your thoughts on this?

**Comment by lucca65** [comment]
this can get pretty big pretty fast, we can break this into several issues, but I think making sentry more useful is super important, at least that's what I use the most to help users on the day to day, Let me know your thoughts before we assign and start the work @amiskov

**Comment by amiskov** [comment]
@lucca65 It's great that we can improve Sentry error reporting! I think we should have a separate issue for that.

For now, I suggest taking a simple step and add error messages to the pages you listed. This task seems to be pretty easy and fast. And then explore Sentry docs and improve reporting for the frontend.

I think it's even more important not to leave our users frustrated with "Oops, something went wrong". With better error messages users could provide us more details when reporting problems.

Even more, those error messages could help users fix their issues by themselves, like using the description with 10-255 symbols for the action or product description.

**Comment by lucca65** [comment]
Not sure bro, I got no complaints about this (255 chars, sale creation, oops something went wrong), but we got every day reports about claims failures and login issues. I'll open another issue for Sentry improvements, but the improvements themselves only serve for us to improve our response when facing something that we cannot reproduce, but we can see happening with the user

**Comment by lucca65** [comment]
I'm 100% in adding the feedback to all the blockchain calls, this must be done and will improve a lot the experience (I feel the transfer page REALLY needs this)

**Comment by amiskov** [comment]
> we got every day reports about claims failures and login issues

@lucca65 Looks like we really need to concentrate on this now! If you think that improving Sentry reports may help with this, then I'll just start working on it!

**Comment by lucca65** [comment]
thinking back you are right @amiskov better to not loose focus and finish this from top to bottom!

**Comment by lucca65** [comment]
@NeoVier can you review this?

**Comment by NeoVier** [comment]
It seems like the issue description still holds, we are still missing those translations. It might also be nice to review the translation files for missing translations and unused translations (that will probably take a while and be pretty boring to do though), since the translation files all have a different number of lines:

- pt-br has 1299 lines
- en-us has 1293 lines
- es-es has 1296 lines
- amh-eth has 1254 lines (around 40 lines missing!)
- cat-cat has 1295 lines

Maybe we could create a quick script to check the difference between files, and add a step on our CI that checks that all the files have the same keys

**Comment by lucca65** [comment]
we can use a diff tool to explore this further. A while ago @SkyLeite suggested us to use `jq` to better interact with our translation files. I think this still holds, check out this gist https://gist.github.com/ipan/e5e86d5495f16216e31fe12ebc9532a4

**Comment by lucca65** [comment]
that's one of those unix puzzles that can be fun to crack

**Comment by lucca65** [comment]
Community creation and sale are done, @NeoVier?

**Comment by NeoVier** [comment]
We already capture those errors and show generic error messages, but we don't have translations for them yet, which I believe is the point of this issue (adding specific translations for each contract error)

**Comment by lucca65** [comment]
Closing, too old
