### ISSUE TITLE
Show error details while voting on a claim

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#422]
**Is your feature request related to a problem? Please describe.**
Users have no feedback when their vote fails

it can have multiple reasons, we log them on sentry but it would be useful to have them displayed somewhere for the user too

**Describe the solution you'd like**
add a collapsible text on the feedback informing the state 

**Describe alternatives you've considered**
ask the design team for alternatives 

**Additional context**
claims are still buggy, we need to interact over it to fix the voting flow

**Comment by lucca65** [comment]
@amiskov just letting you in this!

**Comment by amiskov** [comment]
Here are my thoughts on this.

While parsing the response from EOS after voting we silently send `(Err Encode.null)` in case of an error. So, we receive just encoded `null` value inside `Err` variant of a `Result` containing the voting outcome:

https://github.com/cambiatus/frontend/blob/ad8113e63e2398ce40f80b1b726bd4f587a70b9e/src/elm/Page/Dashboard.elm#L933-L942

But the EOS send us the response with an error in JSON like this:

```json
{
  "code": 500,
  "message": "Internal Service Error",
  "error": {
    "code": 3050003,
    "name": "eosio_assert_message_exception",
    "what": "eosio_assert_message assertion failure",
    "details": [
      {
        "message": "assertion failure with message: There are no usages left for this action",
        "file": "wasm_interface.cpp",
        "line_number": 1075,
        "method": "eosio_assert"
      },
      {
        "message": "pending console output: ",
        "file": "apply_context.cpp",
        "line_number": 113,
        "method": "exec_one"
      }
    ]
  }
}
```

I'm thinking about parsing this JSON and attaching the appropriate message to the `GotVoteResult` variant. This allows us to show the appropriate message to the user. We can match translations for these messages by their code (something like `claimVoteError3050003`).

How does it sound to you @lucca65?

**Comment by lucca65** [comment]
Looks good @amiskov! the only detail I would add is that the code is from EOS, that is all assertions will fail with the same code, so the message is also important `ClaimVoteError String` would be the type to go. Maybe we could expand Feedback type to include optional details that can be shown

**Comment by lucca65** [comment]
Maybe be part of the efforts on #419
