### ISSUE TITLE
App fails to render when it uses the root path

### ISSUE THREAD

**Issue by natillasol** [cambiatus/frontend#45]
**Describe the bug**
Can't access app.cambiatus.io   in Safari, Chrome.   NOTE that it DOES work in Firefox.

**To Reproduce**
1. Go to 'app.cambiatus.io'

OR 

1. Go to borboins.cambiatus.io

**Expected behavior**
a blank page will appear

**Screenshots**
in the annex. 

**Cambiatus Env you are using**
app.cambiatus.io 
borboins.cambiatus.io

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina 10.15.1
 - Browser:  Chrome and Safari
 - Version:  Chrome Version 78.0.3904.97 (Official Build) (64-bit) .  |    Safari Version 13.0.3 (15608.3.10.1.4)

**Smartphone (please complete the following information):**
 - Device: LG 
 - OS: Android 7.0
 - Browser: Chrome 
 - Version: 78.0.3904.96

**Additional context**
<img width="1436" alt="Screen Shot 2019-11-13 at 09 35 57" src="https://user-images.githubusercontent.com/57719975/68779830-e7f86500-05fa-11ea-896a-b764054df978.png">

**Comment by zacck** [comment]
@lucca65  even with nginx reloading this persists for me :(

**Comment by lucca65** [comment]
I had these on muda after a reset on Nginx, we will need to work more on this

**Comment by lucca65** [comment]
closing as this is better explained on #252
