### ISSUE TITLE
Remove “mark as complete” during creation

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#465]
**Describe the bug**

Remove “Mark as complete” button from the creation forms, add only on the editing forms.

**To Reproduce**
1. Go to the Action form
2. See error

**Expected behavior**
The button should only appear during edit

**Screenshots**
N/A

**Cambiatus Env you are using**
demo.cambiatus.io and staging.cambiatus.oi

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Additional context**
Found during @heltonlr tests

**Comment by dev-danilosilva** [comment]
This problem is already solved. The "Mark as Complete" button appears only in the editing action form.

**Comment by lucca65** [comment]
nice! thanks @dev-danilosilva 🙏
