### ISSUE TITLE
Community Logos not showing

### ISSUE THREAD

**Issue by natillasol** [cambiatus/frontend#47]
**Describe the bug**
The community logos or icons are not showing.

**To Reproduce**
1. Go to app.cambiatus.io
2. Click login
3. See error

**Expected behavior**
There would be instead a blank square with a broken paper icon on the top left corner. 

**Screenshots**
in annex 

**Cambiatus Env you are using**
app.cambiatus.io         AND    borboins.cambiatus.io

**Desktop (please complete the following information):**
 - OS: MacOS Catalina version 10.15.1
 - Browser: Firefox 
 - Version : Quantum 66.0.3 (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
<img width="1440" alt="Screen Shot 2019-11-13 at 10 02 55" src="https://user-images.githubusercontent.com/57719975/68781459-71a93200-05fd-11ea-8547-4514c19f242c.png">
<img width="1432" alt="Screen Shot 2019-11-13 at 10 02 48" src="https://user-images.githubusercontent.com/57719975/68781460-71a93200-05fd-11ea-82dd-b7ef051cb34f.png">

**Comment by lucca65** [comment]
Fixed! IPFS was down
