### ISSUE TITLE
Improve size of our loading Gif

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#470]
**Is your feature request related to a problem? Please describe.**
This is not a bug but rather a optimization to improve our load time. It would be great to make the loading gif smaller, today it takes 502 kb

**Describe the solution you'd like**
An animated SVG

**Describe alternatives you've considered**
Maybe a video? idk we should research

**Comment by NeoVier** [comment]
We should also fix it for dark (or just non-white) backgrounds, where we can see some white pixels around it:
![2021-05-07-093015_225x161_scrot](https://user-images.githubusercontent.com/39280468/117449895-e4efe380-af16-11eb-866d-62950a49a998.png)

**Comment by heltonlr** [comment]
Sure @lucca65 , 

@rafachadud , you created the loading gif. Can you help us?

**Comment by rafachadud** [comment]
I'll try to create an animated SVG.

**Comment by NeoVier** [comment]
It works perfectly, thanks @rafachadud
