### ISSUE TITLE
Add Search to LoggedIn.

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#471]
Like we did with Feedback, it should have a panel that is global, independent of the current page. 

This panel should query the local storage to get the recent searches.

After a successful reply from the server with the query results, we need to save the query to the local storage as well

The page should have at least three steps:

- Empty with recent research
- All results (can be empty or can have categorized results)
- Category results (showing a tab on the top that scopes the results)

Maybe this can be a child module similar to what we do with modals, passing `Msg`s into it

**Comment by amiskov** [comment]
Here's the Figma [design for the search](https://www.figma.com/file/BWrtIrnhAIsgc6fksy6bcU/Search?node-id=0%3A1&viewport=1010%2C3438%2C0.7584198713302612).
