### ISSUE TITLE
Create "Add a Phone Number" Modal

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#473]
This modal has several rules, about when it should appear, including a "New Tag" and some local storage information. 

Users will always be prompted as long as they 

1) don't fill in their phone
2) havent explicitly asked not to see the modal again

https://www.figma.com/file/ILiFX32kN5TRQtUhbA0Z5u/New-Shop?node-id=4%3A408

**Comment by marcjal** [comment]
How can I help with this issue?
