### ISSUE TITLE
Update contact information on the Private Profile

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#474]

**Comment by marcjal** [comment]
To solve this issue I need some special privileges? can you indicate a path to this bug?

**Comment by lucca65** [comment]
hey @marcjal those issues related to phone number require a feature on the backend that still needs to be implemented, I suggest you take a look at this one: https://github.com/cambiatus/frontend/issues/165

**Comment by marcjal** [comment]
> hey @marcjal those issues related to phone number require a feature on the backend that still needs to be implemented, I suggest you take a look at this one: #165

Thanks! Let me check

**Comment by marcjal** [comment]
@lucca65 are you using a pattern for the branch creation? the branch is created from master?

**Comment by lucca65** [comment]
this doesn't really matter, feel free to use whatever
