### ISSUE TITLE
Logo not showing in action page

### ISSUE THREAD

**Issue by natillasol** [cambiatus/frontend#48]
**Describe the bug**
Logo not showing in action page

**To Reproduce**

Go to app.cambiatus.io
Click login
See error

**Expected behavior**
broken paper icon instead of image 
<img width="1288" alt="Screen Shot 2019-11-13 at 10 11 38" src="https://user-images.githubusercontent.com/57719975/68782117-71f5fd00-05fe-11ea-8f9e-4d38516a495e.png">
<img width="1440" alt="Screen Shot 2019-11-13 at 10 14 41" src="https://user-images.githubusercontent.com/57719975/68782118-71f5fd00-05fe-11ea-9210-2266a748cce6.png">

**Screenshots**
in annex

**Cambiatus Env you are using**
app.cambiatus.io AND borboins.cambiatus.io

**Desktop (please complete the following information):**

OS: MacOS Catalina version 10.15.1
Browser: Firefox
Version : Quantum 66.0.3 (64-bit)

**Comment by lucca65** [comment]
Fixed!
