### ISSUE TITLE
Add community selector as a "welcome message"

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#482]
**Is your feature request related to a problem? Please describe.**
Users sometimes don't know on which community they are in, adding a selector after the login would help a lot!

**Describe the solution you'd like**
Make our community selector to be the first thing users see when login in on a community

**Comment by lucca65** [comment]
@heltonlr can you provide an Updated modal link here?

**Comment by heltonlr** [comment]
Let me know what you think @lucca65 and @amiskov 

https://www.figma.com/file/nEPG6Dkns8hDVCudVUTEzc/Dashboard?node-id=566%3A19
