### ISSUE TITLE
Claim box does stays fixed when scrolling down

### ISSUE THREAD

**Issue by natillasol** [cambiatus/frontend#49]
**Describe the bug**
Claim box does stays fixed when scrolling down, so ultimately I cannot read the text. 

**To Reproduce**
1. Go to app.cambiatus.io
2. Login
3. Press on community 
4. Click on action
5. Click on objective
6.Click in claim

**Expected behavior**
The claim box will appear at the bottom of the page, but the user is unable to read it completely, because when one scrolls down, the box remains at the bottom of the page. 

**Screenshots**
<img width="1440" alt="Screen Shot 2019-11-13 at 10 16 51" src="https://user-images.githubusercontent.com/57719975/68782702-6ce57d80-05ff-11ea-87a8-c7cca247fcc2.png">
<img width="1440" alt="Screen Shot 2019-11-13 at 10 16 48" src="https://user-images.githubusercontent.com/57719975/68782703-6ce57d80-05ff-11ea-8841-2be871ef8b25.png">

**Cambiatus Env you are using**
https://borboins.cambiatus.io/community/BOR

**Desktop (please complete the following information):**
 OS: MacOS Catalina version 10.15.1
Browser: Firefox
Version : Quantum 66.0.3 (64-bit)

**Comment by zacck** [comment]
@pancakem I challenge you to try this one out
