### ISSUE TITLE
Fix build action

### ISSUE THREAD

**Issue by NeoVier** [cambiatus/frontend#505]
**Describe the bug**
Whenever we push commits, a [build action](https://github.com/cambiatus/frontend/blob/master/.github/workflows/on-push-action.yml) runs. Right now, it's failing with the following error:
```sh
Error: Cannot find module 'react-dev-utils/InterpolateHtmlPlugin'
```

**To Reproduce**
To reproduce, you can do the same as the action does:
1. Clone the repo
2. Run `yarn install --production`
3. Run `yarn build`

**Expected behavior**
The build action should complete successfully

**Screenshots**
![2021-04-13-231609_930x848_scrot](https://user-images.githubusercontent.com/39280468/114644725-6fde1500-9cae-11eb-9a4f-5290ec46c5bc.png)

**Desktop (please complete the following information):**
 - OS: Linux
 
**Additional context**
It works fine when building locally or for staging/demo/prod because we just use `yarn install`. The `--production` flag makes it so [we don't install devDependencies](https://classic.yarnpkg.com/en/docs/cli/install/#toc-yarn-install-production-true-false), and `react-dev-utils` is listed as a devDependency

**Comment by lucca65** [comment]
how come we don't have this problem on production? 🤔

**Comment by NeoVier** [comment]
Are you compiling with the `--production` flag? If so, could it be something with an old `node_modules`? :thinking:

**Comment by lucca65** [comment]
we run `yarn build` which is an alias to `yarn bundle` and that command is: 

```javascript
    "bundle": "NODE_ENV=production yarn webpack --color --mode=production --config config/webpack.config.prod.js",
```

so yes...

**Comment by NeoVier** [comment]
Oh, my bad. It's not on `build`/`bundle`, it's on `install`. So `yarn install` and then `yarn build [--production]` works fine, but `yarn install --production` and then `yarn build [--production]` does not.

**Comment by lucca65** [comment]
yeah we really don't run install it like that, the pipelines for deploy and for the CI are different. We can solve this by always using `yarn bundle` and add `yarn install --production` to the yarn alias. Because we only run `yarn bundle` when deploying to prod, there is no other scenario. Then the situation would be replicable everywhere and it would even help us improving build time, after all we are with a bigger `node_modules` than it need to be. The solution seems straight forward: 1) change the CI 2) change the `yarn bundle` command 3) fix errors 4) profit

what do you think?

**Comment by NeoVier** [comment]
Yep, sounds good. I haven't gone too deep on our build process and I don't know much webpack, so I'm not really sure how to fix this.

From what I see, we use `react-dev-utils/InterpolateHtmlPlugin` (which is what is causing the issue) on `webpack.config.prod.js` to replace variables like `%PUBLIC_URL%` in the final `index.html` (if I understood that correctly). Maybe there's some other way to do that, or some other plugin we could use? Apparently we can get that specific plugin separate from `react-dev-utils`: [GitHub link](https://github.com/egoist/interpolate-html-plugin), [npm link](https://www.npmjs.com/package/interpolate-html-plugin). But it also says to install as a dev dependency :thinking:

**Comment by lucca65** [comment]
yeah, this is the famous "cornojob" bro... picking cherries among the packages
