### ISSUE TITLE
Support more phone numbers

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#508]
**Is your feature request related to a problem? Please describe.**
With new communities and users coming into the platform, we need to support phone numbers from more countries

**Describe the solution you'd like**
Support phone numbers from the following countries:
- [x] Portugal
- [x] Canada
- [x] United Kingdom
- [x] New Zealand

**Describe alternatives you've considered**
- Support specific countries (what we're doing now) with custom placeholders and icons
- Support all countries. We'd still have placeholders, but not well formatted (`11912345678` vs `11 91234 5678`), and would probably need to use a third-party icon set for the flags

**Additional context**
Came from [this slack thread](https://cambiatus.slack.com/archives/CA83HJAAD/p1619743728000300)

**Comment by venomnert** [comment]
Portugal - `+351 xx xxx xxxx`
Canada - `+1 xxx xxx xxxx`
UK - `+44 20 xxxx xxxx`
NZ -` +64 2xxx xxxx(xx)`

**Comment by NeoVier** [comment]
@heltonlr can we get some flag icons for these countries? They'll be used in the profile contact form and in the "add contact" modal

**Comment by NeoVier** [comment]
[Here](https://www.figma.com/file/uAZdgsI1d7qW5kyBNWQZp1/flags?node-id=0%3A1) is the flags library we should use (**we should also change the flags we're already using for the ones in this library**)
