### ISSUE TITLE
Redirect to "My Claims" after a claim

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#509]
Users are doing too many claims one after the other, to the point its becoming spam. We will have to address this properly soon, but for now lets make their spammy work harder by redirecting them to another page -- "My Claims"

**Comment by lucca65** [comment]
how is it going @victorgdev?

**Comment by victorgdev** [comment]
@lucca65 was initially planning to work on this issue throughout this week, but had to fix the problem with the simulation algorithm on the Neutro app. Started working on this yesterday, my goal is to still finish this issue by the end of today, worst case on Monday.

**Comment by lucca65** [comment]
hmm, second week that this happens, since this have some urgency (needs to enter on the next week) I'll assign this to @NeoVier, ok?
