### ISSUE TITLE
Its not possible to delete contact information

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#510]
**Is your feature request related to a problem? Please describe.**
There is no button to delete contact information, even with the API supporting it

**Describe the solution you'd like**
A delete/thrash button somewhere.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by juramos-2020** [comment]
Hi @Lucca @Henrique Buss

Here is the option to delete the contact information. 
To remove contact information from the profile the user can also clear the fields and save.

https://www.figma.com/file/ILiFX32kN5TRQtUhbA0Z5u/New-Shop-Contact?node-id=0%3A1
