### ISSUE TITLE
Can't join community if you're not logged in, but already have an account

### ISSUE THREAD

**Issue by NeoVier** [cambiatus/frontend#512]
**Describe the bug**
If you try to join a community that needs invites and you're not logged in, it takes you to the registration page. If you then try to log in with an account that already exists but isn't a member of that community, you get an "Auth failed" message instead of being redirected to the invite page. This happens because the invitation id isn't carried over from the registration page to the login page.

**To Reproduce**
1. First, make sure you're logged out
2. Try to join a community that requires invitation and you're not a part of through an invite link
3. Click "Join" - this will take you to the registration page
4. Click on "Already have an account? Login"
5. Login with an account that's not part of the community
6. See an "Auth failed" error, and that the invitation didn't work (you're not a part of the community you were invited to)

**Expected behavior**
After logging in, you should be redirected back to the invitation page, so you can join the community, and then be redirected to that community's dashboard

**Screenshots**
N/A

**Cambiatus Env you are using**
staging.cambiatus.io

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Discovered while trying to replicate #511

**Comment by lucca65** [comment]
@NeoVier is this still happening?

**Comment by NeoVier** [comment]
It's slightly different, but it is still happening. I've updated the issue description for better clarity

**Comment by lucca65** [comment]
okay!
