### ISSUE TITLE
We don't store cursorId on the query string params on the analysis page

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#521]
**Describe the bug**
When exploring the `/dashboard/analysis` page we don't keep the filters and cursors, so when we click on a specific page and try to go back where we left off, we need to explore again, clicking the "more button" and/or selecting filters again

**To Reproduce**
1. Go to `/dashboard/analysis` page
2. Click on "Show next 16 items"
3. Click on any claim
4. Try to go back
5. see error

**Expected behavior**
We should see where we left off

**Comment by NeoVier** [comment]
We've decided for a different approach: #536
