### ISSUE TITLE
Mark actions as completed when completing an objective

### ISSUE THREAD

**Issue by NeoVier** [cambiatus/frontend#524]
**Is your feature request related to a problem? Please describe.**
When we mark an objective as completed, we don't mark the actions under that objective as completed as well.

**Describe the solution you'd like**
We should mark all of the actions of an objective as completed when we mark the objective as completed

**Describe alternatives you've considered**
As @lucca65 pointed out in #519, we might need a loading modal to display the progress

**Additional context**
Came up in #519

**Comment by muguika** [comment]
this could also be added to #540 @rafachadud   like "Completed Objectives" which is fantastic because a community achieving its objectives is the whole purpose of Cambiatus... it should be a little celebration, maybe with a special icon.

**Comment by lucca65** [comment]
I love this, from our perspective this was more of a "meh" feature

Glad to visited the repo Karla!

**Comment by muguika** [comment]
come on... nothing is "meh" about Cambiatus :D

**Comment by NeoVier** [comment]
@rafachadud @juramos-2020 can you help us out with this one? Here are some of our thoughts:

- Objectives might have a lot of actions in them, and when we mark the objective as complete, we need to mark each action as complete individually. So it would probably be nice to have some way to show the progress (e.g. "Marking actions as completed - 5 out of 10 completed").
- Completing an objective should be something special for the community. There should be some sort of celebration when it happens (and we should probably make it clearer throughout the app that this is an important thing). Right now, you just click a button and pretty much nothing happens.
- The objectives page is pretty old, and might be confusing for some people.

These are just some things to keep in mind, and we can/should address them separately. In this issue, we're mainly trying to address the first one, so **we need a way to show progress when the admin clicks "Mark objective as completed"**, can you help us out with that? :smile:

**Comment by juramos-2020** [comment]
Hi @NeoVier 

I can think of something to **a way to show progress when the admin clicks "Mark objective as completed"** 
but I can only submit a proposal next week. Can be?

**Comment by NeoVier** [comment]
Sure @juramos-2020 let me know if you need any help!

**Comment by NeoVier** [comment]
@juramos-2020 any news on this one?

**Comment by juramos-2020** [comment]
Hi @NeoVier @rafachadud 

What do you think this proposal?
https://www.figma.com/file/nEPG6Dkns8hDVCudVUTEzc/Dashboard?node-id=2749%3A9695

Remembering that when you mark an abjective as "complete" automatically all your actions will be marked as "complete" as well. This is the desired behavior. 😉👍

**Comment by juramos-2020** [comment]
@NeoVier 

> Remembering that when you mark an abjective as "complete" automatically all your actions will be marked as "complete" as well. This is the desired behavior. 😉👍

I need to confirm that this behavior is correct.

**Comment by NeoVier** [comment]
@juramos-2020  yes, that's the expected behavior **after this issue is done**.

About the designs: Can we have something to indicate progress on marking the actions as complete (maybe a modal)? There's a more detailed explanation on my comment above:

> Objectives might have a lot of actions in them, and when we mark the objective as complete, we need to mark each action as complete individually. So it would probably be nice to have some way to show the progress (e.g. "Marking actions as completed - 5 out of 10 completed").

**Comment by juramos-2020** [comment]
@NeoVier 

Could you explain better what you have in mind?
I had read your comment and understood that it was the progress bar 😅

https://www.figma.com/file/nEPG6Dkns8hDVCudVUTEzc/Dashboard?node-id=2744%3A8915

**Comment by NeoVier** [comment]
Oh, my bad :sweat_smile:. I mean like a progress indicator that only shows up when the user clicks "Complete objective". It should "freeze" the app (user can't interact with anything), fill up entirely, and only then redirect the user to the other objectives page.

As an example, you know how when you open a figma document there's a loading screen (with the figma logo and a loading bar below it)? That loading bar is pretty much what we need. In our case, besides just the loading bar, we could also add progress in numbers (5/10 actions completed, or 50% actions completed, etc)

**Comment by juramos-2020** [comment]
@NeoVier 

would it be more or less that you have in mind?
**obs.:** I'm still going to add the Loading icon. I need Rafa to share it with me so I can't get it to you ready until tomorrow.

https://www.figma.com/file/nEPG6Dkns8hDVCudVUTEzc/Dashboard?node-id=2758%3A9570

**Comment by NeoVier** [comment]
Yes, that's about it! What do you think about adding a white background behind the bar? And also maybe some text to explain what's happening? (Like "We're completing all the actions in the objective... 1 of 3 completed actions")

Also, can you provide a desktop example, so I know what size it should be?

And if you need it, here's the loading icon we use: https://github.com/cambiatus/frontend/blob/master/public/images/loading.svg

**Comment by NeoVier** [comment]
@lucca65 I'm wondering about this issue... Is there a reason we can't just do one transaction with a bunch of `upsertaction`s marking each action as completed? The drawback is we can't really track real-time progress that way, but it would probably be faster, no?

**Comment by lucca65** [comment]
That's actually a great question and I'm glad to hear this. Usually, yes, we could do this, just wrap them in an array and let it rip! The problem here is related to how EOS handle resources. You see, on blockchain we usually have a way to use the miner's services, since they are validating the transaction and all, and that is the fee. Some chains like Ethereum call it gas and it varies in value. The gas/fee amount is usually tied to a CPU time, so one greed actor cannot expand all the network resources (network being the block producers/miners that validate every single transaction). 

EOS don't have fees, instead it uses stacking, you lock some funds and with it you gain access to the usage of the network resources, depending on how much you've stacked. Imagine like you rented some land and until you are paying you can use its resources, remove the stake and you can no longer enjoy those "land services" you get.

the point is: all transactions have a cost, one way or the other, validating claims actually run some operations (some ifs, some fors) and that cost CPU time, which is a resource that have a concurrent limit. The mechanism to limit CPU/RAM time on EOS is the *real reason* why we may need to actually send several transactions.

If we simply do as you suggested, if one action failed, all of the others would fail. And with so many transactions together, it would clog the CPU time really easy. 

Not sure if this is the best explanation or the best examples, but having several transactions getting in in different blocks means that we can circumvent the CPU limitations sometimes. Having them all together in the same transactions means that, if one fails, all of them roll fail, as the transaction as a whole will not be accepted

**Comment by lucca65** [comment]
its great food for thought! How do humans share limited resources that heal over time? Is it possible to reach consensus on what's actually happening on chain? 

on the tradicional web we simply scale until it breaks, and usually we go long ways to reach that "agreeable source of truth", this "consensus". Uber has a consensus within all its database that you really called that rider and is no longer looking for another one, which is really impressive because of its scale and by knowing its not actually one database, its 1000s of them, with replica sets and etc.

us humans tried to built computers with the idea that its possible to have a central source of truth, much like all human work so far on religion or even the contemporary notion of science. But looks like nature doesn't work that way. it doesn't have a single source of truth, its just small parts with perspectives of the whole. 

digressions apart this type of problem that is deeply shown in blockchain due to its design limitations are one of the reasons why I think p2p networks looks more future proof than blockchain, having a final source of truth is not good for you health, can drive you crazy and require marvelous feats to achieve

**Comment by juramos-2020** [comment]
Hi @NeoVier sorry for delay

Here is the proposal: https://www.figma.com/file/nEPG6Dkns8hDVCudVUTEzc/Dashboard?node-id=2758%3A9570
What do you think?

I talked to @rafachadud today and she will do the animation on the final screen. But you can pace these progress bar screens while she creates the animation.

**Comment by lucca65** [comment]
I loved this progress bar, looks amazingly beautiful!

can we also have a modal explaining the consequences of this to the user? All actions will be completed, etc

**Comment by juramos-2020** [comment]
@lucca65 
you say: add a modal in this same stream?
Besides having the progress bar with this information, have one more modal?

**Comment by lucca65** [comment]
I'm thinking about a way to confirm or at least let the user know what happens after this button is pressed, It may be clear to us, but for new users all those screens can be overwhelming. 

it can be a section with an explanation, or maybe a confirmation modal,

**Comment by NeoVier** [comment]
> can we also have a modal explaining the consequences of this to the user? All actions will be completed, etc

We already have something like that:

![2021-07-05-180602_903x396_scrot](https://user-images.githubusercontent.com/39280468/124517973-b75ed380-ddbb-11eb-829f-79ba9230b011.png)

Maybe we should adjust the text to say that the actions are going to be marked as complete as well

**Comment by NeoVier** [comment]
@lucca65 thanks for the amazing explanation, that's really interesting, and it's something we usually don't consider. Thanks for the amazing lesson :moyai:

**Comment by lucca65** [comment]
nice! some extra text should be enough for now! 💪

**Comment by lucca65** [comment]
gotta love that emoji

**Comment by NeoVier** [comment]
So, the flow I'm imagining for this is:

1. User clicks on "Complete objective"
2. We show the explanation, and ask for a confirmation
3. User confirms they want to complete the objective
4. We start sending transactions to the blockchain and showing the (amazing btw) loading screen

Now there's a fork I'm not really sure about:

- If every action is completed successfully, we send a mutation to the backend to mark the objective as completed (or should this mutation be sent before the calls to the blockchain?), and after that redirect the user as we're doing now.
- Else, we show some error screen (maybe just the feedback bar) (do we just let the actions that got completed be completed, and do nothing else?)

**Comment by lucca65** [comment]
+1 for the flow so far! I think it should work, the same!

> If every action is completed successfully, we send a mutation to the backend to mark the objective as completed (or should this mutation be sent before the calls to the blockchain?), and after that redirect the user as we're doing now.

It should be called after its completed, I think this way there is less room for error

> we show some error screen (maybe just the feedback bar) (do we just let the actions that got completed be completed, and do nothing else?)

Yeah, maybe we can have a retry button, with a simple list with the names of pending actions for archive

**Comment by juramos-2020** [comment]
@NeoVier  In this case you will make these implementations of the modal and progress screen while Rafa creates the animation right?

**Comment by NeoVier** [comment]
@juramos-2020 yes! The only other thing we need is this:

>  maybe we can have a retry button, with a simple list with the names of pending actions for archive

In case something goes wrong when completing some of the actions

**Comment by NeoVier** [comment]
@juramos-2020 I'm implementing the loading screen right now, and I think there might be some contrast/readability issues with the way we're displaying the loading text right now, because it shows up on top of the text from the objective's title:

![2021-07-06-105121_392x753_scrot](https://user-images.githubusercontent.com/39280468/124611774-24b84600-de48-11eb-9cec-a2bab7421718.png)

What do you think? Maybe we could extend the white background to be behind the whole thing?

**Comment by juramos-2020** [comment]
Ok @NeoVier 

> Yeah, maybe we can have a retry button, with a simple list with the names of pending actions for archive

I will do a proposal for this

> Maybe we could extend the white background to be behind the whole thing?

And this 😉👍

**Comment by juramos-2020** [comment]
Hi @lucca65  and @NeoVier 

I did some layout tests and I kept thinking about "a simple list with the names of pending actions for archive". There are goals with many actions, and there are actions with very big names. This would make this simple loading modal turn into a huge page full of information, which could be confusing for the user.

For this reason I propose to have a single text talking about the error scenario, when an objective cannot be completed due to a failure to complete the action.

What do you think?

https://www.figma.com/file/nEPG6Dkns8hDVCudVUTEzc/Dashboard?node-id=2820%3A9848

**Comment by juramos-2020** [comment]
> Maybe we could extend the white background to be behind the whole thing?

and here is: https://www.figma.com/file/nEPG6Dkns8hDVCudVUTEzc/Dashboard?node-id=2759%3A10097

😉👍

**Comment by NeoVier** [comment]
Looks amazing @juramos-2020 :heart_eyes:

**Comment by juramos-2020** [comment]
I made this proposal considering that when clicking on "try again" the action of completing the objective will be undone and the user will be directed to the previous screen with the objective still incomplete.

I need to confirm with you if this behavior will be possible 😅

**Comment by NeoVier** [comment]
Yes, that's exactly right. The objective is only marked as complete if/when every single action inside that objective is marked as complete. If one of the actions fails, the objective is not completed

**Comment by juramos-2020** [comment]
if it really is necessary to inform the action that could not be completed so that the "try again" action is only applied to it, I can enter eg "action 2/3 could not be completed" and put a link next to " try again" 

What do you think @NeoVier @lucca65

**Comment by lucca65** [comment]
I think we should show the ones that failed, without redirects

**Comment by NeoVier** [comment]
@lucca65 if an action fails, should we un-complete the ones that didn't fail? I think we could just leave the ones that were successful as completed (which would make the ones with errors to be not completed), and if the user wants to see which ones failed, they can just go to the objectives page and see which ones aren't completed. My reasoning is, if the user wants to complete the objective, they probably don't really care specifically which action was completed or not, they just want to know if there were any errors or not

**Comment by lucca65** [comment]
> if an action fails, should we un-complete the ones that didn't fail?

no, we are not trying to atomize the operation, only make sure we make the blockchain limitations more easy to handle

**Comment by juramos-2020** [comment]
Here is

@lucca65  @NeoVier 

from what I understand, the second option would be better due to some limitation of the system, correct?

https://www.figma.com/file/nEPG6Dkns8hDVCudVUTEzc/Dashboard?node-id=2838%3A10762

**Comment by NeoVier** [comment]
@juramos-2020 both options are doable... I prefer the one on the left, because of this:

> if the user wants to complete the objective, they probably don't really care specifically which action was completed or not, they just want to know if there were any errors or not

I agree with you that some actions might have a long name, and some objectives might have a lot of actions. This modal can become very polluted in those cases if we were to show which ones failed, so I like the option to "Retry all" from the first option (and I also just think the first one looks amazing, it's simple and straight to the point). The only thing is, if we go with the first option, I think the "I will try again" button should link to some other page... it might be confusing if it links back to the editor page, users might not be sure if anything happened at all. Maybe we could link to `/community/objectives` or `/community`?

**Comment by juramos-2020** [comment]
when clicking on "try again" the process could not go back to the beginning?

https://www.figma.com/file/nEPG6Dkns8hDVCudVUTEzc/Dashboard?node-id=2758%3A9570

**Comment by NeoVier** [comment]
It could. I meant the "I will try later" button :sweat_smile:

**Comment by juramos-2020** [comment]
In this case I don't see a problem with the user going back to the previous screen.

https://www.figma.com/file/nEPG6Dkns8hDVCudVUTEzc/Dashboard?node-id=2744%3A9174

Because the modal itself is already reporting that there was an error in completing the objective due to failure to complete some actions.

**Comment by NeoVier** [comment]
Maybe it's the text on the button that's throwing me off... If the user clicks on "I will try later" (instead of immediately retrying), I assume they want to go do something else right now, and after some time come back and try again. In that case, it doesn't make sense to show the objective editor page, just for the user to click on "Back" (which can be hard to reach for on mobile) or go to the dashboard or whatever.

Also keep in mind some users don't read stuff, they just click on buttons and then don't know what happened

**Comment by juramos-2020** [comment]
hum... got it.

in this case I think we could direct to this screen where he could see and analyze other goals:

https://www.figma.com/file/nEPG6Dkns8hDVCudVUTEzc/Dashboard?node-id=2744%3A8700

**Comment by lucca65** [comment]
@juramos-2020 

tem um trecho no Figma que me chamou atenção, não sei se foi um comentário desatualizado ou algo que foi entendido errado, vou tentar esclarecer de qualquer forma que acho que pode ajudar 

> Essa proposta seria adequada se:  1 - Ao clicar em “Try again” o sistema conseguisse refazer todas as analises das ações e aprova-las de uma única vez.
2 - Ao clicar em “I will try later” o sistema conseguisse retornar a página anterior para que o usuário possa refazer o processo de marcar o objetivo como completo.  

Esse "Try again" seguido de "sistema refazer analise" não faz sentido. Arquivar um objetivo não envolve nada com analise das ações. O fluxo de análise -- de voto, tem a ver com reivindicações, estruturas criadas A PARTIR de uma ação. O sistema **não vota por ninguém, nem automatiza votos**, e deve permanecer assim.

Essa funcionalidade que estamos falando aqui é o arquivamento dos objetivos e de suas ações. Um objetivo é o propósito da comunidade. É a forma com que o dinheiro é criado dentro da comunidade. Ao arquivar um objetivo, há um senso de que um ciclo foi concluído e que as ações já foram. Toda vez que um objetivo for fechado, suas ações (ou seja, coisas que se faz para atingir esse objetivo) devem ser fechadas TODAS. Veja que isso não é falar que as reivindicações devam ser modificadas, ou aprovadas nesse momento.

**Comment by lucca65** [comment]
Então, revisando: Essa tela que estamos falando precisa, ao arquivar um objetivo, ir em uma ação por vez e completá-la. Para que o usuário não tenha que fazer isso ele mesmo, nós estamos dando a chance disso ficar mais fácil. Não é automático, tem que fazer uma a uma. 

Randomicamente, uma desses arquivamentos DE AÇAO pode falhar, e por tanto, precisa ir de novo. Não dá pra tentar de novo depois ou mais tarde. Tem que ser ali e agora. 

Inclusive @NeoVier me pergunto se a gente deve mesmo pedir o click do usuário pra fazer isso, no max podemos tentar de novo e mostrar pra ele. Em caso de erro depois de algumas tentativas, mostramos o erro e enviamos pro Sentry (assim a gente sabe sem o admin da comunidade avisar)

Uma pena a gente estar dando tanta volta nisso pessoal, eu poderia ter sido mais claro.

**Comment by lucca65** [comment]
Minha sugestão de como devemos prosseguir:

@NeoVier com os designs que temos, podemos fazer td. Progress bar que fica ali até terminar td, se não rolar na primeira tentativa tenta mais 3, se ainda sim não rolar, manda pro sentry e diz pro usuário que deu td certo. Ve se o Sentry loga isso direitinho pra gente alterar manualmente se for preciso de alguma forma, vamos observar como fica

@juramos-2020 Do design ainda não temos nada relativo ao que a Karla mencionou ali em cima, esse é um momento especial pra comunidade. 

1. Objetivos completados pq não fazem mais sentido são uma boa oportunidade pra revisar as decisões do passado e pq não faz mais sentido
2. Objetivos que foram concluídos com sucesso precisam ficar marcados de alguma maneira na plataforma. Nem que seja com uma tela de comemoração na hora que tudo acabar. 

Isso pode ficar num backlog pra essa issue não se arrastar mais, se assim vocês preferirem minha orientação é abrir uma nova issue aqui nesse repositório ou no Improvement proposals, lugar de discussão de funcionalidades mais a longo prazo. https://github.com/cambiatus/improvement-proposals/

**Comment by NeoVier** [comment]
> Progress bar que fica ali até terminar td, se não rolar na primeira tentativa tenta mais 3, se ainda sim não rolar, manda pro sentry e diz pro usuário que deu td certo. Ve se o Sentry loga isso direitinho pra gente alterar manualmente se for preciso de alguma forma, vamos observar como fica

Certo, vou experimentar com o Sentry e ver como vai ficar

> Isso pode ficar num backlog pra essa issue não se arrastar mais

+1, essa issue tá demorando (bem) mais do que eu esperava e estamos correndo em círculos... Vou abrir uma issue no improvement-proposals pra podermos discutir melhor, visto que essa é uma funcionalidade que parece bastante importante pra nossa plataforma
