### ISSUE TITLE
Confirmation of purchase

### ISSUE THREAD

**Issue by natillasol** [cambiatus/frontend#53]
**Is your feature request related to a problem? Please describe.**
Currently, when you press buy, it instantly goes back to offers and the user is not sure of what happened... what the product purchased? How much was I charged? What is my balance now?

**Describe the solution you'd like**
A confirmation message that responds to the questions above. 

**Describe alternatives you've considered**

Also, we might want to consider an extra step in the purchase in order to avoid error. Like in any other service, you are always asked to confirm if you REALLY want to purchase the products that you haev in your basket. 

**Additional context**
<img width="1440" alt="Screen Shot 2019-11-13 at 13 19 26" src="https://user-images.githubusercontent.com/57719975/68796312-3ff19480-0618-11ea-8341-f32a97f2f691.png">

**Comment by lucca65** [comment]
@natillasol I feel that this should be addressed by the design team first. We haven't implemented the new designs for those screens too, so it might be that it is already implemented. Regardless I will close this issue for now and redirect this to them!
