### ISSUE TITLE
Claim modal

### ISSUE THREAD

**Issue by victorgdev** [cambiatus/frontend#536]
**What we have**
Specific page for claims `dashboard/analysis/objectives/:objective_id/action/:action_id/claim/:claim_id`

**Proposal**
Implement a modal in the `dashboard/analysis` page that will display `/objectives/:objective_id/action/:action_id/claim/:claim_id`, and would substitute the specific `/objectives/:objective_id/action/:action_id/claim/:claim_id` page.

[Here is the Figma link](https://www.figma.com/file/LTaoCg6DKv6EPQAlt6Fngs/New-analysis-page?node-id=64%3A1413&fuid=858359178594905230)

**Why**
Enhance the app's navigating-through-claims experience

**How**
Implementing a modal that would display the list of claims a community have.

**Additional context**
N/A

**Comment by NeoVier** [comment]
@victorgdev actually, we're keeping `dashboard/analysis`. What we're removing is `/objectives/:objective_id/action/:action_id/claim/:claim_id`, which is the page for a specific claim. That claim will now be shown in a modal. I think it's easier to understand if you actually see what we're doing, so [here is the Figma link](https://www.figma.com/file/LTaoCg6DKv6EPQAlt6Fngs/New-analysis-page?node-id=64%3A1413)

**Comment by lucca65** [comment]
@victorgdev don't forget that we have some new design elements on this page! check figma
