### ISSUE TITLE
Profile information popup

### ISSUE THREAD

**Issue by NeoVier** [cambiatus/frontend#537]
**Is your feature request related to a problem? Please describe.**
When you see a user image, you need to click on it to go to the user's profile page to be able to see all their information

**Describe the solution you'd like**
Have some basic information more easily accessible

**Describe alternatives you've considered**
Use a modal/popup to show the user's information. See it for [Mobile](https://www.figma.com/file/LTaoCg6DKv6EPQAlt6Fngs/New-analysis-page?node-id=2%3A956) and [Desktop](https://www.figma.com/file/LTaoCg6DKv6EPQAlt6Fngs/New-analysis-page?node-id=2%3A956).

**Additional context**
This is specially useful in the analysis page, so that validators can know who is submitting a specific claim

**Comment by lucca65** [comment]
honestly can't wait for this one!

**Comment by NeoVier** [comment]
You might be pleasantly surprised today then :eyes:

**Comment by lucca65** [comment]
👀 👀 👀 👀
