### ISSUE TITLE
Show Token data on the community page

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#540]
**What we have**
Currently we show lots of information on the community page: members, transfers, claims, orders, products. 
![Captura de Tela 2021-05-24 às 16 02 21](https://user-images.githubusercontent.com/1082127/119395101-6ed6d500-bca9-11eb-9718-ed1cef8bce32.png)

**Proposal**
We could include more info related to the token that the community uses. Here is a sample with some data: 
https://www.figma.com/file/268fiH2aIOgBMSKYybffuJ/About?node-id=0%3A1

We can add even more info!
![Captura de Tela 2021-05-24 às 16 06 00](https://user-images.githubusercontent.com/1082127/119395477-f15f9480-bca9-11eb-9e03-33b6ed75800d.png)
(we can ask for directions from the design team if needed)

**Why**
Communities already asked us about this information, also we could do a little improvement on those stats CSS/ look and feel

**How**
The implementation is simple enough, we can do a direct call to the blockchain to query that data. Here's a `cleos` example:

```sh
cleos -u https://muda.cambiatus.io get table cambiatus.tk MUDA stat
```

**Additional context**
N/A

**Comment by rafachadud** [comment]
@lucca65 I updated the Figma with minimum supply. 

![Screenshot 2021-05-27 at 17 42 42](https://user-images.githubusercontent.com/67650032/119856375-f1ae9880-bf12-11eb-9649-76a005a6f2ba.png)
