### ISSUE TITLE
Show balance when transferring

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#543]
**Is your feature request related to a problem? Please describe.**
Its really annoying on our monthly claims, I have to recheck my balance every time 

**Describe the solution you'd like**
Just show the balance that we already have on the transfer form

**Describe alternatives you've considered**
maybe it can be a modal, but I think the problem would persist even if we do it 🤷

**Comment by UdattaChowdhury** [comment]
Would like to work on this issue, can you assign it to me? Along with that can you explain what exactly is needed.

**Comment by lucca65** [comment]
hey @UdattaChowdhury what a nice surprise! 

Yes, please go ahead, you can use the designs of [this page](https://github.com/cambiatus/frontend/blob/4b1126830d3f5342affeb0a65b613afecab08421/src/elm/Page/Shop/Viewer.elm#L518-L521) to display the balance

**Comment by UdattaChowdhury** [comment]
Sure, please assign it to me.

**Comment by UdattaChowdhury** [comment]
error frontend@1.9.1: The engine "node" is incompatible with this module. Expected version "14.8.0". Got "14.16.0"
error Found incompatible module.

I am getting this error I don't know why.

**Comment by lucca65** [comment]
you are using a different version of node than the project needs. install the correct version and it should go away.

you can use **n** https://www.npmjs.com/package/n
