### ISSUE TITLE
Improve sentry error reporting

### ISSUE THREAD

**Issue by NeoVier** [cambiatus/frontend#552]
**What we have**
We log a lot of errors to sentry that aren't relevant, which makes it so actual relevant issues get buried below these, making it harder to know if there's actually something wrong with the app or not. At the time of this writing, out of the top 6 most recurring events, 4 are related to DOM manipulation, with over 125k combined events.

**Proposal**
Solve or suppress the most recurring issues, depending on whether it's worth it to fix them or not

**Why**
If we only have relevant issues, we can do a better job debugging with sentry, and actually use it correctly. It'll make our lives way easier in regards to checking the health of our app

**How**
N/A, depends on each issue

**Additional context**
Brought up by @lucca65 on Slack

**Comment by muguika** [comment]
it would be fantastic also to make the titles or descriptions as "readable" for community builders as possible... so when a community reports to us a problem, we could quickly check what error is happening and help them accordingly.

**Comment by NeoVier** [comment]
+1 on nice error names (we're using Elm after all, famous for it's error messages!), but we should still have descriptions/breadcrumbs that point to where it happened in the code so it's easier for us to fix it

**Comment by lucca65** [comment]
One case of bad usage of sentry:

https://sentry.io/organizations/cambiatus/issues/2512681435/?project=1480468&query=is%3Aunresolved

this error is shown but we cannot know the query that generated it!
