### ISSUE TITLE
Standardize all inputs

### ISSUE THREAD

**Issue by NeoVier** [cambiatus/frontend#554]
**What we have**
We have a (recently) growing `View` module, with useful input components, with a bunch of configurations, that make every input field be standardized. We also have a lot of non-standard `Html.input` fields, which have to be styled individually. That makes it a lot harder for inputs to look the same.

**Proposal**
Create an elm-review rule that forbids the use of functions like `Html.input` (maybe there are others we should forbid? idk) outside of the `View` directory

**Why**
This would make it so every input is covered, and it's a lot easier than hunting them down one by one manually. Also, if we want to change some input style globally, we would have a single place we need to change.

**How**
Use a [moduleVisitor](https://package.elm-lang.org/packages/jfmengels/elm-review/latest/Review-Rule#withModuleVisitor) to check if the module name starts with `View` and an [importVisitor](https://package.elm-lang.org/packages/jfmengels/elm-review/latest/Review-Rule#withImportVisitor) to check for all the imports. From there, we can use an [expressionVisitor](https://package.elm-lang.org/packages/jfmengels/elm-review/latest/Review-Rule#withExpressionEnterVisitor) to check for usages of `input` (the `expressionVisitor` docs have a very similar example to the one this issue proposes)

**Additional context**
N/A

**Comment by NeoVier** [comment]
@lucca65 what do you think about this? I think it could be really useful, but it also might be too harsh, idk

**Comment by lucca65** [comment]
actually this is an amazing solution. Now this is **actually** using Elm types to our advantage

I love this idea, compiler will tell us about all incorrect occurrences

we could add this to husky and other git hooks too (and of course our github action) to prevent PRs to submit code like this 

Bro I love this and i do think this would be a very good first issue for a developer that wants to start to get familiar with Elm!

**Comment by NeoVier** [comment]
> we could add this to husky and other git hooks too (and of course our github action) to prevent PRs to submit code like this

We already run elm-review on the pre-push hook, so no extra work needed! Just gotta create that rule :smile:

**Comment by NeoVier** [comment]
@lucca65 I feel like this could be a general rule, and other people might find it useful as well. Is it ok if I publish it as a package under my name?

**Comment by lucca65** [comment]
I agree, please do it!
