### ISSUE TITLE
Add alert on My Claims page

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#556]
**Is your feature request related to a problem? Please describe.**
Some users do multiple claims, this is a problem as multiple claims make the validator work way harder

**Describe the solution you'd like**
https://www.figma.com/file/LTaoCg6DKv6EPQAlt6Fngs/New-analysis-page?node-id=64%3A1073

**Comment by NeoVier** [comment]
@lucca65 I assume that "boas práticas da Comunidade" is a link, right? Is it community specific link (if so, where is it coming from?), or is it supposed to be a new route?

**Comment by lucca65** [comment]
@heltonlr @juramos-2020 @rafachadud do you know where it should go? its not clear on Figma

**Comment by heltonlr** [comment]
The idea was create a page about that on webflow, but the content doesn't exist yet. We can begin without that link.
