### ISSUE TITLE
Handle blockchain erros on Claim page

### ISSUE THREAD

**Issue by natillasol** [cambiatus/frontend#56]
**Is your feature request related to a problem? Please describe.**

When I verify someone's action, the app just remains in the same page, there is no confirmation that the verification has been done.

**Describe the solution you'd like**
A confirmation that the verification has been done, and that after the app takes me to a page in which pending verifications are shown, or if there is no verifications it shows: "You don't have any verifications pending"

**Describe alternatives you've considered**
See above

**Additional context**
<img width="1439" alt="Screen Shot 2019-11-14 at 08 10 22" src="https://user-images.githubusercontent.com/57719975/68864638-15a2e400-06b7-11ea-836e-ab2b3f393505.png">

**Comment by lucca65** [comment]
The reason for that is that this pages don't handle failed push transaction. We should implement this workflow so the user gets feedbacks that something went wrong

**Comment by zacck** [comment]
@lucca65  Where in particular is the failed transaction not catered for?

**Comment by lucca65** [comment]
it only logs failed transactions, there is no message like in the community page

**Comment by zacck** [comment]
@lucca65  awesome thanks, I needed to know where cool will do the error handling  ...
