### ISSUE TITLE
Add "Analyzed" and "Needs your vote" tabs on analysis page

### ISSUE THREAD

**Issue by NeoVier** [cambiatus/frontend#560]
**What we have**
On the analysis page, there is a list of all claims that you have voted and that still need your vote

**Proposal**
We should have separate tabs so it's easier for the validator to see what claims they still need to vote on

**Why**
Make it easier and more organized for validators

**How**
There is already a `claimsAnalysis` query, used in the dashboard, that just shows the claims the validator hasn't voted on yet. The `claimsAnalysisHistory` query only shows the ones the validator has voted yet (still needs to be tweaked on the backend). We should implement [these designs](https://www.figma.com/file/LTaoCg6DKv6EPQAlt6Fngs/New-analysis-page?node-id=230%3A0)

**Additional context**
N/A

**Comment by lucca65** [comment]
actually its not really like that...

check those designs: https://www.figma.com/file/LTaoCg6DKv6EPQAlt6Fngs/New-analysis-page?node-id=230%3A0

We have now two tabs: "Need you Vote" and "Analyzed". The first one is already done and its used on `/dashboard`. Analyzed is actually the one we have right now but a little different, because it will no show pending votes (it does right now). We can fix this on the backend later as this will not change much for the frontend

**Comment by NeoVier** [comment]
Corrected title and description accordingly

**Comment by NeoVier** [comment]
@rafachadud @juramos-2020 in these designs, what do you think of having the ordination info (descending/ascending) be on the button itself? (Instead of it saying "Sort by", just say "Crescending"/"Ascending" or something like that, with a corresponding icon). I think it makes more sense this way, since we only have two options, and it's always one or the other. What do you think?

**Comment by juramos-2020** [comment]
Hi @NeoVier 

Clicking in "order by" a modal will be opened with the sorting options.

https://www.figma.com/file/LTaoCg6DKv6EPQAlt6Fngs/New-analysis-page?node-id=5%3A620

This component was created with shoppoing in mind, in which we will have other sorting options

Ex:
* highest date
* lowest date
* biggest price
* Lowest price

If we put only "Crescending"/"Ascending" this component will not serve the shopping scenario with the other ordering options.

**Comment by NeoVier** [comment]
We can have different things on the shop and on the analysis page. I don't see why we should add an extra step for the user if we only have 2 options :thinking: .

It would look the same on the analysis page and the shop, sure, but I don't think it's worth it - the shop doesn't even look like that yet.

But anyway, it's up to you. If you think looking consistent is more important, no problem, just let me know!

**Comment by rafachadud** [comment]
@NeoVier , @juramos-2020

It makes sense to keep it "Ascending" "Descending" order, as we have now in the analysis page. 


![IMG_5182](https://user-images.githubusercontent.com/67650032/121781849-faf06400-cba6-11eb-8634-fd74f99f6a8e.PNG)

**Comment by rafachadud** [comment]
By the way @NeoVier, the User field has a weird shadow, can you take a look at it?

**Comment by NeoVier** [comment]
@rafachadud what environment is that (staging, demo, prod)? Also, what browser are you on?

**Comment by rafachadud** [comment]
That's Muda's community, I believe prod (?), Safari browser

**Comment by rafachadud** [comment]
@NeoVier, the button updated is here 
https://www.figma.com/file/LTaoCg6DKv6EPQAlt6Fngs/New-analysis-page?node-id=318%3A3299

@juramos-2020, I kept your version as well, and we can put it in the next round when the shop is also redesigned with the filters. 👯

**Comment by NeoVier** [comment]
> That's Muda's community, I believe prod (?), Safari browser

Yep, that's prod, I'll take a look and fix it :smile:

**Comment by NeoVier** [comment]
@rafachadud we still need the filters though, right? Other than the sorting order, we also can select the claimer and claim status: https://www.figma.com/file/LTaoCg6DKv6EPQAlt6Fngs/New-analysis-page?node-id=2%3A186.

**Comment by rafachadud** [comment]
@NeoVier oh yeah, I forgot those hehe 

Design updated 
https://www.figma.com/file/LTaoCg6DKv6EPQAlt6Fngs/New-analysis-page?node-id=230%3A0

**Comment by NeoVier** [comment]
Awesome @rafachadud :fire: :rocket:

**Comment by NeoVier** [comment]
@rafachadud @juramos-2020 [this yellow rectangle](https://www.figma.com/file/LTaoCg6DKv6EPQAlt6Fngs/New-analysis-page?node-id=2%3A1861) is only related to the ordination modal, right? We're still going with the filters modal, right?

**Comment by juramos-2020** [comment]
that's right @NeoVier is only related to the ordination modal. 😉👍
