### ISSUE TITLE
Multiple selection of claims

### ISSUE THREAD

**Issue by juramos-2020** [cambiatus/frontend#564]
**What we have**
A page with all the claims to analyze

**Proposal**
Add the claims selector option so that the Administrator can select multiple options at the same time, gaining agility in completing the claims analysis

**Why**
This feature is to help administrators select multiple claims and be able to approve or disapprove at once.
Because administrators currently analyze claims one by one. Making this task take longer to complete

**How**
A selector must be added next to each claim that is pending analysis.

**Additional context**
N/A

**Comment by lucca65** [comment]
@juramos-2020 can you edit the description answering the questions after the titles? This will help us get the context across! I know this is extra work but having good text communication is crucial for remote only teams! 💪

**Comment by juramos-2020** [comment]
Oh sorry. Yes, I will do this. 💪

**Comment by NeoVier** [comment]
@juramos-2020 do we have any designs for this already? We'll need to show a progress indicator just like in #524 (it could even be the same component), to show the progress on each vote

**Comment by juramos-2020** [comment]
Hi @NeoVier 

it was decided in our last rice session that we will wait to implement "Claim no Modal" and analyze user behavior with this implementation. After that we will reassess the necessity of implementing the selector or not.

**Comment by lucca65** [comment]
in this case, let’s close this issue, we can open a new one or reopen this if needed
