### ISSUE TITLE
Improve transfer list

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#579]
**What we have**
A very old, not community aware transfer list. We need to update that

**Proposal**
Improve our transfer view to follow the new design: https://www.figma.com/file/47BEsGEMSWfhTm3zC0ugyA/Ticolones-version?node-id=1%3A421

**Why**
As an effort to improve visibility and as a preparation for the community admin balance tool

**How**
N/A

**Comment by NeoVier** [comment]
@lucca65 is this a replacement for #237?

**Comment by lucca65** [comment]
No, but we can see it as "part of". Timeline will require us to do something similar to what we did on notifications, where we could have several elements of different types. Here we will implement only transfers. The main reason to do this is for the "check balance tool" for admins, which will need a new API. We are due to update transfers, as it one of those old parts of the app we don't touch in a while, it isn't even aware of our change to be multi community. So we can update this and use the same query on that tool, while we give a little something for our regular users!

**Comment by NeoVier** [comment]
@rafachadud @juramos-2020 On the dashboard, we have a list of transfers that the user is a part of. This design shows a filter button that only has the options "All", "Transferred" and "Received". Now we have some new filters we can use:
- date
- direction (whether the current user sent or received the transfer)
- the other user participating on the transfer

Should we include these filters here on the Dashboard? I like the idea of using a similar modal to the one we used in #560, what do you think?

**Comment by NeoVier** [comment]
ping @juramos-2020 @rafachadud

**Comment by juramos-2020** [comment]
Hi @NeoVier sorry for the delay.

I think it makes perfect sense for us to maintain the behavior of opening a modal for these filter cases, as we managed to maintain consistency in the application.

can you do this on backend or will you need a screen?

A question: do these transactions refer to all transactions that the user has within all the communities he is part of? Or are transactions that only take place within the community he is currently logged in to?

**Comment by NeoVier** [comment]
> can you do this on backend or will you need a screen?

The backend part is already done, and it's integrated into the frontend as well. The only thing left is a screen/modal for displaying the filters. I've implemented a draft while implementing the feature, you can see it on the [Dashboard here](https://deploy-preview-587--angry-wing-8fcdd0.netlify.app/dashboard), when you click "filters" on "My timeline". You can see all the options there (date, transfer direction and other user). I think it's looking a lot like the rest of the app and it's probably fine like that, but if you want to change something, feel free.

> A question: do these transactions refer to all transactions that the user has within all the communities he is part of? Or are transactions that only take place within the community he is currently logged in to?

They're only related to the community the user is currently logged in to (if they're in the Cambiatus community, it only shows transfers from the Cambiatus community)

**Comment by juramos-2020** [comment]
> They're only related to the community the user is currently logged in to (if they're in the Cambiatus community, it only shows transfers from the Cambiatus community)

wonderful

> the other user participating in the transfer

I just didn't identify this search in the modal. The others are in accordance with the design
