### ISSUE TITLE
After approving a claim, the same claim remains in dashboard to be approved. 

### ISSUE THREAD

**Issue by natillasol** [cambiatus/frontend#58]
**Describe the bug**
After approving a claim, the same claim remains in dashboard to be approved. 

**To Reproduce**
Go to 'borboins.cambiatus.io
Click on 'Activities for your analysis'
Click on "Approve"
Go back to Dashboard

**Expected behavior**
Previously approved claims, remain in dashboard

**Screenshots**
<img width="1440" alt="Screen Shot 2019-11-14 at 08 33 26" src="https://user-images.githubusercontent.com/57719975/68866261-c01c0680-06b9-11ea-9855-a8e2d5dd30d8.png">
<img width="1440" alt="Screen Shot 2019-11-14 at 08 34 03" src="https://user-images.githubusercontent.com/57719975/68866262-c01c0680-06b9-11ea-9c6f-40395ddcc2ef.png">
<img width="1440" alt="Screen Shot 2019-11-14 at 08 34 08" src="https://user-images.githubusercontent.com/57719975/68866264-c0b49d00-06b9-11ea-9127-704dd7043701.png">
<img width="1440" alt="Screen Shot 2019-11-14 at 08 34 16" src="https://user-images.githubusercontent.com/57719975/68866265-c0b49d00-06b9-11ea-88c3-001b2788389f.png">

**Cambiatus Env you are using**
borboins.cambiatus.io

**Comment by lucca65** [comment]
Fixed! This was happening because event-source was offline
