### ISSUE TITLE
Reorganize Token data

### ISSUE THREAD

**Issue by NeoVier** [cambiatus/frontend#583]
**What we have**
In the Cambiatus structure, we have two main entities/models: Community and Token. On the blockchain, they're completely separate. On the frontend, the Community is pretty well defined, but still has some stuff that's actually related to Tokens, and Tokens aren't very well defined.

**Proposal**
Differentiate everything that belongs to the Token from what belongs to the Community, and vice-versa.

**Why**
It'll be clearer for everyone in the project - we would have the same structure all around. As pointed out by @lucca65 during #580, Token data deals with currency, so we should have the most up-to-date information at all times, as opposed to the Community data, that doesn't necessarily need to be so updated.

**How**
Improve the `Token` module, and bring everything that relates to Tokens that is in the `Community` module there. We can take information on what should be where on the blockchain tables.

**Additional context**
There were some really interesting conversations in #494, and more recently in #580

**Comment by lucca65** [comment]
@NeoVier bro, can you review this?

**Comment by NeoVier** [comment]
The only thing vaguely related to tokens left on the `Community` module is the type alias `Balance`, which is arguably related to a `Community` as well. Since it's just a type alias, I think it's safe to keep it there anyway. Other than that, all token information is already under the `Token` module

**Comment by lucca65** [comment]
nice!
