### ISSUE TITLE
Create/use a standard way to deal with forms

### ISSUE THREAD

**Issue by NeoVier** [cambiatus/frontend#585]
**What we have**
Each page has its own strategy when dealing with forms. Some use one library, some use another library, some don't use any library... It's very non-standard

**Proposal**
Create (or use something ready) that allows us to deal with forms "universally". Some requirements I see as essential:
- Abstract and flexible enough so that we can use it everywhere on the app
- Possibility to change existing features or add new ones (we'll probably run into some edge cases that won't be foreseen by the solution)
- The library/solution shouldn't care about visuals. It should only handle the logic of inputs and validation
- Should have some way to do something like `Form -> ValidForm`
- Probably should be composable, so that we're able to do something like this (we could incorporate our existing `View.Form.*` components here):
```
initForm ...
  |> withField ...
  |> withField ...
```
(`withField` would need to (at least) pass in some `Html`, since **the view should be handled by the caller, and not by the form library**)

**Why**
It would make developing new screens that have forms way faster and easier, with less space for bugs. Also, it would make our code base even more uniform, which makes it easier to understand and expand.

**How**
I personally lean towards a custom solution, respecting the requirements mentioned above. [According to the Elm community](https://discourse.elm-lang.org/t/how-do-you-deal-with-forms/7354/3), this isn't a thing you can reliably do with a general library, and people usually use custom handlers. As you can see in that post, it seems like everyone else is also all over the place on dealing with forms.

**Additional context**
Popped up after having to fix an issue on a form (#584), introducing the functionality of scrolling to the first field with an error, which I don't think I've seen anywhere else on the app, but it's probably something we should do everywhere for better UX.

This could be very hit or miss, we must do this in a very good and general way, or else we might see ourselves just changing this library all the time to include edge cases

**Comment by lucca65** [comment]
+1 to this!

**Comment by NeoVier** [comment]
I've seen a lot of people on the Elm community recommend [hecrj/composable-form](https://package.elm-lang.org/packages/hecrj/composable-form/latest/), and I've recently tried it out on a [quick side project](https://github.com/NeoVier/mycontacts-frontend). I talk a little about my experience with it in the README of that project, but the main point I can see as not great is that we use custom types to build our input fields, and I think that works really well, providing extensible customization. That pattern doesn't look like it would work too well with this package. As an example, here's how it looks like to define a text field:
```elm
Form.textField
    { parser = Ok
    , value = .name
    , update = \name values -> { values | name = name }
    , error = always Nothing
    , attributes =
        { placeholder = "Name"
        , label = "Name"
        }
    }
```

This means we can't really add "dynamic" values, which don't need to be declared _every_ time, like we can in our app:

```elm
Input.init
    { label = translators.t "news.editor.field.time"
    , id = "time-input"
    , onInput = EnteredPublicationTime
    , disabled = form.isSaving
    , value = scheduling.selectedTime
    , placeholder = Nothing
    , problems = Maybe.map (translators.t >> List.singleton) scheduling.timeError
    , translators = translators
    }
    |> Input.withContainerAttrs [ class "w-full" ]
    |> Input.withType Input.Time
    |> Input.toHtml
```

All of this to say, I think we can have a really nice API if we follow some examples from `hecrj/composable-form` (having a "dirty" model and "parsed" model, using the `parser`, `value` and `update` fields, having a pipeline style to build forms), but we would probably have to bake our own version, which uses our own custom types, as I think this is very specific per app.

We could even start using something like [The (extensible records) Phantom Builder Pattern](https://www.youtube.com/watch?v=Trp3tmpMb-o) if we see fit (that's a great talk, by the way!)

**Comment by lucca65** [comment]
🎉
