### ISSUE TITLE
Make the PIN as hidden by default

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#589]
**What we have**
Today the default of the pin is to be shown, the user can toggle this to change to hidden

**Proposal**
Default the value to hidden

**Why**
To improve privacy

**How**
N/A

**Additional context**
Discovered during our Full Team session

**Comment by lucca65** [comment]
nice! this would be nice! If possible, can we have a full list of preferences? I'm thinking to persist some of them in our backend on https://github.com/cambiatus/backend/issues/172

**Comment by NeoVier** [comment]
Can't think of much else... Other than the language, maybe the timezone could be useful for sending emails at appropriate times? Not sure...

I think the PIN preference could be stored only in localStorage, no? The only other thing I can think of is search words, but idk how useful that would be on the backend
