### ISSUE TITLE
Objectives are not being created

### ISSUE THREAD

**Issue by natillasol** [cambiatus/frontend#59]
**Describe the bug**
After creating an objective, this does not show in the community page

**To Reproduce**
1. Go to 'borboins.cambiatus.io'
2. Click on 'communities'
3. Click on 'New Objective'
4. Write objective
5. Save
6. See error

**Expected behavior**
New objective is not created

**Screenshots**
<img width="1440" alt="Screen Shot 2019-11-14 at 08 44 25" src="https://user-images.githubusercontent.com/57719975/68867444-703e3f00-06bb-11ea-80ab-9234997732f3.png">
<img width="1440" alt="Screen Shot 2019-11-14 at 08 45 02" src="https://user-images.githubusercontent.com/57719975/68867445-703e3f00-06bb-11ea-8251-b194909151ea.png">

**Cambiatus Env you are using**
borboins.cambiatus.io

**Desktop (please complete the following information):**
OS: MacOS Catalina version 10.15.1
Browser: Firefox
Version : Quantum 66.0.3 (64-bit)

**Smartphone (please complete the following information):**
 - Device: LEG
 - OS: Android 7.0
 - Browser Chrome
 - Version  78.0.3904.96

**Comment by lucca65** [comment]
Event source was off in this env, fixed
