### ISSUE TITLE
Remove 256 characters limitation from Actions form

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#592]
**What we have**
Today we have 256 characters for the action description and on the validation with photo description

**Proposal**
Simply remove the limitation on those two fields

**Why**
The blockchain already clips the bigger part, and event-source can save it on Postgres normally

**How**
Just remove it!

**Additional context**
Discovered during our Full Team Session on 13 july

**Comment by victorgdev** [comment]
@lucca65 should the char counter be removed as well `View.Form.InputCounter.view shared.translators.tr 256 (getInput form.description)` ?

**Comment by lucca65** [comment]
not sure about that code snippet you sent, but no need for the counter
