### ISSUE TITLE
Add Sponsorship (PayPal)

### ISSUE THREAD

**Issue by NeoVier** [cambiatus/frontend#599]
**Is your feature request related to a problem? Please describe.**
We need more ways to fund our platform and our communities.

**Describe the solution you'd like**
Accept fiat payments, which will go partly to our communities and partly to us

**Describe alternatives you've considered**
We can use PayPal. The Natus project already does this, we can get inspired by that. The backend suport for this will come with cambiatus/backend#159

**Additional context**
N/A

**Comment by NeoVier** [comment]
@rafachadud @juramos-2020 do we have any designs for this already?

**Comment by juramos-2020** [comment]
Yes @NeoVier 
We have a design for this. 
@rafachadud  developed these screens and will share them with you.
I don't share it because I don't know if she needs to review something.

**Comment by rafachadud** [comment]
@NeoVier @juramos-2020, 

I did a brief review and it seems okay. 
[https://www.figma.com/file/8qgVAV2yFRE8ryzy3UPVJe/Support-the-Community?node-id=0%3A1]

However I do have questions @NeoVier,
1 - Can we set specific amounts on Cambiatus? 
2 - The standard account will be the Cambiatus PayPal, or we'll allow each community to have connect their own PayPal account?

And if you have any other comment/issue let me know. We did that before implementing PayPal in Natus, so I believe a lot was learned regarding the how-tos.

**Comment by NeoVier** [comment]
Thanks for the designs @rafachadud!

> Can we set specific amounts on Cambiatus?

Not sure I understand what you mean... Can you elaborate?

> The standard account will be the Cambiatus PayPal, or we'll allow each community to have connect their own PayPal account?

@lucca65 @muguika can you explain how the PayPal integration flow will work?

**Comment by rafachadud** [comment]
> > Can we set specific amounts on Cambiatus?
> 

I mean, can we allow the admins to set amounts ($5, $55, $10...), and time periods (monthly, yearly, one time...), or even both (eg. $5 monthly, $55 yearly, $10 one time...) directly on the Cambiatus app? So when the user clicks on "sponsor community" they can choose and then be redirected to the PayPal screen/flow. 

The way I designed, the community doesn't set any of those on Cambiatus app itself, but on PayPal, then they send Cambiatus their link already set.

**Comment by lucca65** [comment]
> @lucca65 @muguika can you explain how the PayPal integration flow will work?

The same way as Natus for this first version, you can grab more insight [here](https://github.com/cambiatus/natus.webapp/pull/31). Just receive a payment. This first version will not have a "back office" for community admins for now! Using https://natus.cambiatus.io may help!

**Comment by NeoVier** [comment]
Ok, so we will receive the payments directly to the cambiatus account, and from there manually transfer to communities, right?

Also in the "keep it simple" philosophy, I assume we should take any amount (as opposed to what @rafachadud suggested of having fixed amounts), at least in this first version, correct?

**Comment by lucca65** [comment]
I think the complexity of having presets is minimal, we can have them. But it could be like Natus, simply an input with some validations.

**Comment by NeoVier** [comment]
@rafachadud @juramos-2020 looks like [the donation flow linked on figma](https://developer.paypal.com/docs/paypal-payments-standard/integration-guide/checkout-exp-donate/) is deprecated/legacy... The recommended way of accepting payments seems to be the one Natus is using, with these kinds of buttons:

![2021-07-29-110242_560x254_scrot](https://user-images.githubusercontent.com/39280468/127505838-7b1a7067-6a7c-49ff-bbc6-bdd4971775cf.png)

We can do the same thing that's shown on Figma, just on our own modal, what do you think? Also, we can change the buttons styles according to [Paypal's style guide](https://developer.paypal.com/docs/platforms/checkout/reference/style-guide/), so they fit better on our design (for example, making the buttons pill-shaped, like our own buttons). Should we use the default buttons or should we tweak them?

**Comment by rafachadud** [comment]
@NeoVier we can use the pill shaped button :D 

Do you want me to update in the design or can you do it without it?

**Comment by NeoVier** [comment]
Nah, I don't think that's necessary, I can do it

**Comment by NeoVier** [comment]
@rafachadud In the [Sponsor your community modal](https://www.figma.com/file/8qgVAV2yFRE8ryzy3UPVJe/Support-the-Community?node-id=15%3A1390) there's a "Learn More about sponsoring communities" link. Do we have that link? If not, should we just not include that text for now, and add it once we have somewhere to link the user to?

**Comment by rafachadud** [comment]
@NeoVier we don't have the content for that yet. We can remove the text for now until we have it. :D

**Comment by NeoVier** [comment]
@rafachadud @juramos-2020 In the [about page](https://www.figma.com/file/8qgVAV2yFRE8ryzy3UPVJe/Support-the-Community?node-id=13%3A663):

- Do we have content for the "Why sponsor {{community}}?" link? If so, where should it link to?
- How should the new cards ("Our Supporters" and "Sponsor {{community}}") look on larger screens? I think the buttons might look too wide if we just stretch them to fill all the width (see image below). Or do you think that's fine?

![image](https://user-images.githubusercontent.com/39280468/128522114-5e2f21ec-efaf-4601-8066-d7b30b093fd1.png)

**Comment by juramos-2020** [comment]
hi Henry.  Regarding the link, I don't think we have that content yet.  I'll check with Luiz 😉👍.  about the size of the card, I will think of a proposal to improve this appearance 😉👍

**Comment by juramos-2020** [comment]
For now and not to delay delivery.  What do you think about the Our sponsor card being next to the Verdes Sponsor card?

**Comment by NeoVier** [comment]
The only problem is that the "Our sponsors" card is much taller than the other:
![image](https://user-images.githubusercontent.com/39280468/128536389-aba12ba2-cade-433a-b821-85caf795e511.png)

Maybe we could include some art below the "Sponsor Verdes" card to compensate that though, idk...

We don't really need to hurry on this, there are some missing things from the backend which might take a while to get ready and integrated with the frontend

**Comment by juramos-2020** [comment]
wonder then.  I will work on a proposal for this 😉👍
