### ISSUE TITLE
Actions are not being created

### ISSUE THREAD

**Issue by natillasol** [cambiatus/frontend#60]
**Describe the bug**
After creating an action, this does not show in the community page

**To Reproduce**
1. Go to 'borboins.cambiatus.io'
2. Click on 'communities'
3. Click on objetive
4. Click on create new action
4. Write action
5. Click on create 
6. Click on objetive (in which you created action)
7. See error

**Expected behavior**
New action is not created

**Screenshots**
<img width="1440" alt="Screen Shot 2019-11-14 at 08 55 02" src="https://user-images.githubusercontent.com/57719975/68868104-8993bb00-06bc-11ea-80af-01da15b452f8.png">
<img width="1440" alt="Screen Shot 2019-11-14 at 08 54 52" src="https://user-images.githubusercontent.com/57719975/68868107-8993bb00-06bc-11ea-8055-50762ed41c67.png">

**Cambiatus Env you are using**
borboins.cambiatus.io

**Desktop (please complete the following information):**
OS: MacOS Catalina version 10.15.1
Browser: Firefox
Version : Quantum 66.0.3 (64-bit)

**Smartphone (please complete the following information):**
 - Device: LEG
 - OS: Android 7.0
 - Browser Chrome
 - Version  78.0.3904.96

**Comment by lucca65** [comment]
Fixed! This was happening because event-source was offline
