### ISSUE TITLE
Show celebration when completing objective

### ISSUE THREAD

**Issue by NeoVier** [cambiatus/frontend#603]
**Is your feature request related to a problem? Please describe.**
As per cambiatus/improvement-proposals#44, we need to celebrate when a community completes an objective.

**Describe the solution you'd like**
Some celebration screen/animation to show when an objective is completed.

**Describe alternatives you've considered**
@rafachadud created [an animation screen](https://www.figma.com/file/nEPG6Dkns8hDVCudVUTEzc/Dashboard?node-id=2877%3A10267) to show.

**Additional context**
Next step after #524, one step towards cambiatus/improvement-proposals#44

**Comment by lucca65** [comment]
"as per ... we need to celebrate" lol 😂

**Comment by NeoVier** [comment]
Lol wording can be hard sometimes :sweat_smile: :rofl:

**Comment by lucca65** [comment]
@juramos-2020 no hurry, but just to keep in mind!
