### ISSUE TITLE
Close modal when pressing Esc

### ISSUE THREAD

**Issue by NeoVier** [cambiatus/frontend#618]
**What we have**
We already close the modal if the user clicks out of it.

**Proposal**
Close the modal when the user presses Esc.

**Why**
Better accessibility, it's kind of expected to happen. Also, it would mean we wouldn't need to listen for all key presses on LoggedIn, making for less spamming on the debug console.

**How**
Listen for key presses, figure out if it's Esc, and call the close Msg.

**Additional context**
N/A

**Comment by NeoVier** [comment]
We should also try to [trap focus](https://css-tricks.com/a-css-approach-to-trap-focus-inside-of-an-element/) inside modals

**Comment by lucca65** [comment]
damn, yes please!! 🤤
