### ISSUE TITLE
Transfers are not reflected in receiver's account

### ISSUE THREAD

**Issue by natillasol** [cambiatus/frontend#62]
**Describe the bug**

Tried sending BOR from the admin account to nataliaborbo and nataliasolan account. The balance in the admin account reflects the transfer, however, it the receiver does not get the BOR.

NOTE that when nataliasolan send BORs to admin, it DOES reflect the transfer, but it does not show in "recent transfers"

**Comment by lucca65** [comment]
Fixed! This was happening because event-source was offline
