### ISSUE TITLE
BOR new account did not get 5000 BOR

### ISSUE THREAD

**Issue by natillasol** [cambiatus/frontend#64]
**Describe the bug**
New borboin accounts are supposed to receive 5000 BOB when these are created. However, I created a new account leokeagsolan  and leosolankeag which did not receive it. 

**To Reproduce**
Create new user

**Expected behavior**
balance will be on 0 BOR

**Screenshots**

<img width="1440" alt="Screen Shot 2019-11-14 at 10 02 57" src="https://user-images.githubusercontent.com/57719975/68874050-2d359900-06c6-11ea-8997-339cc097b4b0.png">

![WhatsApp Image 2019-11-14 at 10 06 31](https://user-images.githubusercontent.com/57719975/68874278-8f8e9980-06c6-11ea-81cd-e53bf917e1a1.jpeg)

**Cambiatus Env you are using**

borboins.cambiatus.io

**Desktop (please complete the following information):**
OS: MacOS Catalina version 10.15.1
Browser: Firefox
Version : Quantum 66.0.3 (64-bit)

**Smartphone (please complete the following information):**
 - Device: LEG
 - OS: Android 7.0
 - Browser Chrome
 - Version  78.0.3904.96

**Comment by lucca65** [comment]
This is actually another problem, the current community page don't have configurations for invitation reward. This means that everytime the community is edited it makes the reward 0 as it is de default value. Closed in favor of #66
