### ISSUE TITLE
Mudar ordenação padrão das reinvidicações

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#645]
**What we have**
Atualmente temos a ordenação padrão como `DESC` nas páginas de claim (`/dashboard`, `/dashboard/analysis` e `/profile/${user}/claims`) 

**Proposal**
Mudar a ordenação para que fique por padrão para `ASC`

**Why**
Isso pode deixar claims mais antigas tenderem a ficarem esquecidas, enquanto as mais novas serão priorizadas

**How**
Só trocar a ordenação da query nessas páginas

**Additional context**
Foi notada pelo @flpfar em uma reunião de dev! Valeu 💪

**Comment by dev-danilosilva** [comment]
A PR acima implementa essas mudanças.
