### ISSUE TITLE
Allow edit of invited_reward and inviter_reward

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#66]
Right now on the Community Editor page we have a few fields that allow changing the name, description and logo of a community. We need to add two more fields to it. `invited_reward` and `inviter_reward`. Those fields are currently hard coded in the function that pushes the edit action to the blockchain. We just need to hook those input values into the ports call to edit the community

**Comment by zacck** [comment]
@Pancakem  another one?

**Comment by Pancakem** [comment]
@zacck I'll get on it.

**Comment by zacck** [comment]
Let us know if you need any help @Pancakem
