### ISSUE TITLE
Alterar a palavra "Patrocinar" por "Apoiar" na versão PT-BR do Broadcast (#598)

### ISSUE THREAD

**Issue by juramos-2020** [cambiatus/frontend#663]
**What we have**
Na versão em Português do Broadcast temos alguma a palavra "patrocinar" e "apoiar" representando a mesma ação.

**Proposal**
Alterar todas as palavras "patrocinar" para "apoiar"

**Why**
A palavra "apoiar" tem maior significado para as comunidades

**How**

**Additional context**
A @muguika também ficou de enviar algumas correções da tradução em Espanhol.

**Comment by juramos-2020** [comment]
OI @NeoVier 
sinalizei aonde encontrei a palavra "Patrocinar" para realizar essa alteração 😉👍
<img width="1867" alt="Group 1020" src="https://user-images.githubusercontent.com/67649886/143039755-345d7f6b-0de0-467b-ae47-5c3426014c51.png">

**Comment by dev-danilosilva** [comment]
😁

**Comment by dev-danilosilva** [comment]
A PR mencionada acima implementa essa mudança de texto 😉
