### ISSUE TITLE
Use Feedback for showing submit errors on Shop Editor

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#675]
**What we have**
Right now we show a basic, small red text above submit buttons on this form when we have an error

**Proposal**
Use Feedback to display errors

**Why**
Sometimes its hard to see the error message 

**How**
We can use the existing Feedback on LoggedIn to display transactions errors. This way we have a standard way of doing this and also will have a way to report errors to sentry 

**Additional context**
Here is a print of how an error looks like now:
<img width="1288" alt="Captura de Tela 2022-01-19 às 18 24 57" src="https://user-images.githubusercontent.com/1082127/150216160-fd1f8595-2d2c-4260-bdd6-d2c38bdd8e90.png">

**Comment by NeoVier** [comment]
This was fixed by #658, so I'm closing this
