### ISSUE TITLE
Allow users to update their notification preferences

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#681]
**Is your feature request related to a problem? Please describe.**
Since the implementation of our News feature, every month users will receive a monthly digest of all that happened in the community. We would need to allow our users to toggle those preferences of receiving emails, otherwise we might be not be respecting their choice of receiving communication from us. It is a global config, you opt on receiving preferences from all communities or none of them, so it's important to make this clear on our interface.

One other preference that we need to setup, its language. We already have a menu to change the in app language, so we can hook this language change to also trigger a mutation.

**Describe the solution you'd like**
We need to discuss how we are going to present this, but we already have a mutation to set those preferences in the profile:

```graphql
mutation {
  preference(claimNotification: false, digest: true, language: PTBR) {
    account
    name
  }
}
```

Right now we have these notification options:

- claim notification
- monthly digest about the community
- transfer notification

We also need to handle the case where the user has not set their language on the backend yet. It will come as `null` on the GraphQL `users` object. If that's the case then we need to set the current chosen language during the first initial setup of the app after its logged.

**Describe alternatives you've considered**
We could have a basic setting directly on the menu, maybe as a button that opens up

<img width="200" alt="Captura de Tela 2022-01-28 às 11 08 40" src="https://user-images.githubusercontent.com/1082127/151561009-467fce93-661a-43c0-81f6-75787ef4ef34.png">

**Comment by lucca65** [comment]
@juramos-2020 This setting will be used on the News feature, as a side effect of starting to send emails. Can you help us with the interface for this?

**Comment by NeoVier** [comment]
@juramos-2020 this might be useful (@lucca65 correct me if I'm wrong):
Right now we have these notification options:
- claim notification
- monthly digest about the community
- transfer notification

It would probably be nice to plan ahead and make it easy to add new kinds of notifications preferences in the future if we need to

**Comment by juramos-2020** [comment]
Yes I can help you. I will send you a new design tomorrow 😉👍

**Comment by juramos-2020** [comment]
@rafachadud 💚

**Comment by NeoVier** [comment]
@juramos-2020 @rafachadud Do we have any news on this? I remember these options are on the new profile page, do we have them somewhere else to add before the new profile page?

@lucca65 mentioned this should come in on the next release which is... tomorrow 😬. It's really quick and simple to add this feature though, and we can move it to the new profile page when that gets done.

What do you folks think we should do? Just add it somewhere else for now, and move it to the appropriate place afterwards?

**Comment by juramos-2020** [comment]
@NeoVier vou aguardar a @rafachadud trocar uma ideia com vc e lhe mostrar a proposta que ela montou.

**Comment by rafachadud** [comment]
@NeoVier I missed this is on the new release. D: 

But we can do like this for the current profile style, ad the toggles in the profile, in the section where they download their 12 words. 
https://www.figma.com/file/l2HhpioJFpVSUW6E5ZjBn9/Acessibilidade?node-id=659%3A14435

I put them in the same section for the redesign of the profile, so it makes sense to be there. :D 

Does this works?

**Comment by NeoVier** [comment]
Yep, that looks good to me @rafachadud, thanks!
