### ISSUE TITLE
Session automatically ends 

### ISSUE THREAD

**Issue by natillasol** [cambiatus/frontend#70]
**Describe the bug**

Session automatically ends and user is required to login again. It happened several times for various users in different phones.

borboins.cambiatus.io

**Comment by lucca65** [comment]
closing as it lacks details. 

@natillasol even though it happened with different people, we need a way to test and simulate this. This can have several reasons: low memory on budget phones, browser issues (maybe some different mobile browser?), etc.

We already have #75 and #73 for tracking that with more details.
