### ISSUE TITLE
Add an extra call to community creation

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#701]
**Is your feature request related to a problem? Please describe.**
After the role feature implementation we got an extra step that must be taken during the community creation process. 

**Describe the solution you'd like**
We need to call a new contract action `upsertrole` with the default member role:
```json
{
    "community_id": "X,YOURCOMMUNITYID", 
    "name": "member", 
    "color": "#ffffff", 
    "permissions": ["invite", "claim", "order", "verify", "sell", "transfer"]
}
```

**Describe alternatives you've considered**
N/A

**Additional context**
This will be changed later, after we implement the msig functionality, that will require us to handle membership a little different as we will have new permissions like `admin` and a new way of figuring out who can propose changes in a community in a decentralized way. For now, we only need to make sure that the community creation will fill in the basic data needed

**Comment by lucca65** [comment]
Bro, can you squeeze in this enhancement?

**Comment by NeoVier** [comment]
Sure!
