### ISSUE TITLE
Add contact information and new footer

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#702]
**Is your feature request related to a problem? Please describe.**
We are now preparing for our next milestone: improving the Shop. As part of our efforts to be more transparent and offer more help to the user, as now things will keep changing faster and faster, we should help the community users to be in touch with the admins.

**Describe the solution you'd like**
A while ago @juramos-2020 created [this new footer](https://www.figma.com/file/RSoh4DDEj0N1TVkQT0SxIn/Header-and-Footer?node-id=361%3A1768). Maybe that was her first issue for Cambiatus 🤔. Anyway, this provides us with a new design for the footer, but I think we can expand this a little bit more by using the same mechanism we have for user contacts, but now to have more details so it works best with the community contacts.

This new field on our GraphQL allows us to see several contacts:

```graphql
query {
  community(symbol: "0,MIZU") {
    contacts {
      label
      externalId
      type
    }
  }
}
```

We need a new page to add the contact information, we **need** to reuse the contact components. 

### Contact Component
We already have a way to add contact information to the user. We need to expand it to allow a label: its a new field on the contact that will be useful for the community admins to better direct their users, but also to improve the users direction, as the shop will effectively make them also **sellers** and having clear ways of being in touch is essential.

### Contact mutation
Our GraphQL will have some changes:

- new contact_type `email`, for alternative emails, as we already have the main one on the user's profile
- new mutation called `community`, that allow us to quickly update certain community data, like `has_news` (removing old mutation `has_news`) and `contacts`

**Describe alternatives you've considered**
N/A

**Additional context**
This feature is our icebox for a while but I think this is the perfect timing to implement this, as this will help our users to keep in touch with the communities' admins

**Comment by lucca65** [comment]
PR/branch for the needed backend: https://github.com/cambiatus/backend/pull/213

**Comment by NeoVier** [comment]
Nice! I think it would be nice for the admins if they could, instead of a phone number, add a link (e.g. a WhatsApp group invite link). Is that a use case for the new `label` field?

**Comment by lucca65** [comment]
Well I guess we can simply add a new type for this. Nice thinking bro, I'll add it!

**Comment by lucca65** [comment]
Done!

**Comment by juramos-2020** [comment]
Hy @lucca65 @NeoVier 

guys I didn't even remember this footer 🙈

Maybe he needs a drawing to include the [Guidelines and code of conduct ](https://www.figma.com/file/pjrI6ovITeudHw8CYYY7HV/Terms-%26-Conditions-%7C-Cookie-%26-LGPD?node-id=113%3A1160)right? 
But it would be something very simple, just include the link.

**Comment by lucca65** [comment]
nóis tarda mas não falha

**Comment by NeoVier** [comment]
@juramos-2020 @lucca65 where should we put the form for community admins to add/edit contacts? Should it be a new page? I think the "Community information" (`/community/settings/info`) is pretty crowded already. Should the form look like the one we use for users?

**Comment by lucca65** [comment]
I'd +1 this, this page was not made to grow a lot, and it will keep getting bigger in the next cycles of features and releases. Shop will need to have several admin pages (a few examples: categories, moderation, configurations like the % of fiat allowed, reports, promoted sales, etc).

While I don't have a solution for this, here is an example of a tool we use, called Sentry that have a super complex Configuration page, with sections, forms, etc

<img width="1191" alt="Captura de Tela 2022-03-08 às 10 40 22" src="https://user-images.githubusercontent.com/1082127/157249209-98887060-3b24-416c-b1bf-ed60c1346548.png">

**Comment by juramos-2020** [comment]
Thanks guys, @NeoVier @lucca65 

I'll make a proposal for that

**Comment by NeoVier** [comment]
@juramos-2020 just as a reminder to take into account while designing this, we also have a `label` field now, which means people can give their contacts more descriptive names. From the original description:

> We need to expand it to allow a label: its a new field on the contact that will be useful for the community admins to better direct their users, but also to improve the users direction, as the shop will effectively make them also sellers and having clear ways of being in touch is essential.

I would say that, in order to not clutter the contact form too much, we could have a little button next to the contact type that shows a new field to edit the label:

<img width="1263" alt="Untitled" src="https://user-images.githubusercontent.com/39280468/157514622-7bb40334-cc83-43e1-b1eb-2b154f5eda75.png">

Or maybe we could even have the contact type itself be editable (when the user clicks on `Whatsapp`, it turns into a text field the user can edit)


Either way, I think it's important to make it not occupy too much space

**Comment by lucca65** [comment]
+1 @NeoVier, no big changes and still simple. If the user don't see/use it, we keep the regular description, as the label is nullable! nice and elegant

**Comment by NeoVier** [comment]
@juramos-2020 any news on this?

**Comment by juramos-2020** [comment]
Oi @NeoVier 

já estava finalizando uma [nova proposta](https://www.figma.com/file/RSoh4DDEj0N1TVkQT0SxIn/Header-and-Footer?node-id=1225%3A2613). 

Mas antes de finaliza-la, conversei com a Rafa e Karla e combinamos que eu falaria com alguns representantes das comunidades para extrair a real expectativa de uso desse footer. 
A ideia de usá-lo como "contato de suporte" foi levantado há muito tempo pela comunidade Muda (se me recordo direito). Então seria bom trocar uma ideia com eles para saber se a necessidade ainda é essa e pegar uma percepção da comunidade Verdes também. 
Também seria bom pegar um feedback deles sobre como eles gostariam de usar essas informações de contato. 

Esse bate papo vai trazer boas informações sobre como construir essa opção de "contato para suporte", então acredito que isso ainda vai demorar um pouquinho.😅

**Comment by juramos-2020** [comment]
O link de "Termos e condições" não está atrelado a essa issue correto?
O "contato de suporte" pode ficar pausado e mesmo assim termos a implementação do link de "Termos e condições" ?

**Comment by juramos-2020** [comment]
OI @lucca65 

nesse caso vc sugere fazer a implementação do footer com a opção de "contato para suporter" mesmo antes de termos esse feedback da comunidade?

Ou vamos lançar com o link dos "Termos e condições" e depois sim implementamos o "contato para suporte"?

Desculpe é que não ficou claro pra mim.

**Comment by lucca65** [comment]
@NeoVier podemos também fazer um PR só pra manter o GraphQL atualizado, e depois fazemos os forms de contato e exibição dos mesmos no footer

**Comment by juramos-2020** [comment]
Valeu @lucca65 😉👍

**Comment by juramos-2020** [comment]
OI @lucca65 e @NeoVier 

Finalizei o novo footer com o contato para suporte. Falei com a Flavinha e com a Irene e pra elas ainda faz sentido mantermos esse recurso no footer. 

Vamos continuar tratando disso nesse PR? ou vcs vão abrir outro?

Segue como ficou:

[Um novo espaço de configuração mais flexivel](https://www.figma.com/file/RSoh4DDEj0N1TVkQT0SxIn/Header-and-Footer?node-id=1225%3A2613). 
Trouxe os recursos todos para um primeiro plano. Gostaria muito do feeback de vcs, se era isso mesmo o que vcs estavam imaginando. 

[Página de contatos para suporte](https://www.figma.com/file/RSoh4DDEj0N1TVkQT0SxIn/Header-and-Footer?node-id=1225%3A2860)
[Novo footer no mobile](https://www.figma.com/file/RSoh4DDEj0N1TVkQT0SxIn/Header-and-Footer?node-id=331%3A2262)
O modal só vai abrir no caso da comunidade ter mais de um contato para suporte. Provavelmente usaremos apenas um, mas caso, futuramente, alguma comunidade queira usar mais de um contato já temos o recurso pronto.
[Novo footer no desktop](https://www.figma.com/file/RSoh4DDEj0N1TVkQT0SxIn/Header-and-Footer?node-id=1249%3A2191)

**Comment by NeoVier** [comment]
Ficou show @juramos-2020! Criei uma nova issue pra conversarmos melhor sobre isso: #713. Vou deixar uns comentários lá para ficar melhor organizado. Já coloquei esses links lá também 😄
