### ISSUE TITLE
Allow images to be cropped

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#707]
**Is your feature request related to a problem? Please describe.**
Our image handling in the app today is very basic. We simply allow the user to upload an image.

**Describe the solution you'd like**
We should be able to allow for cropping images directly into the form. This way we can make sure that all images follow the correct aspect, when that is needed (like photos from an action or profile images).

Hopefully we can do this using only the frontend.

**Describe alternatives you've considered**
If that fails we can try to serve image magick on a HTTP endpoint

**Additional context**
This is part of the Shop milestone

**Comment by rafachadud** [comment]
Hi @lucca65 @NeoVier @MatheusBuss.
I have a first design update on this, link to figma: https://www.figma.com/file/l2HhpioJFpVSUW6E5ZjBn9/Acessibilidade?node-id=1154%3A53050

Basically is a modal that shows the size of the canvas and the image, allowing users to resize (zoom in and out) and drag the image. 

I also made a test with this modal for other use cases, like the cover images for user profile https://www.figma.com/file/l2HhpioJFpVSUW6E5ZjBn9/Acessibilidade?node-id=1154%3A47169. 

I think this is something we can include for user photos as well. What do you guys think?

**Comment by NeoVier** [comment]
Nice, thanks @rafachadud 

(Yes, this is the right issue 😄)

**Comment by NeoVier** [comment]
We should take as a parameter the aspect ratio and minimum size for images

**Comment by NeoVier** [comment]
@rafachadud @juramos-2020 @lucca65 I'm not sure what the best flow is, maybe you can help me out:

1. The form starts with a button to upload a file
2. The user clicks the button
3. We show the prompt to select a file
4. User selects file
5. Here I'm confused:
  a. We show the modal right away
  b. We show the image, just like we do now. When the user clicks the image, the modal opens

Option 5.a. doesn't seem possible for multiple-file inputs (How would we show multiple modals at once?). And on single-file inputs, if we show the modal right away, it might disrupt the user flow (they need to interact with the modal instead of just adding the file and moving on).

(We could choose to show the modal ASAP on single-file inputs, and not show any modals on multiple-file inputs)

---

And another one: Should we validate the minimum size and aspect ratio?

For example, let's say we want images in the format 1:1 for profile pictures. If the user enters an image that has an aspect ratio of 3:4, should that be an error, and prevent the user from submitting that image (forcing them to either choose another image or crop it appropriately)?

**Comment by rafachadud** [comment]
@NeoVier I would go for option b, I checked some other websites, and they only open the modal when there's only 1 image upload, if there's many, the user needs to click on the image to edit/crop. 

I would not validate by aspect ratio, since the crop is suppose to crop the image to the right ratio?

**Comment by lucca65** [comment]
@juramos-2020 contou que estão trabalhando nisso

**Comment by NeoVier** [comment]
@juramos-2020 @rafachadud @lucca65  como vamos forçar o aspect ratio das imagens, precisamos saber que aspecto devemos usar em cada imagem. Aqui está uma lista de todas as imagens que podem ser carregadas por usuários:

- Foto de perfil (Acredito que esse deve ser um quadrado - aspect ratio de 1 : 1)
- Logo da comunidade (Também acho que deve ser 1 : 1, mas **os ícones disponíveis por padrão não seguem esse aspect ratio** - cada um tem um aspecto diferente)
- Imagem de capa da comunidade
- Imagens de produtos do shop
- Imagens de verificação de ações

Lembrando também que **podemos ter a opção de não forçar o aspect ratio em algumas imagens** (por exemplo, nas imagens de verificação de ação talvez não faça sentido forçar o aspect ratio), **mas daí não tem como fazer o crop** (até podemos fazer um crop "à mão livre", onde o usuário pode arrastar pelas bordas da janela de seleção, mas isso vai atrasar essa feature ainda mais)

**Comment by lucca65** [comment]
> - Foto de perfil (Acredito que esse deve ser um quadrado - aspect ratio de 1 : 1)
> - Logo da comunidade (Também acho que deve ser 1 : 1, mas os ícones disponíveis por padrão não seguem esse aspect ratio - cada um tem um aspecto diferente)

+1!

Acho que o Shop pode se manter como está hoje, sem forçar um ratio, a mesma coisa para as imagens de verificação

@rafachadud qual seria a proporção ideal para a capa da comunidade?

**Comment by rafachadud** [comment]
Faz sentido um numero quebrado? 
Fiz os calculos e seria algo em torno de 6,4 : 1, se nao podemos fazer 7 : 1 ?

**Comment by NeoVier** [comment]
Podemos usar números quebrados sim @rafachadud. Será que não seria mais interessante usar um ratio mais "comum", como 1:1, 4:3 ou 16:9 (ou algo perto desses valores)? Se fugirmos muito desses valores, vai ficar difícil para os usuários colocarem uma foto inteira

Além disso, acho que essa conta não tá certa 😅 Um ratio de 7 : 1 fica assim:
<img width="782" alt="image" src="https://user-images.githubusercontent.com/39280468/171270731-3a47fa0f-5cc7-40f5-a70d-fd9e07d598ff.png">

**Comment by NeoVier** [comment]
Ah, esquece, eu tava pensando na foto do produto 🤦 Acho que esse ratio faz sentido pra imagem da comunidade

**Comment by rafachadud** [comment]
Sim, seria para a capa da comunidade xD 

Minhas habilidades matemáticas já foram melhores, hoje em dia está osso. hahah 

Mas fiz os calculos com o formato web (antes eu tinha calculado com base nas medidas do design) e deu uma proporcao de 9 : 2. Talvez algo assim funcione?

**Comment by lucca65** [comment]
Pessoal dei uma pesquisada rápida aqui no que o pessoal mais especializado recomenda pra tirar o máximo de velocidade de carregamento e qualidade visual e o recomendado 16/9 ou até mesmo 3/1 ou 2/1 para esse tipo de imagem. 

Algumas referências, falam de blogs mas também como Facebook e Twitter fazem
https://www.strikingly.com/content/blog/website-image-size-guidelines/
https://www.picmonkey.com/blog/facebook-cover-photo-size
https://www.adobe.com/express/discover/sizes/twitter
https://www.adobe.com/express/discover/sizes/facebook

**Comment by rafachadud** [comment]
+1 Lucca! 

Inclusive dei uma pesquisada em como o Youtube trata (porque gosto das dimensoes da capa de canal do youtube) e tem a mesma proporcao de 16:9, entao podemos manter essa e dar o crop com as medidas exatas da altura e largura. 

![Screenshot 2022-06-02 at 19 50 21](https://user-images.githubusercontent.com/67650032/171694775-c7f9962f-8288-468a-86d8-c3b916189604.png)
