### ISSUE TITLE
Language suddenly changes

### ISSUE THREAD

**Issue by natillasol** [cambiatus/frontend#71]
**Describe the bug**
For various users, the language changes out of the blue, mainly to CAT. They get really confused. 

**Expected behavior**
Language changes suddenly 

**Screenshots**

**Cambiatus Env you are using**
cambiatus.borboins.io

**Comment by lucca65** [comment]
@natillasol thanks for the report.

To whoever will solve this: It might be that the language dropdown is with a incorrect z-index, causing misclicks
