### ISSUE TITLE
Add empty state to shop

### ISSUE THREAD

**Issue by NeoVier** [cambiatus/frontend#714]
**What we have**
We have a beautiful new shop interface. However, we didn't treat the case of it being empty:
![image](https://user-images.githubusercontent.com/39280468/160303407-8106ef39-0da2-4efd-a101-2a4ca95c9064.png)

**Proposal**
Use some illustration or text to tell the user we couldn't find any sales on the community

**Why**
If we just show nothing, users may be confused and think the shop is still loading, or that something has gone wrong.

**How**
We can follow other examples. Some pages just have some text explaining what happened, others have text and images.

**Additional context**
Noticed this on CMBX

**Comment by NeoVier** [comment]
@juramos-2020 can you help us out with this one? I think we have lots of space to put a nice illustration there!

**Comment by lucca65** [comment]
+1, been thinking about the same after opening CMBX this month

**Comment by juramos-2020** [comment]
Hi @NeoVier 

in this case, this community will have shop?
because if this community won't have shop we can desabiliytar this recourse.
but if intencion is have the shop, we can work on illustration 

I don't know if cmbx will have products in the store now, or if we have that intention. So I think we can disable it. And if we are going to work the shop on it in the future, we can enable it.

Do I talk more about intending to have the feature or don't you understand?

**Comment by NeoVier** [comment]
I don't think it matters if the community pretends to use the shop or not, and it's not a CMBX exclusive thing.

If the community has the shop feature turned on, we need to show the shop. It may happen that there are no products on the shop yet (it's probably a pretty rare edge case), and we need to communicate that to the users, instead of just having a blank screen.

**Comment by NeoVier** [comment]
Another possible scenario is when the user clicks on the button that shows only the user's sales. If they have no sales, they also see a blank screen.

Maybe we could have something that kind of teaches the user, saying something like "Start by creating your first sale" and an illustration pointing at the "Create New" button

**Comment by juramos-2020** [comment]
ok let's work on these illustrations 😉👍

**Comment by rafachadud** [comment]
@NeoVier 
I prepared two empty states for the shop: 

- Shop with no products
[https://www.figma.com/file/rT5DMvPAtvbHSxNBwQENDM/New-shop---v1?node-id=2381%3A12952](url)

- Users with no offers
[https://www.figma.com/file/rT5DMvPAtvbHSxNBwQENDM/New-shop---v1?node-id=2402%3A15566](url)

**Comment by NeoVier** [comment]
Great @rafachadud, thanks!
