### ISSUE TITLE
Add version tag to Sentry errors

### ISSUE THREAD

**Issue by NeoVier** [cambiatus/frontend#733]
**What we have**
We use Sentry to log runtime errors on production.

**Proposal**
Some time ago, we started showing the current commit hash on the app to help us debug errors from users. However, we only have access to that if users send us screenshots or something like that. We could also send this commit hash to Sentry.

**Why**
We can eliminate "false" bugs, caused by browser caching and things like that. If we resolve a bug, we can probably archive it or delete it on Sentry so that we know it's fixed.

**How**
On the `logEvent` function in JS, add a tag that has the value of `process.env.COMMIT`

**Additional context**
I found a very weird error that shouldn't be able to happen: https://sentry.io/organizations/cambiatus/issues/3222078152/?project=1480468&referrer=slack

I'm pretty sure it's been a while since we've made changes to the `Invite`, so I don't think that error should happen, and the only thing I can think as the cause is a wrong version of the frontend. The only way to be sure of that kind of thing is if we had commit hashes on Sentry.

**Comment by NeoVier** [comment]
@lucca65 do you know if Sentry has something to do this automatically, or if we need to do it ourselves? (it's very very easy to do, but maybe they have something ready for this already 🤷)

Looking through the error, I couldn't find anything related to the app version or commit hash

**Comment by lucca65** [comment]
Bro you can do this by adding context to the Sentry JS object: https://docs.sentry.io/platforms/javascript/enriching-events/context/

If you have access to the version on the index.js file, should be super ez

**Comment by NeoVier** [comment]
Yeah, that's pretty much what I was planning to do. I was mostly wondering if they had something to do that automatically through their dashboard or something.

This way is super easy though, so no problem!
