### ISSUE TITLE
Objectives don't open on Windows

### ISSUE THREAD

**Issue by NeoVier** [cambiatus/frontend#738]
**Describe the bug**
The objectives on the new "How to earn" page don't open properly on Windows. Here's how they show up when clicking them to open:

![image](https://user-images.githubusercontent.com/39280468/165829674-182fbbb7-fec0-467e-ab8b-7bae24848597.png)

**To Reproduce**
1. Be on a Windows machine
2. Go to the "How to earn" page
3. Click on an objective to open it (it must have actions inside)

**Expected behavior**
Actions should show up, like this:

![image](https://user-images.githubusercontent.com/39280468/165829907-e5fac5e8-02fc-49e5-99c7-52d2581af569.png)

**Screenshots**
Already provided above

**Cambiatus Env you are using**
Staging, prod

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Firefox

**Additional context**
Discovered by @MatheusBuss when claiming things on CMBGO and CMBX

**Comment by lucca65** [comment]
wow, weird

**Comment by NeoVier** [comment]
Closing this, since @MatheusBuss reported that it didn't happen again
