### ISSUE TITLE
PDF is not downloaded

### ISSUE THREAD

**Issue by natillasol** [cambiatus/frontend#74]
**Describe the bug**
An user could not download his PDF into his phone. Note that he has a previous version of the 12 words document from a previous meeting. 

**Screenshots**

**Cambiatus Env you are using**
borboins..cambiatus.io

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - OS: 
 - Browser : Chrome 
 - Version 77.0.3865.116

**Comment by lucca65** [comment]
@natillasol please give us more details, this is after creating an account? How come then it is that the user already as the PDF?

**Comment by natillasol** [comment]
We did a previous meeting with them in which he created a username and he downloaded a PDF.

**Comment by lucca65** [comment]
But if he already has the document I don't understand what it was the expected behaviour.

**Comment by natillasol** [comment]
1. On October 31st, we had a meeting in which this user created an account and downloaded the PDF (dated 31/10/2019) in the app.cambiatus.io environment if not wrong.
2. During the meeting, the same person with the same phone  on November the 14th, using borboins.cambiatus.io created an account in which the PDF was not downloaded and only a blank page was retrieved (about page). When we checked the files and downloads folder, we were unable to find the new PDF for the new account. 

Does that make it a bit clearer? Otherwise @muguika can help me explain

**Comment by muguika** [comment]
The user was able to download the PDF the first time we tested borboins.cambiatus.io  but not the second time.  During our second test, after creating his new account and clicking to download the PDF he got a blank page.

![IMG_20191114_163207](https://user-images.githubusercontent.com/25396167/69104597-74a58780-0a2e-11ea-98c1-03333070ecdc.jpg)

**Comment by zacck** [comment]
Ok I have a fix that downloads he pdf in the same tab the user is in, hopefully this removes the confusion caused by the new tab
