### ISSUE TITLE
Add indicator to show that an action is already closed, completed and automatic 

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#745]
**What we have**
Today, when searching for an action we show all actions in existence in a same community. 

**Proposal**
1. Add a section or any other visual indicator that an action is closed or completed and thus cannot be claimed.
2. Disable the claim button and add indication if its automatic

**Why**
This may be misleading as some users might want to claim and have no idea if an action is closed or not

**How**
We might need assistance from @juramos-2020 and @rafachadud 

**Additional context**
[Appointed by Luiz Hadad on Slack](https://cambiatus.slack.com/archives/CA83HJAAD/p1651605302938319)

**Comment by juramos-2020** [comment]
Segue o que temos atualmente na tela de busca:

![image](https://user-images.githubusercontent.com/67649886/167130107-b11aec56-aec5-45d3-8cd8-fcd01968ed7f.png)


@lucca65 @NeoVier Sugiro inicialmente mudarmos esse cenário do cards das ações para o que a @rafachadud fez na tela de[ "How to earn"](https://www.figma.com/file/l2HhpioJFpVSUW6E5ZjBn9/Acessibilidade?node-id=732%3A20001)

Enquanto a @rafachadud faz uma propposta do card de ação encerrada. 
Concordam?

**Comment by NeoVier** [comment]
+1

**Comment by lucca65** [comment]
@juramos-2020 @rafachadud Alguma novidade sobre isso?

**Comment by lucca65** [comment]
@rafachadud aproveitando, vamos precisar também de um indicador de ações automáticas, hoje mostramos só o botão de compartilhar:

<img width="877" alt="Captura de Tela 2022-05-27 às 15 23 02" src="https://user-images.githubusercontent.com/1082127/170769011-44a9a9c1-e742-4cde-91f7-67eea803dff2.png">


Fiz uma anotação tosca de que devemos diferenciá-las nessa tela e na pesquisa!

**Comment by rafachadud** [comment]
@lucca65 esqueci de compartilhar o link 🫠🫠🫠
[https://www.figma.com/file/CO9QI0RyRxdx9ShfHJCo2g/acessibilidade?node-id=1171%3A24117](url)

O que seriam acoes automaticas? 🤔

**Comment by lucca65** [comment]
são um tipo de ação na Cambiatus que existem desde a primeira versão, que não precisam dos votos e do processo de reinvidicacao. Te convidei pra gente conversar disso há alguns meses: https://github.com/orgs/cambiatus/discussions/671#discussion-3806007

**Comment by lucca65** [comment]
Obrigado Rafa, ficou show!

**Comment by rafachadud** [comment]
@lucca65 eu adicionei um textinho referente à acoes automáticas no mesmo link do figma. 👯 
![Screenshot 2022-05-31 at 20 26 50](https://user-images.githubusercontent.com/67650032/171258898-10ae6774-6e05-49c0-9a1d-2e5d8a66daed.png)
