### ISSUE TITLE
Notifications page don't work properly when displaying product images

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#746]
**Describe the bug**
Notification page don't load if there is a notification with a product image on it

**To Reproduce**
1. Have one product of yours bought
2. Click on the notification bell 
3. See error

**Expected behavior**
It should display the notification screen

**Screenshots**
<img width="1281" alt="Captura de Tela 2022-05-04 às 21 45 20" src="https://user-images.githubusercontent.com/1082127/166848998-ae454dfa-6a51-45d2-a43b-d7c902712ea0.png">

**Cambiatus Env you are using**
Production

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Additional context**
Discovered after the migration after moving from blockchain

**Comment by lucca65** [comment]
It might also happen on related pages like payment history

**Comment by NeoVier** [comment]
For now we should just show the first image out of the `images` field, right? I don't think we have designs for that with multiple images, and we don't really let people add multiple images yet anyway

**Comment by lucca65** [comment]
yeah first image is fine?
