### ISSUE TITLE
Session automatically finished whilst doing a transfer

### ISSUE THREAD

**Issue by natillasol** [cambiatus/frontend#75]
**Describe the bug**
Session automatically finished whilst doing a transfer

**Cambiatus Env you are using**
borboins.cambiatus.io

**Smartphone (please complete the following information):**
 - Device: Xiaomi A1N1
 - OS: 
 - Browser Mozilla Firefox
 - Version 68.1.1

**Additional context**
Ranulfo's phone

**Comment by zacck** [comment]
Oh wow I experienced this while testing something else @natillasol  I thought I logged out

**Comment by lucca65** [comment]
This happened several times during our tests, we should increase priority

**Comment by zacck** [comment]
On it this week @lucca65  did you notice any likely causes?

**Comment by lucca65** [comment]
no nothing ):

**Comment by zacck** [comment]
No worries have a few hours scheduled for it tomorrow ...

**Comment by lucca65** [comment]
This is still happening, reopening...

**Comment by zacck** [comment]
@lucca65  so I can't even replicate this issue, would you reckon this would be easier to solve if we built fuzz tests for the Auth module?
