### ISSUE TITLE
Visualização e edição de categorias na comunidade

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#754]
Criar design das tela visualizar todas categorias na comunidade

Tela que serve para mostrar todas as categorias que uma comunidade tem e só pode ser acessada pelo administrador. 

Aqui o administrador também poderá reordenar as categorias. 

Deve mostrar como árvore, pois categorias podem possuir categorias dentro. Exemplos: [aqui](https://user-images.githubusercontent.com/1082127/169156525-fac104f4-b67a-468b-9f3c-aa0f4637d995.png) e [aqui](https://user-images.githubusercontent.com/1082127/169156736-11f72a50-2c23-46eb-a854-4318a0b79d4a.png)

Cada categoria em seu "card" ou "linha" deve mostrar o nome da categoria, a descrição e o slug. [Aqui tem uma explicação do slug e como usar](https://yoast.com/slug/). O elemento da categoria deve ser clicável para abrir seus nós filhos (sub categorias), que são mostradas da mesma maneira que a "categoria mãe".

As categorias podem ser reordenadas. Isso afeta como serão exibidas na listagem pública da loja. Devemos ter um botão no topo que entra no modo de ordenação, linhas podem ser arrastadas ou o usuário pode clicar em duas setas que deverão aparecer nas linhas somente nesse modo: ⬆ ⬇. 

Um botão de edição também deverá estar disponível, que abrirá campos extras na linha, para que seja editável como uma planilha de excel.

**Comment by NeoVier** [comment]
Podemos representar as categorias no frontend usando [zwilias/elm-rosetree](https://package.elm-lang.org/packages/zwilias/elm-rosetree/latest/Tree)! A estrutura é exatamente o que precisamos, e a documentação do pacote até mostra alguns casos de uso bem parecidos com o nosso

**Comment by lucca65** [comment]
Incrível! @NeoVier eu conversei com a @juramos-2020 nessa semana e topamos fazer um experimento de tocar essa tela sem referências de design. Não é o ideal mas o pessoal de design tá com as mãos cheias e essa é uma das telas que não estava pronta. Fora que a estrutura de categorias que usamos segue a estrutura de e-commerce que é diferente da estrutura de filtros que tínhamos no design. 

Acha que podemos bolar uma tela usando referencias do tailwind e outras libs? Acho que estruturalmente dá pra gente pegar algumas coisas

**Comment by lucca65** [comment]
acho melhor deixarmos isso pra outra issue bro, assim podemos iterar melhor em como isso vai ficar, acho que podemos aprender bastante com a maneira com que outras lojas fazem
