### ISSUE TITLE
Over imposed text

### ISSUE THREAD

**Issue by natillasol** [cambiatus/frontend#76]
**Describe the bug**
Over imposed text when searching for a user to do a transfer. [iphone]
Over imposed numbers in PIN [Dell Computer]

**Expected behavior**
over imposed text

**Screenshots**
![WhatsApp Image 2019-11-14 at 16 48 26](https://user-images.githubusercontent.com/57719975/68954540-d98c8380-0789-11ea-8a92-5fb25080b822.jpeg)

![WhatsApp Image 2019-11-14 at 17 00 02](https://user-images.githubusercontent.com/57719975/68954620-0476d780-078a-11ea-95c0-9d24d532c699.jpeg)

**Cambiatus Env you are using**
borboins.cambiatus.io

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: 
 - Browser  Safari
 - Version

**Comment by zacck** [comment]
@lucca65  do we really have a fix for the over imposed text in the pin, I think the issue is that the app considers double digit numerals to be numbers

**Comment by zacck** [comment]
Hmmm perhaps I can limit the highest value to 9 let me try

**Comment by zacck** [comment]
Hi @natillasol  @lucca65  I can not seem to replicate the pin issue on my end

**Comment by lucca65** [comment]
it is device specific, our code really tries to mitigate this.
