### ISSUE TITLE
Claim buble not showing

### ISSUE THREAD

**Issue by natillasol** [cambiatus/frontend#77]
**Describe the bug**
When clicking to claim an action, the bubble in which you confirm your claim does not show.

**Expected behavior**
 the background of the page goes darker (in gray) but the bubble is not visible

**Screenshots**

**Cambiatus Env you are using**
borboins.cambiatus.io 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chome
 - Version 

![WhatsApp Image 2019-11-14 at 17 05 41](https://user-images.githubusercontent.com/57719975/68954867-79e2a800-078a-11ea-86ae-c85c26e3ec27.jpeg)

**Comment by zacck** [comment]
@lucca65  this was fixed by @Pancakem's fix the other week closing this as it is a non issue for now
