### ISSUE TITLE
Allow user to associate to categories to their product

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#770]
**Is your feature request related to a problem? Please describe.**
With the implementation of #760 categories in the community we need a way to associate a product to one or more categories. 

**Describe the solution you'd like**
Modify the edit form to support categories, selecting as many as the user wants. We can follow the category screen tree-like design

When selecting a child, it should also select its parents. Although, the user can unselect freely

**Describe alternatives you've considered**
N/A

**Additional context**
The reference of the old category model: https://www.figma.com/file/OSqvmNO3HSzRJSrp9Of865/New-Shop?node-id=2624%3A27037

**Comment by lucca65** [comment]
We will show categories on the view product page as well? Maybe as pills?

**Comment by lucca65** [comment]
@juramos-2020 @rafachadud teremos algum tipo de indicador com a tela de visualização de oferta quando eu sou o dono?

Hoje a tela é igualzinha, se estou olhando pra uma oferta minha ou de outra pessoa, exceto por uma diferença:

O botão de **"comprar"** se torna **"editar"**. Seria legal ter alguma outra diferença, talvez uma barra no topo indicando alguma coisa ou dando certos botões? 

Se não tiverem nada fácil nesse sentido, seguimos assim, sem problemas

**Comment by rafachadud** [comment]
@lucca65 @juramos-2020 posso trabalhar nisso durante o final de semana e testar algumas coisas mais simples. Pode ser? o/

**Comment by juramos-2020** [comment]
Tranquilo Rafa, no seu tempo ☺️

**Comment by juramos-2020** [comment]
@lucca65 acho que [esse pedido](https://github.com/cambiatus/frontend/issues/770#issuecomment-1179241844) resolve a issue #719 .

@rafachadud quando você for atualizar o link, pode colocar na issue #719 😉👍
