### ISSUE TITLE
Erro no crop da imagem da Categoria 

### ISSUE THREAD

**Issue by juramos-2020** [cambiatus/frontend#775]
**Describe the bug**
O crop está travando e a área da imagem que foi definida para corte não está salvando corretamente.

O erro foi reportado na issue #760 

https://github.com/cambiatus/frontend/pull/760#issuecomment-1170290665

**Expected behavior**
Posicionar o crop sem "travas" e fazer com que a área selecionada apareça como salva.

**Screenshots**

**Comment by juramos-2020** [comment]
Obrigada @NeoVier 😅🤟

**Comment by lucca65** [comment]
Isso também tá rolando, dependendo da imagem, ela fica inacessível 

<img width="836" alt="Captura de Tela 2022-08-12 às 15 08 48" src="https://user-images.githubusercontent.com/1082127/184418500-ee1b5b70-6e43-401c-a79a-37e814a0f6d2.png">
