### ISSUE TITLE
Erro no crop da Imagem 

### ISSUE THREAD

**Issue by juramos-2020** [cambiatus/frontend#776]
**Describe the bug**

Erro reportado nessa issue:

https://github.com/cambiatus/frontend/pull/760#issuecomment-1170290665

**Expected behavior**
Mover a área de corte sem travas e salvar a imagem que foi definida pela área de corte.

**Screenshots**

**Comment by NeoVier** [comment]
@juramos-2020 acho que abriu duas issues sem querer 😅. Vou fechar essa para termos só a #775 e não ficar com duplicatas
