### ISSUE TITLE
Update action form to support images

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#777]
Today we have an updated api/smart contract/event-source combo that supports a single image as a param for upserting actions. **We need to update the action form** to support it and also update some pages like How to Earn, search and claims. Please be aware that claims is a big part, with pages like "my claims", the dedicated view for a claim, the modal for a claim and an analysis (reviewers viewing the claim, instead of the claimer).

**Comment by lucca65** [comment]
@rafachadud como tá indo essa? Uma sugestão legal seria de ter o DS para upload de imagem, que pode seguir o que temos aqui: https://cambiatus-elm-book.netlify.app/forms/file

Isso é o que já temos de DS (talvez um dev system?) sobre esse componente

**Comment by rafachadud** [comment]
Oie @lucca65, demorei mas saiu. 

Eu usei o mesmo estilo que temos para o upload das claims e acredito ser o que temos no elm book. Vou adicionar esse elemento no nosso arquivo do design system. 

https://www.figma.com/file/esLEQOPHNaq3TJoQGpNbuZ/Dashboard?node-id=589%3A2394

**Comment by lucca65** [comment]
Show! Obrigado @rafachadud!
