### ISSUE TITLE
Use masonry layout on analysis page

### ISSUE THREAD

**Issue by NeoVier** [cambiatus/frontend#795]
**What we have**
On the analysis page, some cards may be taller than others:
![image](https://user-images.githubusercontent.com/39280468/180781507-dbe40fbc-9819-425d-b55a-1f55c7bdbbc6.png)

Right now, we just show rows of the same height.

However, we've created a component, `MasonryLayout`, which will display different-height rows. It's used in the How to Claim page:
![image](https://user-images.githubusercontent.com/39280468/180781778-14ae6114-2723-4fac-a609-2fbe1ec60314.png)

**Proposal**
Use the `MasonryLayout` component in the analysis page as well.

**Why**
To have a more consistent look throughout the app, and make that page prettier

**How**
Just stick the `MasonryLayout` component, it shouldn't be too hard

**Additional context**
We should keep an eye out for when there are too many actions, and see if there are any performance issues with this component (I would guess that there usually are more cards in this page than in the objectives page)

**Comment by NeoVier** [comment]
@lucca65 @juramos-2020 @rafachadud what do you think about this one? Do you think it's a valid change? Maybe keeping same height rows is better for people who want to take a quick glance at the claims

**Comment by lucca65** [comment]
+1 this screen as it is right now could be improved!

**Comment by lucca65** [comment]
Conversamos sobre isso na reunião de sexta e decidimos tentar e ver como fica!

Temos a preocupação de que deixar desigual pode tornar mais difícil o agrupamento visual de certas claims. Nesse exemplo do print fica fácil ver que algumas claims foram feitas no mesmo dia. Como será que fica no mansonry?
