### ISSUE TITLE
Create user settings page (with new text for notifications)

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#796]
Modify text email preferences to be more clear that the notification is actually an email

<img width="628" alt="Captura de Tela 2022-07-25 às 13 04 53" src="https://user-images.githubusercontent.com/1082127/180823921-0f4b2ba9-9930-40dc-8cc5-fed60d1eab1a.png">

## Context

Discussed during our RICE session on 25 July with @juramos-2020 and @iamluizhadad

**Comment by lucca65** [comment]
@juramos-2020 pode sugerir como os textos podem ficar?

**Comment by juramos-2020** [comment]
@lucca65 a notificação de transferência 'e a unica que não 'e por e-mail correto? Ou ela tambem esta sendo por e-mail?

**Comment by lucca65** [comment]
todas essas são por e-mail.

Não existe uma maneira de desabilitar as notificacoes do sininho

**Comment by juramos-2020** [comment]
Obrigada ☺️

Segue a sugestão: https://www.figma.com/file/CO9QI0RyRxdx9ShfHJCo2g/Acessibilidade?node-id=1307%3A24327

**Comment by NeoVier** [comment]
@juramos-2020 será que esse novo menu de settings não vai ser confuso para admins de comunidade?

Já usamos o ícone de engrenagem para levar às configurações da comunidade. Esses dois estando bem perto um do outro, com o mesmo nome e mesmo ícone, me parece fácil de confundir

**Comment by juramos-2020** [comment]
Novo menu? aonde? 
nao entendi.

**Comment by juramos-2020** [comment]
@NeoVier  vc pode sinalizar la no figma por favor

**Comment by juramos-2020** [comment]
> Que me parece ser acessível pelo menu que abre na foto de usuário:

sim por o que estamos alterando 'e essa configuracao do perfil do usuario.

**Comment by juramos-2020** [comment]
Ja temos essa tela  https://www.figma.com/file/CO9QI0RyRxdx9ShfHJCo2g/Acessibilidade?node-id=1307%3A24327

não alterei o acesso a ela. Apenas dividi as informações.

**Comment by NeoVier** [comment]
Não temos essa tela no app 😅 

Todas essas configurações ficam na página de perfil (`/profile/<nome>`), como mostrei acima:

![Untitled](https://user-images.githubusercontent.com/39280468/181255780-f44efe3b-8435-445d-be70-1047bcb3595d.png)

E não temos o link de settings no menu da foto de usuário:

![image](https://user-images.githubusercontent.com/39280468/181255856-34985f16-033c-456f-904a-e553bf0f1ac0.png)

**Comment by NeoVier** [comment]
Pra deixar claro, eu gosto dessa tela, e acho que ela deveria existir mesmo! Só achei que ficaria confuso o acesso.

Talvez uma solução simples seria jogar o ícone de configurações da comunidade pra dentro do menu da foto do usuário, e ter dois links: "Configurações pessoais" (talvez só "Configurações" para usuários que não são admins) e "Configurações da comunidade".

Quem sabe, assim até podemos colocar a barra de pesquisa pra cima em dispositivos menores (no mesmo nível do seletor de comunidades, notificações e foto do perfil), e assim economizamos um pouco de espaço vertical em telas menores (como o @lucca65 sempre fala 😁)

**Comment by juramos-2020** [comment]
> Só achei que ficaria confuso o acesso.

Com certeza😅 ela so faz sentido se tivermos o ícone de configurações no menu do perfil.

Talvez uma solução simples seria jogar o ícone de configurações da comunidade pra dentro do menu da foto do usuário, e ter dois links: "Configurações pessoais" (talvez só "Configurações" para usuários que não são admins) e "Configurações da comunidade".

Isso mesmo. A ideia dessa proposta (acho ate que tem uma issue dela) é justamente adicionar o ícone de configurações dentro do menu do usuário para ele configurar as informações pessoais. O admin continua editando as informações da comunidade dentro de "Configurações da comunidade".


> Quem sabe, assim até podemos colocar a barra de pesquisa pra cima em dispositivos menores (no mesmo nível do seletor de comunidades, notificações e foto do perfil), e assim economizamos um pouco de espaço vertical em telas menores (como o @lucca65 sempre fala 😁)

Show Podemos testar e ver como que fica😃

**Comment by lucca65** [comment]
Não estava lembrando dessa alteração do menu @juramos-2020, achei bem legal. Inclusive acho que podemos alterar o escopo dessa issue para melhorar isso e torná-la sua própria página. O que acham?

> Talvez uma solução simples seria jogar o ícone de configurações da comunidade pra dentro do menu da foto do usuário, e ter dois links: "Configurações pessoais" (talvez só "Configurações" para usuários que não são admins) e "Configurações da comunidade".

Dou +1000 pra isso, apesar que me lembro bem que essa engrenagem foi uma decisão bem "desinspirada" e não foi pensada a fundo. Acho que o menu principal (que tem só painel e loja) é o ideal para ficar isso. Podemos até dar destaque já que poucos tem acesso a isso. Talvez até mover isso pra página da comunidade. Mas acho que isso é ainda outro assunto. Assunto que pode ficar mais relevante com a implementação de roles, onde vamos permitir vários Admins. Vamos deixar isso pro futuro!

Pra resumir: **TL;DR**

1. Vamos alterar essa issue para criar tela de configuração. Já temos os designs e agora os textos atualizados. 
2. Alterar o acesso dela para a caixinha do perfil
3. Deixar a engrenagem admin onde está agora. Um dia melhoramos isso

**Comment by juramos-2020** [comment]
Sucesso Lucca. Super concordo!

E achei bem legal essa idéia do @NeoVier de "colocar a barra de pesquisa pra cima em dispositivos menores (no mesmo nível do seletor de comunidades..."
Eu vi um comportamento bem legal em um app (vou procurar para compartilhar a ideia com vcs) que aparecia apenas o ícone da pesquisa e quando o usuário clica nela ela expande e os outros elementos somem. Mas é só uma idéia precisamos testar p ver se funciona legal

**Comment by NeoVier** [comment]
> Eu vi um comportamento bem legal em um app (vou procurar para compartilhar a ideia com vcs) que aparecia apenas o ícone da pesquisa e quando o usuário clica nela ela expande e os outros elementos somem. Mas é só uma idéia precisamos testar p ver se funciona legal

Acho que vários apps fazem isso. Dei uma olhada super rápida em alguns apps do meu celular, e achei alguns: Reddit, LinkedIn, Discord, GitHub, Slack. Todos eles mostram ou o ícone de pesquisa, ou uma barra de pesquisa um pouco menor. Ao clicar na pesquisa, todo o resto do app some pra mostrar só a busca. Enfim, podemos discutir isso mais pra frente
