### ISSUE TITLE
Add the web analytics tool code into Muda's community

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#813]
Hi,

We would like to test a new web analytic tool that helps us to collect more navigation data. It is the first step, we hope to use in all communities at the future. The code must be inserted inside the tag 'head', only on Muda's app (http://muda.cambiatus.io). So, we will collect only Muda's data. 

More about [Matomo](https://matomo.org/)

> 
> <script>
>   var _paq = window._paq = window._paq || [];
>   /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
>   _paq.push(['trackPageView']);
>   _paq.push(['enableLinkTracking']);
>   (function() {
>     var u="https://cambiatus.matomo.cloud/";
>     _paq.push(['setTrackerUrl', u+'matomo.php']);
>     _paq.push(['setSiteId', '2']);
>     var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
>     g.async=true; g.src='//cdn.matomo.cloud/cambiatus.matomo.cloud/matomo.js'; s.parentNode.insertBefore(g,s);
>   })();
> </script>
>

**Comment by heltonlr** [comment]
Hi Team. Some news about that ?

**Comment by lucca65** [comment]
Hey @heltonlr we usually "digest" new issues on our weekly every Friday to plan ahead and decide what we are going to do next. You can check this issues side bar for its status:

<img width="324" alt="Captura de Tela 2022-08-19 às 13 08 58" src="https://user-images.githubusercontent.com/1082127/185661245-4d2823c1-69ca-4c4c-9146-2cadc2a41b36.png">

this way you can keep track of our work and our next steps!

**Comment by NeoVier** [comment]
@heltonlr não temos como incluir só para alguma comunidade em específico... O que podemos fazer é usar algum recurso do Matomo para diferenciar as comunidades (no Plausible usamos um parâmetro chamado `domain`). Sabe se existe alguma funcionalidade do Matomo que funcione pra isso?

**Comment by NeoVier** [comment]
Também estamos [prestes a lançar mais uma release](https://cambiatus.slack.com/archives/CGQQ98MQA/p1660935367420079). Podemos correr um pouco com essa issue pra incluir o Matomo antes dela, mas se não tiver pressa pra isso, podemos incluir na próxima (geralmente fazemos uma release por mês, mais ou menos), o que acha?

**Comment by heltonlr** [comment]
Fala pessoal, vou verificar essa funcionalidade para diferenciar as comunidades. Não se preocupem se isso não entrar nesse release, não é nada urgente.

**Comment by heltonlr** [comment]
Fala pessoal, @NeoVier , agora eu configurei de forma diferente, adicionando mais de uma URL como o Matomo solicitava nesses casos (imagem). Podemos testar assim para ver como fica a visualização dos dados...

```
<!-- Matomo -->
<script>
  var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="https://cambiatus.matomo.cloud/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '5']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src='//cdn.matomo.cloud/cambiatus.matomo.cloud/matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Matomo Code -->
```

![Screen Shot 2022-08-21 at 19 27 35](https://user-images.githubusercontent.com/39558132/185813415-254088ee-0dc0-4b49-802f-6c39558e0116.png)

**Comment by NeoVier** [comment]
Beleza @heltonlr, já adicionamos na nossa lista de afazeres 😁
