### ISSUE TITLE
Show categories on the product page

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#817]
Show categories as "tags" on the product page, so users can know more. https://www.figma.com/file/OSqvmNO3HSzRJSrp9Of865/New-Shop?node-id=2540%3A18971

![image](https://user-images.githubusercontent.com/1082127/185677250-5d4ff114-2e7b-4ff0-99ac-7f661523dbd0.png)

**Comment by NeoVier** [comment]
The product page is visible for guests as well. Guests can't query for `Product`, only for `ProductPreview`. However, `ProductPreview` doesn't include the product's categories. Are we going to show these tags for guests as well, or only for logged in users?

**Comment by lucca65** [comment]
i don't think it's needed to be honest. it's a rare usecase
