### ISSUE TITLE
Check if user can buy product

### ISSUE THREAD

**Issue by NeoVier** [cambiatus/frontend#822]
**What we have**
A new and improved shop.

**Proposal**
Check if the user has enough balance to buy products from the shop.

**Why**
We're getting a bunch of these errors: https://sentry.io/organizations/cambiatus/issues/2582322317/?project=1480468&referrer=slack, because even when users don't have enough balance, we allow them to try to buy the product.

**How**
We already do this in the Transfer page, we can do something similar. I don't think we need to change anything visually, just disable the button if there isn't enough balance.

**Additional context**
N/A.

**Comment by lucca65** [comment]
+1
