### ISSUE TITLE
Require at least two verifiers in the verifier list

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#85]
Make sure that if we have a list of verifiers active on the action, it is required of it to have at least two users.

**Comment by amiskov** [comment]
I guess I understand how it should work, but I'm not sure enough :)

Here’s how I see the implementation. @lucca65 please, correct me if I’m wrong.

When “Manual” verification is chosen, we need to select _at least 2 verifiers_. So, when we press “Create” button with _no verifiers selected_, there should be a validation error like this:
￼
![• Manual, rewards the user only after reviewed by others](https://user-images.githubusercontent.com/140053/78041129-07f5ae80-7379-11ea-8fed-e3fd8ab2e6af.png)

The same story is for the case when only _1 verifier is selected_:
￼
![• Manual, rewards the user only after reviewed by others](https://user-images.githubusercontent.com/140053/78041220-19d75180-7379-11ea-86a4-410b3e815e32.png)

And when we _select 2 or more verifiers_, then validation should pass.

Are you OK with this solution?

**Comment by amiskov** [comment]
And here's another question:
![Screenshot 2020-03-31 at 18 28 04](https://user-images.githubusercontent.com/140053/78044832-d7fcda00-737d-11ea-8822-c233a8f51b29.png)

**Comment by lucca65** [comment]
@amiskov You understood it completely. The "minimum number of votes" is related to the verifiers field! Just keep in mind that, min votes number cannot be smaller than 2!

**Comment by amiskov** [comment]
@lucca65 here's the result so far. I made a little demo to show how it works:

[![image](https://user-images.githubusercontent.com/140053/78285189-30bca600-7529-11ea-9fbe-95957664dec3.png)](https://youtu.be/VclL3sm5m0w)
