### ISSUE TITLE
Buy form is broken 

### ISSUE THREAD

**Issue by zacck** [cambiatus/frontend#94]
**Describe the bug**
The value input and label touches the quantity input and label please see the screen grab below

**To Reproduce**
1. Log into the app
2. Click on `Shop` 
3. Scroll down to an item and click on it '.
4. Click on buy'
4. See value element and quantity element are touching

**Expected behavior**
The form should be displayed in a manner that is understandable and usable without confusion 

**Screenshots**
![Screenshot 2019-12-04 at 11 08 34](https://user-images.githubusercontent.com/897731/70129040-b8cb9580-1686-11ea-9e59-9af44c9b8024.png)

**Cambiatus Env you are using**
https://app.cambiatus.io/shop/7

**Desktop (please complete the following information):**
 - OS: mac Os  Catalina 
 - Browser: Brave 
 - Version 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)

**Additional context**
Issue happens on desktop only this is likely a good reason to migrate to the new shop interface  as shown here 
https://www.figma.com/file/GyRvSEQNS91DOLgMIk3u77/shop-desk?node-id=325%3A0

**Comment by zacck** [comment]
@heltonlr  I can't seem to find a shop interface for the buy page on figma would you mind sharing the link if it's available?

**Comment by zacck** [comment]
Rest of the states 
Success interface (transfer):
https://www.figma.com/file/GyRvSEQNS91DOLgMIk3u77/shop-desk?node-id=103%3A0
Success interface (receipt):
https://www.figma.com/file/GyRvSEQNS91DOLgMIk3u77/shop-desk?node-id=351%3A2447
and when an error occurs:
https://www.figma.com/file/GyRvSEQNS91DOLgMIk3u77/shop-desk?node-id=349%3A108

**Comment by zacck** [comment]
@nyoikejerry this one is a good one to start with ... let me know if I can help

**Comment by lucca65** [comment]
Sorry guys it is already solved, I missed closing this issue on the PR that closes it

**Comment by lucca65** [comment]
<img width="1309" alt="Screen Shot 2019-12-09 at 14 48 06" src="https://user-images.githubusercontent.com/1082127/70459431-ec495e00-1a92-11ea-8f07-11d5b1f51e13.png">
