### ISSUE TITLE
Is Cutting  the "12 words" at the pdf

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#96]
**Describe the bug**

**To Reproduce**
1. Create account
2. Download the pdf with 12 words and private key
3. Open the document

**Expected behavior**
Do not cut the words

**Screenshots**
--

**Cambiatus Env you are using**
muda.cambiatus.io

**Desktop (please complete the following information):**
- OS: OSX
- Browser: Safari
- Version: --

**Smartphone (please complete the following information):**
 - Device: iPhone 7
- Browser: Safari
- Version: --

**Additional context**
--

**Comment by lucca65** [comment]
@heltonlr why don't we solve this by implementing the new PDF?

**Comment by heltonlr** [comment]
> @heltonlr why don't we solve this by implementing the new PDF?

Sure, no problem.

**Comment by lucca65** [comment]
Ok, after it is done on the Design UX/UI board we open a new issue to solve this
