### ISSUE TITLE
Input "Sale price" does not work when creating offer and accept letters

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#97]
**Describe the bug**
Input "Sale price" does not work when creating offer. User types a number (example: 20) and the input show "Number less than 0". And is accepting letters.

**To Reproduce**
1. Create an offer
2. Type a number at "Sale price" input or type letters
3. Click "Create"

**Expected behavior**
- Do not show error when the number is bigger than 0 and do not accept letters.

**Screenshots**
--

**Cambiatus Env you are using**
- muda.cambiatus.io

**Desktop (please complete the following information):**
 - Not tested

**Smartphone (please complete the following information):**
 - Device: Xiami; Samsung (several)
 - OS: Android
 - Browser Chrome
 - Version: --

**Additional context**
--

**Comment by lucca65** [comment]
fixed by #183
