### ISSUE TITLE
Logo too small on desktop and smartphone

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#99]
**Describe the bug**
Logo too small at desktop, users can not see.

**To Reproduce**
1. Go to muda.cambiatus.io

**Expected behavior**
Logo visible to the user at desktop and a bit bigger at smartphone

**Screenshots**

![Screen Shot 2019-12-05 at 11 55 09](https://user-images.githubusercontent.com/39558132/70246889-3363e600-1757-11ea-97df-8274616f2548.png)

**Cambiatus Env you are using**
- muda.cambiatus.io

**Desktop (please complete the following information):**
 - All

**Smartphone (please complete the following information):**
 - All;

**Additional context**
- Lets talk about before start this task;

**Comment by lucca65** [comment]
@heltonlr you need to provide us with a desktop version with the following dimensions: 505x52

that is the dimension of the original Cambiatus logo and the partners logo should follow the same pattern or else it will be impossible to do a rule to fit all logo sizes in a restricted space

**Comment by heltonlr** [comment]
> @heltonlr you need to provide us with a desktop version with the following dimensions: 505x52
> 
> that is the dimension of the original Cambiatus logo and the partners logo should follow the same pattern or else it will be impossible to do a rule to fit all logo sizes in a restricted space

@lucca65, please try this one. It is exactly 52px height. let me know if it worked.

<img width="133" alt="LogoMudaDesk" src="https://user-images.githubusercontent.com/39558132/72924810-590d7480-3d30-11ea-91bb-6a1a099bcdff.png">

**Comment by lucca65** [comment]
@heltonlr we need the logo to be svg can you export in that format for us?

**Comment by heltonlr** [comment]
Sure, I will send at Slack.

**Comment by lucca65** [comment]
deployed on muda.cambiatus.io

**Comment by heltonlr** [comment]
Hey @lucca65 and @zacck, this is the exact size of the logo and on the header it appears smaller ... 

SVG
<img width="133" alt="LogoMudaDesk" src="https://user-images.githubusercontent.com/39558132/73012593-6a6c8480-3df5-11ea-89a0-3ee41ef145f5.png">

On header
<img width="114" alt="Captura de Tela 2020-01-23 às 15 46 29" src="https://user-images.githubusercontent.com/39558132/73013718-9852c880-3df7-11ea-9976-04d401460ff2.png">

In the header the Logo is: Width: 61px and Height: 24px, it is very small ...I inspected the code and this is the exact size we need (style = height: 52px) with a height of at least 52px as you said.

<img width="2019" alt="Captura de Tela 2020-01-23 às 15 44 39" src="https://user-images.githubusercontent.com/39558132/73013619-748f8280-3df7-11ea-9ff1-8e6ec3489285.png">

**Comment by lucca65** [comment]
@heltonlr this was made to make sure our logo looks right. Maybe the best course of action is to first take a look at the size of our logo, make sure it’s correct and then send us both muda’s and our logo in the same size and change on both

otherwise we’ll do a fix for muda that will mess up our logo and vice versa

**Comment by heltonlr** [comment]
> @heltonlr this was made to make sure our logo looks right. Maybe the best course of action is to first take a look at the size of our logo, make sure it’s correct and then send us both muda’s and our logo in the same size and change on both
> 
> otherwise we’ll do a fix for muda that will mess up our logo and vice versa

I will ckeck @lucca65

**Comment by lucca65** [comment]
Fixed on #229, now we show the community logo (which can be changed by community admins)
